### ISSUE TITLE
Store images to temp folder, not the user's album. iOS

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#10]
When using the test-app on iOS it appears that all images are stored to the users photo album. This is not ideal when developing an application. If you process/move/delete the image the user is prompted for the app gaining access to the photo album.

It would be better if the images are stored to a temp location, and the developer could choose to push the photos to the album themselves if that is what they really want. 

In addition, I really think that there should be some sort of way to say "I do not what the preview image". Maybe even a way to choose the preferred size?  

I have little-to-none experience with native iOS dev. so I am not able to help out much right now until I have read up on some stuff, but I found a nice SO question/answer which might be of help with this: http://stackoverflow.com/questions/14531912/storing-images-locally-on-an-ios-device

Anyways, great work thus far!

**Comment by leouze** [comment]
+1 to this. The plugin is great! It works very well except that it saves to the album which for the user will be annoying if he tries to take a picture and have both original and resized image in the camera roll.

**Comment by mbppower** [comment]
Hi guys. I'll work on this issue soon. Thanks for your feedback.

**Comment by stephan-nordnes-eriksen** [comment]
I have made a branch which solves this on ios. You might want to check it out. I did not make a PR since it changes the behaviour, and only on iOS for now.

https://github.com/stephan-nordnes-eriksen/CordovaCameraPreview

**Comment by leouze** [comment]
thanks @stephan-nordnes-eriksen , this is great!
Will try your branch when I sit on my next project.

Can you tell me how does it work?

**Comment by stephan-nordnes-eriksen** [comment]
It saves both preview and original, for now. But it saves them to your applications folder, not to the gallery. 

I would actually like if it only saved the original image, and did not try to do much more than that. If the developer want's a preview, then they can fix that themselves, or possibly provide a method that creates a preview for them. Eg.: `createPreview(image_url, width, height);`

**Comment by leouze** [comment]
That's exactly what I've wanted for my project. I just want it to be saved somewhere else but not on the camera roll. Will try it tomorrow! Thank you very much @stephan-nordnes-eriksen 

Cheers.

**Comment by joshuaohana** [comment]
@stephan-nordnes-eriksen You are a life saver!!! I used your plugin instead and it worked perfectly...

**Comment by DaCardinal** [comment]
@joshuaohana does stephans plugin work for both ios and android?

**Comment by stephan-nordnes-eriksen** [comment]
glad i could help @joshuaohana :)

@DaCardinal Yes

**Comment by leouze** [comment]
hi @stephan-nordnes-eriksen 
I just wanted to ask if your branch is also updated?
What I mean is the "toBack" param is also supported on your branch?

**Comment by stephan-nordnes-eriksen** [comment]
I haven't touched this since I made the branch back in February. Feel free to do PR if there are any features you lack there ;)

**Comment by andrenro** [comment]
@stephan-nordnes-eriksen @mbppower would be great to get the latest from both of these versions merged together :)!

**Comment by stephan-nordnes-eriksen** [comment]
I hate objective c, so I won't do that. If you need it feel free to create a pull request ;)

**Comment by mbppower** [comment]
Hi guys, I would really like to improve this project, but I've out of time for now, so if anyone that is working on this could do a PR, that would be great.
