### ISSUE TITLE
Camera crashes app on bigger preview size.

### ISSUE THREAD

**Issue by bunkovic** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#100]
Hello. 
I am trying to inster CameraPreview into my application. I am finding difficulty with android preview size.
I found a code snippet for finding effectiveDeviceWidth/Height:
`function effectiveDeviceWidth() {
        var deviceWidth = window.orientation == 0 ? window.screen.width : window.screen.height  ;

```
    if (navigator.userAgent.indexOf('Android') >= 0 && window.devicePixelRatio) {
        console.log("effectiveDeviceWidth(): " + "DEVICE_PIXEL RATIO = " + window.devicePixelRatio);
     deviceWidth = deviceWidth / window.devicePixelRatio;
   }
    console.log("effectiveDeviceWidth(): " + "DEVICE_WIDTH = " + deviceWidth);
    return deviceWidth;
}
```

function effectiveDeviceHeight() {
        var deviceHeight = window.orientation == 0 ?  window.screen.height : window.screen.width ;

```
   if (navigator.userAgent.indexOf('Android') >= 0 && window.devicePixelRatio) {
      deviceHeight = deviceHeight / window.devicePixelRatio;
   }
    console.log("effectiveDeviceHeight(): " + "DEVICE_HEIGHT = " + deviceHeight);


    return deviceHeight;
}`
```

Problem is, i do not want to divide the pixels by 2, but when i don't the app crashes on Android (on iOS it works swell).

**Comment by westonganger** [comment]
This is likely fixed in master as many updates have occuring. Closing.
