### ISSUE TITLE
Add parameters to controller?

### ISSUE THREAD

**Issue by ChrisR19** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#101]
Hello, I'm trying to use this plugin in an ionic app, but it doesn't work.
Do I have to add any further parameters to the controller, after installing the plugin? 
Or do I have to link to the plugin in the index.html?
Thanks!

**Comment by erperejildo** [comment]
I'm not using Ionic but my app is AngularJS.
What problem have you got?
I only had to add in my config.xml this line (for Cordova 6):
`<plugin name="cordova-plugin-camera-preview" spec="~0.0.8" />`
