### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by shirk3y** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#102]
The last commit is 5 months old, and there is more than 50 unresolved issues. Is anybody still working on this code on some fork?

**Comment by westonganger** [comment]
I have privileges on this repo. I was working on it a little while back but currently don't have much time or app needs to work on it.

I have had good success with skanygin's fork. I started some very basic work to merge this into master on the branch called skanygin in this repo. 

Any future development should probably performed on the skanygin branch. We can merge it to master once its stable.

**Comment by westonganger** [comment]
If people can help me determine which issues are valid, that would help a bit to clean this up. I have some time for admin work but am not super familiar with the native portions of the code.

**Comment by erperejildo** [comment]
I'm creating an app to share photos and I'm using this plugin. I wouldn't have any problem to find and fix problems in the JavaScript part and even to add some features as well.

**Comment by westonganger** [comment]
I started doing some work on [this fork](https://github.com/westonganger/cordova-plugin-camera-preview) here which I plan to merge to master once its stable. I've changed the options portion of the JS but its not functioning correctly yet and added some features that others have added in their forks. So please start your work there and send pull request there. https://github.com/westonganger/cordova-plugin-camera-preview I can merge changes very quickly as long as I know they have been tested.

Heres a sample app to help with testing (which also may need some work):
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app

**Comment by westonganger** [comment]
Latest details in #158
