### ISSUE TITLE
plugin unsupported PhonegapBuild

### ISSUE THREAD

**Issue by manufuentescr** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#103]
I add the line  <gap:plugin name="cordova-plugin-camera-preview" /> in the file config.xml

![adobe phonegap build - google chrome](https://cloud.githubusercontent.com/assets/2752593/14900260/ff87b806-0d4c-11e6-8f82-a5d377988c4f.jpg)

**Comment by agomezmoron** [comment]
Have you tried <plugin name="cordova-plugin-camera-preview" source="npm" spec="0.0.8"/>?
