### ISSUE TITLE
Crop picture

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#108]
More than an issue itself would be a new feature.

I'm trying to save the picture from a square preview but the picture loads with camera real size (is not squared).
The correct functionality would be like Instagram camera.
https://dl2.pushbulletusercontent.com/aUKsT9zF9M5coLdWVLMjvn3tntlLolX2/Screenshot_2016-05-18-18-26-41.png
https://dl2.pushbulletusercontent.com/adx5313xgmPlAvwsJvssp0BfS1gkPphu/Screenshot_2016-05-18-18-26-53.png

**Comment by vinimendes3** [comment]
+1

**Comment by erperejildo** [comment]
@vinimendes3 check this out:
https://github.com/erperejildo/cordova-plugin-preview-camera

**Comment by renatobezerra** [comment]
I have a same issue using iPhone 4s (ios 9.3.5) - Cordova 6.3.1

**Comment by patelchirag1987** [comment]
@erperejildo Have you got any solution for the same ? I am facing the same problem

**Comment by erperejildo** [comment]
@patelchirag1987 I fixed this a long time ago. Just use the latest version, I merged my changes changes. It should be fine.

If it's not might be a different issue
