### ISSUE TITLE
Failed to load resource: unsupported URL

### ISSUE THREAD

**Issue by DBZFYAM** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#109]
Hello all,

I've just tried this plugin as other similar plugins seem to be causing memory issues. So far I've got it up and running (it shows the rectangle and live camera feed), however, I need to get the image data as Base64 string to use in combination with a QR-scanner.

To do this, I tried updating the src of a image on the page (same as in the example/documentation), however when doing this, I get the following error on iOS:

Failed to load resource: unsupported URL
assets-library://asset/asset.JPG?id=2B7434FE-D9DE-4D44-8F42-105578D7160F&ext=JPGFailed to load resource: unsupported URL

The image is saved in the Photos app though. What am I doing wrong? How can I use the captured image in a <img src="">?

Thanks in advance for the help!
Regards,
Stefan

**Comment by marty-krishner** [comment]
+1

**Comment by fitra90** [comment]
@Eli13 Where did you put that code?

**Comment by Eli13** [comment]
Inside the setOnPictureTakenHandler callback.

**Comment by fitra90** [comment]
@Eli13 Thanks, it works for me :) 
@DBZFYAM you should try this

**Comment by KamranakwardaK** [comment]
I dont get it @Eli13 , should I put that inside CameraPreview.js ???

**Comment by westonganger** [comment]
Things have changed regarding output of taking a picture. Please use master and re-read the readme.

**Comment by darkthsideous** [comment]
@Eli13 @fitra90 where did you add yours 
var PLUGIN_NAME = "CameraPreview";

var CameraPreview = function() {};

CameraPreview.setOnPictureTakenHandler = function(onPictureTaken) {

  exec(onPictureTaken, onPictureTaken, PLUGIN_NAME, "setOnPictureTakenHandler", []);
  resolveLocalFileSystemURL(result[1], function (fileEntry) {
    fileEntry.file(function (file) {
      var reader = new FileReader();
      reader.onloadend = function (event) {
        $("img#myImg").attr('src', event.target.result);
      };
      reader.readAsDataURL(file);
    });
  });
};

//@param rect {x: 0, y: 0, width: 100, height:100}
//@param defaultCamera "front" | "back"
CameraPreview.startCamera = function(rect, defaultCamera, tapEnabled, dragEnabled, toBack, alpha) {
  if (typeof(alpha) === 'undefined') alpha = 1;
  exec(null, null, PLUGIN_NAME, "startCamera", [rect.x, rect.y, rect.width, rect.height, defaultCamera, !!tapEnabled, !!dragEnabled, !!toBack, alpha]);
};
