### ISSUE TITLE
Picture loses quality in canvas

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#110]
I've got a picture with quality and when I try to create a canvas with it the image in canvas loses quality.
I assign the url for normal image and after that I create the canvas:

```
cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result) {
        document.getElementById('originalPicture').src = result[0]; //originalPicturePath;
        // test
        //img.src = "https://wallpaperscraft.com/image/cat_face_glasses_thick_65455_1280x720.jpg";
        img.src = result[0];
        $scope.createCanvas();
});
```

```
$scope.createCanvas = function() {
      var canvas = document.getElementById('canvas');
      var ctx = canvas.getContext('2d');

      // enable Cross Origin Image Editing
      img.crossOrigin = '';

      // image for canvas loaded
      img.onload = function() {
        canvas.width  = window.innerWidth;
        canvas.height = window.innerWidth;
        console.log('En canvas: '+img.src);
        // fix blurry images
        ctx.imageSmoothingEnabled = false;
        canvas.enableRetinaScaling = true; 
        ctx.drawImage(img, 0, 0, 300, 300);
      };
    };
```

This is the result (the first one doesn't have a correct size, but is ok):
https://dl2.pushbulletusercontent.com/y6sedhVUb79EP1k7tSaKOFxvNaS0nuTZ/Screenshot_2016-05-19-17-10-41.png
And this is the result with a normal online image (see first block of code) which looks ok:
https://dl2.pushbulletusercontent.com/8WADXQ83oa30335Mjlz2CMk0WDUl7tOk/Screenshot_2016-05-19-17-17-07.png

If I don't change the canvas image size the image keep its quality:
`ctx.drawImage(img, 0, 0);`
But I would need a smaller size.

What am I doing wrong?

**Comment by erperejildo** [comment]
I tried with another device which camera has 1280x720 and looks fine. Mine (the bad one) is 1920x1080.
I still looking into it.

**Comment by Luukschoen** [comment]
@erperejildo did you ever solved this? I'm currently experiencing the same behaviour on my S7 edge.

**Comment by erperejildo** [comment]
@Luukschoen yes, but to be honest I can't remember. I think I used a different way.
This is my component anyway so you can take a look into it to follow the same way:
https://codeshare.io/G8j1A5

The function still called `createCanvas` so probably I'd have to change it.

Hope this helps
