### ISSUE TITLE
Application stopped unexpectedly 

### ISSUE THREAD

**Issue by iamrutvik** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#112]
This is my code in apache cordova : 

In script tag : 
'
            function OpenCamera() {
                alert(1);
                var tapEnabled = true; //enable tap take picture
                var dragEnabled = true; //enable preview box drag across the screen
                var toBack = true; //send preview box to the back of the webview
                var rect = { x: 100, y: 100, width: 200, height: 200 };
                cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack);
                cordova.plugins.camerapreview.show();
            }

```
    <button onclick="OpenCamera();">Open Cam</button>'
```

What is the issue? Am i doing something wrong?

**Comment by iamrutvik** [comment]
I solved it. It is because In android 6, App should have permission to access Camera.

**Comment by barklund** [comment]
@iamrutvik, you solved that how? By asking for permission where and how?

**Comment by iamrutvik** [comment]
The problem exists only for Mashmallow. You need to allow use of camera application for this plugin to work in settings.

Second plugin should throw an error like "access to camera application is denied." or ask for permission to allow access.

**Comment by westonganger** [comment]
Permission are now fixed in master.
