### ISSUE TITLE
Triyng to use the plugin with Meteor

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#113]
I'm developing a full stack app with Meteor + Angular and I've tried this plugin in an Angular project with good results. I had no problems installing the plugin on Meteor app but when I try to run the server I've got this problem:

> While adding plugin com.mbppower.camerapreview@0.0.8 to Cordova project:
> Cordova error: Failed to fetch plugin com.mbppower.camerapreview@0.0.8
> via registry.
> Probably this is either a connection problem, or plugin spec is
> incorrect.
> Check your connection and plugin name/version/URL.
> Error: Registry returned 404 for GET on
> https://registry.npmjs.org/com.mbppower.camerapreview
> at registry.fetch.fail.then.pinfo

The object in that url is empty but for example the camera plugin is ok:
https://registry.npmjs.org/cordova-plugin-camera

Any ideas?

**Comment by erperejildo** [comment]
https://forums.meteor.com/t/meteor-and-cordova-plugins/24327

**Comment by erperejildo** [comment]
The problem is only with this repository, with this one I don't have any problem:
https://www.npmjs.com/package/cordova-camera-preview

Any help @westonganger?

**Comment by gkrizek** [comment]
That npm repo seems out of date. I just added this to my Meteor project a few days ago with no problem. I did it from the Cordova library. So I installed it like:
`meteor add cordova:cordova-camera-preview@1.0.6`
I haven't had any issues so far.

**Comment by erperejildo** [comment]
I tried again and works now with version 0.0.8
