### ISSUE TITLE
Low resolution of preview image

### ISSUE THREAD

**Issue by zyf0330** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#115]
The preview image has a 600x600 resolution which is so low. I have add auto focus and make `optimalSize` a best size 1080P, but it just influences originalImage which is 1080P now not previewImage.
What I want is previewImage, so is there a solution?

**Comment by Djagu** [comment]
@zyf0330 : Hey I needed this plugin for a big app, so I fixed all the issues I could find and added the flash to the plugin...
Here is the working fork : https://github.com/Djagu/CordovaCameraPreview

**Comment by zyf0330** [comment]
Thanks, I will taste it.

Djagu <notifications@github.com>于2016年6月26日周日 上午12:04写道：

> @zyf0330 <https://github.com/zyf0330> : Hey I needed this plugin for a
> big app, so I fixed all the issues I could find and added the flash to the
> plugin...
> Here is the working fork : https://github.com/Djagu/CordovaCameraPreview
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/115#issuecomment-228552577>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZ5gSCh0FKgMhZZOZxWY_0NZrENTuPZks5qPVF1gaJpZM4I0D3->
> .
>
-- 

追随

**Comment by erperejildo** [comment]
There is another one here if you wanna try it:
https://github.com/erperejildo/cordova-plugin-preview-camera

**Comment by zyf0330** [comment]
@erperejildo maybe you should change the words about how to install it by cordova CLI

**Comment by erperejildo** [comment]
Is a copy with a few more features of this repository, the rest is the same, including readme (except urls)

**Comment by alexdinca** [comment]
I had a problem with this original plugin where the live preview of the camera had a really low resolution and also the original picture taken [0] was also of low quality.

But @erperejildo's version worked flawless, thanks mate!

**Comment by erperejildo** [comment]
It still having some bugs, mostly when you zoom a portrait or landscape image. I have to take a deeper look into it

**Comment by erperejildo** [comment]
@alexdinca can you try with new version (not from npm)

**Comment by westonganger** [comment]
This should now be fixed in master closing.
