### ISSUE TITLE
IOS toBack, Image Preview is not working at all

### ISSUE THREAD

**Issue by KamranAliKhan01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#118]
Is there anyone with the solution?

**Comment by KamranakwardaK** [comment]
@westonganger

**Comment by paramtrivedi** [comment]
I am having the same issue. @westonganger Can you please comment?

**Comment by KamranakwardaK** [comment]
@paramtrivedi Do you know how to record a video in it?

**Comment by paramtrivedi** [comment]
No, The plugin is not working at all for me in iOS. @KamranakwardaK , Is it working for you?

**Comment by KamranakwardaK** [comment]
@paramtrivedi Yes, Its working and I can help you... tell me whats the error you are getting ?

**Comment by KamranakwardaK** [comment]
Install the plugin and replace the CameraPreview to cordova.plugins.camerapreview in index.js and add <gap:plugin name="cordova-plugin-camera-preview" /> to your Config.xml

**Comment by paramtrivedi** [comment]
@KamranakwardaK Thanks for the help. I got it working.

**Comment by blckshrk** [comment]
I have the same issue, the preview does work if put `toBack : true` in `CameraPreview.startCamera` options. :-(

**Comment by KamranakwardaK** [comment]
I have mentioned above

**Comment by blckshrk** [comment]
@KamranakwardaK Forget it, it was the fucking `ion-view` background... Sorry!

**Comment by KamranakwardaK** [comment]
Is it working?

**Comment by blckshrk** [comment]
Yes ! I just did something like this : 

```scss
html, body, ion-view {
    background-color: transparent !important;
}
```

 and use `CameraPreview` instead of `cordova.plugins.camerapreview` in my code.

**Comment by KamranakwardaK** [comment]
Are you familiar to objective c or can you add video recording feature in
it?

**Comment by blckshrk** [comment]
@KamranakwardaK Not really, I know a little of objective-c but I do not have much time to spend on it... but I gonna look at the code. No promesses :)

In fact, I think there is a bug in this plugin. Sometime the camera seem not start. If I kill the app and restarts it that works. I dont know if it's on the native side or the JS one.

**Comment by KamranakwardaK** [comment]
Its must be js

**Comment by blckshrk** [comment]
I will take a look

**Comment by blckshrk** [comment]
It seems to work if you clone this version `https://github.com/westonganger/cordova-plugin-camera-preview.git` (which is master and actually version 0.9.0).

**Comment by KamranakwardaK** [comment]
You mean video recording?

**Comment by blckshrk** [comment]
No I mean the toBack option. I think you should maybe open a new topic about the video recording functionality.

**Comment by mikewagz** [comment]
I'm still unable to see the Camera Preview view when using `toBack=true`.  It seems to be blocked by a black overlay (what looks like the UIWebBrowerView in XCode visual debugger), so I see my HTML overlay buttons but not the camera preview, only a black background.  Here's what I've tried so far:

- In XCode, set the .xib 'background' to 'Clear Color' and unchecked 'Opaque' box.
- In MainViewController.m `viewDidLoad` method, added:

```
self.webView.opaque = NO;
self.webView.backgroundColor = [UIColor clearColor];
self.view.opaque = NO;
self.view.backgroundColor = [UIColor clearColor];
```
- In CameraPreview.m `startCamera` method, within the `if(toBack){` block, I added:

```
self.webView.opaque = NO;
self.webView.backgroundColor = [UIColor clearColor];
```

- I also added `glClearColor(0, 0, 0, 0);` after `glBindRenderbuffer(GL_RENDERBUFFER, _renderBuffer);` in CameraRenderController.m

- All HTML elements, including `<html>, <body>, <ion-app>` etc are set to `background-color:transparent;`

Has anyone gotten this working for iOS?

**Comment by jladbrook** [comment]
Try this (tested on iOS 10). It looks like it's related to the styling of the nav-decor component and the background-color being black.

```
var navDecor = document.getElementsByClassName("nav-decor").item(0);
navDecor.style.backgroundColor = "transparent";
```

**Comment by benydc** [comment]
This is fixed now.

**Comment by darkthsideous** [comment]
@KamranAliKhan01 I needed you iOS
