### ISSUE TITLE
[FIXED] IOS clear background

### ISSUE THREAD

**Issue by KamranAliKhan01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#120]
Just add 
glClearColor(0, 0, 0, 0);
in CameraRendarControl.m

**Comment by maxharland** [comment]
Where exactly did you add the line?

**Comment by KamranakwardaK** [comment]
After 
glBindRenderbuffer
in CameraRendarControl.m
You can just search that

**Comment by mikewagz** [comment]
I'm still encountering this issue.  If I send the CameraPreview toBack=true, all I see is a black background.  I have set every HTML element, all the way to <html>, to background-color:transparent.

**Comment by KamranAliKhan01** [comment]
@Michael Wagstaff

If its IOS than I can help you

**Comment by laaaaaaky** [comment]
@KamranAliKhan01 I add glClearColor(0, 0, 0, 0); after glBindRenderbuffer  in CameraRendarControl.m but still no work!

**Comment by mikewagz** [comment]
@KamranAliKhan01 - many thanks.  Yes, it is iOS via the Ionic 2 RC2 platform.  Here's what I've tried so far:

- In XCode, set the .xib 'background' to 'Clear Color' and unchecked 'Opaque' box.
- In MainViewController.m viewDidLoad method, added:

```
self.webView.opaque = NO;
self.webView.backgroundColor = [UIColor clearColor];
self.view.opaque = NO;
self.view.backgroundColor = [UIColor clearColor];
```
- In CameraPreview.m startCamera method, within the `if(toBack){` block, I added:

```
self.webView.opaque = NO;
self.webView.backgroundColor = [UIColor clearColor];
```

- I also added `glClearColor(0, 0, 0, 0);` after `glBindRenderbuffer(GL_RENDERBUFFER, _renderBuffer);` in CameraRenderController.m

- All HTML elements, including <html>, <body>, <ion-app> etc are set to `background-color:transparent;`

Thank you!

**Comment by Luukschoen** [comment]
This is when using Ionic, definitely an issue with setting a transparency. You need to set the nav-decor transparent as well, while this doesn't seem to be needed when using it for Android only. After that all works fine.

**Comment by westonganger** [comment]
You definately need to make a few html items `background-color: transparent;`. Fiddle around with that and you'll solve your issue.

**Comment by marisananakul** [comment]
@KamranAliKhan01 I'm having the same issue as @mikewagz  . Do you have any insight on the iOS side? I would truly appreciate any help on this. Thanks!

**Comment by darkthsideous** [comment]
@KamranAliKhan01 @marisananakul Any update on these issues.

**Comment by mikewagz** [comment]
Here's what ended up working for me:

```
html, body, ion-app, ion-content, ion-page, .nav-decor{
  background-color: transparent !important;
}
```

**Comment by darkthsideous** [comment]
@mikewagz thanks mike. Yeah the new plugin didn't work for some reason fought with it all week. Im tweaking the 0.088- version

**Comment by marisananakul** [comment]
@darkthsideous I did exactly what @mikewagz did but I put that in the src/app/app.scss. Hope that helps!

**Comment by darkthsideous** [comment]
@mikewagz @marisananakul OK trying that now already hit first bump. In mainViewController.xib
opened file I get a view of the white screen but no option to set it to clear. IS there a certain file I can make that change?

**Comment by darkthsideous** [comment]
@marisananakul @mikewagz Got it working with your changes in Xcode. Thanks Guys!!
