### ISSUE TITLE
Does it work with Ionic ?

### ISSUE THREAD

**Issue by hupptech** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#121]
I added this to my ionic project, but doesn't show camera at all. Has anyone tried it. Please suggest.

**Comment by piyushdutta** [comment]
trying it now. Will let you know as soon as we fix some bugs on it. Before you build it you need to add corodova.js and cordova.camera.js.
It's showing us startCamera undefined. But i am pretty sure it's just some bug that we haven't fixed. So we are fixing it currently.

**Comment by hupptech** [comment]
@piyushdutta thanks. 

I did add cordova.js and cordova.camera.js but nothing.. nothing just came up. not even errors. So we were confused.

**Comment by Rakonda** [comment]
i confirm this, same issue with my app, nothing came up at all.

**Comment by piyushdutta** [comment]
well how come you guys are getting nothing. I am getting a error require not recognized in camerapreview.js. If somehow we can fix that the plugin should work. We even tried and consoling it after device ready but their seems to be something wrong. Still we are trying on our end. Will report as soon we make it work.

**Comment by KamranakwardaK** [comment]
Check the #118

**Comment by piyushdutta** [comment]
hey guys we got it working. You need to call it in the html page where in your calling this. I will upload a demo script as i have to skim out a few code and give it to you all for testing.
For enabling particular features you can use [this](https://github.com/MattKetmo/darkroomjs)

**Comment by marko1943** [comment]
I pretty much read and tried all the fixes and issues posted here and I couldn't get toBack:true to work with Android 6. Any help?
