### ISSUE TITLE
Video Capture/ Record

### ISSUE THREAD

**Issue by KamranAliKhan01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#122]

**Comment by paramtrivedi** [comment]
@KamranakwardaK  Were you able to capture the video with the help of this plugin? Or do you know a way to capture the video and get the link for the captured video?

**Comment by KamranakwardaK** [comment]
@paramtrivedi No, its not ... I'm not good in Objective C and @westonganger in currently not working on this plugin, if anyone could add these features in this plugin that will make it one of the best ionic plugin to use native feature!

**Comment by paramtrivedi** [comment]
@KamranakwardaK I will try that and let you know if I can. 
Thanks

**Comment by KamranakwardaK** [comment]
@paramtrivedi Can you do that???

**Comment by hugobessa** [comment]
Hey @KamranakwardaK, is video recording working for android?

**Comment by vintage** [comment]
Are there any news about capturing whole video from the preview instead of just a picture for iOS or Android?

**Comment by westonganger** [comment]
Duplicate. Closing.

**Comment by 2diegoduque** [comment]
¿Ningún avance para grabar video con este plugin?
