### ISSUE TITLE
cannot find symbol PermissionHelper

### ISSUE THREAD

**Issue by michaelsandner** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#123]
I only installed the plugin and tried to build the app. Buti get this error.

error: cannot find symbol import org.apache.cordova.PermissionHelper;

**Comment by shrijan** [comment]
Same here any solution

**Comment by CodeGenie** [comment]
The PermissionHelper library moved to https://github.com/apache/cordova-plugin-compat in newer versions of Cordova. Install that plugin then you should have a successful build.

**Comment by CodeGenie** [comment]
The PermissionHelper class moved to https://github.com/apache/cordova-plugin-compat in newer versions of Cordova. Install that plugin then you should have a successful build.

**Comment by sundayhd** [comment]
Thanks 👍

**Comment by lordlaw** [comment]
installed latest cordova plugin compat 1.1.0
still not working

**Comment by marcelo-ribeiro** [comment]
`cordova plugin rm cordova-plugin-compat --save --force`
`cordova plugin add https://github.com/apache/cordova-plugin-compat.git --save`
`ionic run android`

**Comment by westonganger** [comment]
This should now be fixed in master. Please re-read the readme as things have changed.

**Comment by sJonatas** [comment]
@marcelo-ribeiro great (y)
