### ISSUE TITLE
setOnPictureTakenHandle is not working as expected

### ISSUE THREAD

**Issue by Velourium** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#124]
Hi everyone,

in the docs you gave an example like this:

```
cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result){
    document.getElementById('originalPicture').src = result[0];//originalPicturePath;
    document.getElementById('previewPicture').src = result[1];//previewPicturePath;
});
```

but when using setOnPictureTakenHandler like this, it just has preview image as a result (base64 image string, not the path), and no second parameter at all. Obvously, I get only previewPicture but I need originalPicture also. How do I get original camera picture with full quality? 
Right now I can only get this preview image and if the phone has low display resolution it will produce crappy image, since all this handler gets, as a result, is an image with DISPLAY resolution (720x1280), not image with original CAMERA resolution (8mpx).

Am I wrong or this setOnPictureTakenHandler example in your documentation is completely wrong? How can I get original image?

**Comment by rafaelbuiu** [comment]
Use the version below which return the path of the preview image

https://github.com/stephan-nordnes-eriksen/CordovaCameraPreview

**Comment by westonganger** [comment]
The takePicture has been changed in master. Please follow the latest instructions in the readme.
