### ISSUE TITLE
freeze image

### ISSUE THREAD

**Issue by danmobilers** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#126]
Hello everybody, I would like to take a doubt.
You can simulate a freeze image? I'm working on a project where with a click I freeze the image and if it is in good condition, with a longpress generate the image to be saved. Currently simulate freezing superimposing the image generated on the html, but there is a delay and the size of the generated image does not match.
Any tips?
Sorry for my bad English.

**Comment by westonganger** [comment]
You would have to save the file as a base64 string with which you can choose to save to file if its approved.

**Comment by danmobilers** [comment]
Thanks!!!!
