### ISSUE TITLE
startCamera doesn't work when toBack is set to false

### ISSUE THREAD

**Issue by zyf0330** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#127]
When I set `toBack: false`, I cannot see the preview box and no error appears. And If I set `toBack: true`, the box appears, but background becomes black or gray unless I set `backgroundColor: white`, and even if I reload page it is still like that. Another problem occurs at the same time is `dragEnable: true` is not effective. Then I set `toBack: false` again, I can startCamera now and drag normally, but backgroundColor is still black or gray.

**Comment by vicheanak** [comment]
I'm having the same issue. Working fine on Android, but problem with iOS. Has anyone found the solution yet?

**Comment by Luukschoen** [comment]
This is when using Ionic, definitely an issue with setting a transparency. You need to set the nav-decor transparent as well, while this doesn't seem to be needed when using it for Android only. After that all works fine.

**Comment by erperejildo** [comment]
Fixed here: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/129
