### ISSUE TITLE
Move preview to back

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#129]
Is it possible to add elements above camera layer? I'd like to add the switch button and a circle.

**Comment by danmobilers** [comment]
Yes, it is possible! For your images, use z-index> = 3 and absolute position. See how was my example. Only Fawn problems with delayed setOnPictureTakenHandler ...
![unnamed](https://cloud.githubusercontent.com/assets/15742721/18218416/f93e6f44-7138-11e6-861b-2af6f1c62c27.jpg)

**Comment by erperejildo** [comment]
The first think I have tried was that, to make the element absolute with a z-index really high but I doesn't work to me.

**Comment by danmobilers** [comment]
You are using a framework for development? If you can expose a portion of your html and css respectively to the camera screen. I wish I could help lo.Ah, else, your camera setting is for the back of the html?

startaCamera function () {
cordova.plugins.camerapreview.startCamera ({x: 0, y: 0, width: larguraTela, height: alturaTela}, "back", tapEnabled, dragEnabled, Toback);
}

Sorry my bad English, but I use google translator to communicate.

hug

**Comment by erperejildo** [comment]
I'm using Meteor and AngularJS. For the style I'm working with Sass but if it just a css fix I think all of this wouldn't be a problem.

I've got my js in this other post:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/130
But the camera functionality is working perfectly, so I think this wouldn't be related.

For the css I'm using a random box with this style:
```
.box {
  position: absolute;
  margin: 200px; // same position as camera
  z-index: 1000; // this should be enough
}
```

Don't worry, it's ok, I appreciated the help  ;)

Cheers

**Comment by danmobilers** [comment]
I understand, u are using sass. Indeed, if the camera's features are properly only fits the layers of same style. Only to make sure that your .box layer is above the camera and not behind the body or some element, we could do a little test?

.box {
   position: absolute;
   width: 200px;
   height: 140px;
   top: 200px;
   left: 50%;
   margin-left: -100px;
   background: RGBA (0,0,0,0.6);
   z-index: 1000; // This shouldnt be enough
}

This div .box is created dynamically? If possible, you could expose the piece of code where you insert your button or icon ?.   Cheers     :D

**Comment by danmobilers** [comment]
I forgot a detail,

.box {
    position: absolute! important;
    width: 200px;
    height: 140px;
    top: 200px;
    left: 50%;
    margin-left: -100px;
    background: RGBA (0,0,0,0.6);
    z-index: 1000! important; // This shouldnt be enough
}

**Comment by erperejildo** [comment]
No, the box is not dynamic.
I tried your style but I still having the same result, in fact is kind of the same, position absolute and z-index should be enough if you say it's like another element to be positioned.

How do you create the camera element?

**Comment by danmobilers** [comment]
Style css
body {
overflow-x: hidden! important;
background: transparent! important;
font-family: 'Raleway', sans-serif;
font-style: normal,
      font-weight: 300;
font-size: 12px! important;
letter-spacing: 0.5px;
word-spacing: 3px;
color: #fff! important;
}
#pageCaptura {        /*layer off camera*/
position: absolute;
top: 0;
left: 0;
right: 0;
bottom: 0;
background: transparent! important;
width: 100%;
height: 100%;
}

#funcoesCamera {        /* layer buttons box*/
position: absolute;
width: 800px;
height: 240px;
left: 50%;
margin-left: -400px;
background: RGBA (0,0,0,0.3);
border-radius: 20px;
padding: 50px;
top: 50%;
margin-top: -120px;
webkit-transition: all 0.4s ease;
   -moz-transition: all 0.4s ease;
   -o-transition: all 0.4s ease;
   -ms-transition: all 0.4s ease;
   transition: all 0.4s ease;
}

html code



       <div id="pageCaptura" data-role="page" class="pagina_captura hide ">
       		<div id="gridCaptura" class="animated zoomIn"><img src="img/grid_captura.png" class="img-responsive"/></div>
            <div id="divSeparador" class="hide animated zoomIn"><img src="img/separador.png" class="img-responsive"/></div>
            
            
            
            <div id="funcoesCamera" class="hide">
                <div  class="funcoesCamera animated fadeIn pt-page-delay400">
                    <div class="btn-group-justified">
                         	
                            
                            <a href="#" class="btn " >
                                <img src="img/capturaIcone.png" id="btnFotoCapturaImg"  class="img-responsive img-circle botoes"/>
                                Fotografar
                            </a>
                       
                            <a href="#" class="btn ">
                                <img src="img/btnodontograma.png" id="btnOdontogramaImg" class="img-responsive img-circle botoes"/>
                                Odontograma
                            </a>
                        
                            <a href="#"  class="btn">
                                <img src="img/checkupguiado.png" id="btnCheckupGuiadoImg" class="img-responsive img-circle botoes"/>
                                Checkup guiado
                            </a>
                        
                            <a href="#" class="btn">
                                <img src="img/sorriso-dividido.png" id="btnSeparadorImg" class="img-responsive img-circle botoes"/>
                                Sorriso dividido
                            </a>
                            
                            <a href="#" class="btn ">
                                <img src="img/filmar.png" id="btnVideoCapturaImg" class="img-responsive img-circle botoes"/>
                                Filmar
                            </a>
                        
                    </div>
            	</div>
            </div>
            
            
            
        <div id="configuracaoDaCamera" class="escondida sombraGoogle">    
            <div class=" btn-group">
            	<a href="#" id="cameraOriginal" class="btn text-center">
                	<img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />
                	Original
              	</a>
                <a href="#" id="cameraAzulada" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Azulada</a>
                <a href="#" id="cameraBlack" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Escura</a>
                <a href="#" id="cameraMono" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Mono</a>
                <a href="#" id="cameraNegativa" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Raio-x</a>
                <a href="#" id="cameraPosterizada" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Poster</a>
                <a href="#" id="cameraSepia" class="btn text-center"><img src="img/config.png" width="55" height="55" class="img-circle botoes"/><br />Sépia</a>
                <a href="#" id="cameraSolarizada" class="btn hide text-center"><img src="img/config.png" width="35" height="35" class="img-circle botoes"/><br />Solar</a>
                <a href="#" id="cameraBranca" class="btn hide text-center"><img src="img/config.png" width="35" height="35" class="img-circle botoes"/><br />White</a>
                
            </div>
       </div>
           
           
           
            	<div  id="fotosCapturadasTela" class="hide"></div>   
          
            
     </div>

**Comment by erperejildo** [comment]
That is pretty much the same, we've got similar css and html. You didn't share the js which probably would be the most different part.

```
cordova.plugins.camerapreview.startCamera({
      x: 0,
      y: window.innerHeight/2 - window.innerWidth/2,
      width: window.innerWidth,
      height: window.innerWidth
    }, "back", tapEnabled, dragEnabled);
    // show it up
    cordova.plugins.camerapreview.show();
```
This creates an element (the canvas for your camera) but this element (at least you took a different way) can't be behind other elements.

Do you use that function?

**Comment by danmobilers** [comment]
Oh, I do not really use the function show and hide the camera, only start and stop .. when I stop the camera, start another function that places another layer that I call screen ...

Follow my function to turn on and turn off the camera ....
And another thing, I am using using screen.width Screen.Height and the dimensions of the camera screen

var = larguraTela screen.width;
var = alturaTela Screen.Height;

cordova.plugins.camerapreview.setOnPictureTakenHandler (function (result) {

path = "file: ///" + result [1];
excluirCaminho = "file: ///" + result [0];
fotooriginal = result [1];
fotomini = result [0];
imageURI = result [0];

// Foto_original = '<img src = "' + fotooriginal + '" id = "imgOriginal" class = "img-responsive imagemOriginal" style = "position: fixed; top: 0px; left: 0px; z-index: 0;" /> ';
//$('#pageCaptura').append(foto_original);

var date = new Date ();
var day = data.getDate ();
if (day <10) {
day = "0" + day;
}
var months data.getMonth = () + 1;
if (Month <10) {
mes = "0" + months;
}
var year = data.getFullYear ();

disease = $ ( "# listaEnfermidadesCheckup") val ().;
descricao_galeria day = + '/' + month + '/' + year;
var = width_editar editor.width;
var = height_editar editor.height;
conta_foto ++;

// PHOTO MINIATURE ON SCREEN CAPTURE
conta_foto-1 = last;

thumbnail = $ ( '<img />', {
src: fotomini,
id 'imgP' + conta_foto,
class, 'img-responsive miniature transp animated fadeInLeft'

}) AppendTo ($ ( 'body').);
$ ( '# ImgP' + last) .removeClass ( 'animated fadeInLeft') addClass ( 'animated fadeOutRight') fadeOut (1000)..;
// Patient records
div_pront = $ ( '<div class = "short list"> <img src = "img / temOdonto.jpg" id = "temOdonto' + conta_foto + '" class = "temOdontograma hide" /> <img src = "img / temEditar. png "id =" temEditar '+ conta_foto +' "class =" temEditar hide "/> <img src =" img / temRaiox.png "id =" temRaioX '+ conta_foto +' "class =" temRaioX hide "/> <span id = "Tooth '+ conta_foto +'" class = "numeroDente hide"> </ span> </ div> '). click (function () {
$ (This) .find ( 'img') toggleClass ( 'Selected.');
$ (This) .find ( 'p.descricao') toggleClass ( 'Selected.');
$ (This) .find ( 'numeroDente.') ToggleClass ( 'Selected.');
}) PrependTo ($ ( '# capturaCheckupListaFotos0').);

pront = $ ( "<img />" {
src: fotomini,
id: "fotoProntuario" + conta_foto,
class: "fotoListaCheckup img-responsive flipped"

}) AppendTo (div_pront.);



texto_pront = $ ( '<p id = "texto_prontuario' + conta_foto + '" class = "description">' + descricao_galeria + '</ p>') appendTo (div_pront.);

//PHOTO GALLERY

div_galeria = $ ( '<div class = "col-xs-2"> <span class = "numeroDente hide"> </ span> </ div>'). click (function () {
$ (This) .find ( 'img.galeria') toggleClass ( 'Selected.');
$ (This) .find ( 'p.album') toggleClass ( 'Selected.');
}) PrependTo ($ ( '# galeriaCheckupLista').);

galeriax = $ ( "<img />" {
src: fotomini,
id: "imgGaleria" + conta_foto,
class, 'img-responsive gallery'

}) AppendTo (div_galeria.);

texto_div = $ ( '<p id = "texto_galeria' + conta_foto + '" class = "description album">' + descricao_galeria + '</ p>') appendTo (div_galeria.);

imgCheckup ++;
$ ( '# ImgOriginal') remove ().;
. $ ( '. ContaFotosCheck') html (imgCheckup);

uploadFile (imageURI);

// MontaFotonaMedida (imageURI);

if (odonto_mascara === true) {
odontogram ();
$ ( '# DoencaCheckup') addClass ( 'selectDoenca.');
}
$ ( '# ProntuarioSemRegistro') addClass ( 'hide').;
$ ( '# ListaCheckupRealizados0') removeClass ( 'hide').;


recupImagem (path);


});


//turn the camera on

startaCamera function () {
cordova.plugins.camerapreview.startCamera ({x: 0, y: 0, width: larguraTela, height: alturaTela}, "back", tapEnabled, dragEnabled, Toback);
}

// Turn off the camera
pararCamera function () {
cordova.plugins.camerapreview.stopCamera ();
}



// BY CLICKING THE CAPTURE SCREEN (ANDROID PC)
$ ( '# PageCaptura'). On ( "click", function () {
cordova.plugins.camerapreview.takePicture ({maxWidth: 871, maxHeight: 490});
});

So are we to solve your case?

Hope so

**Comment by erperejildo** [comment]
I'm not sure what the problem is...
I tried with the same js without show:
`cordova.plugins.camerapreview.startCamera ({x: 0, y: 0, width: larguraTela, height: alturaTela}, "back", tapEnabled, dragEnabled, Toback);`
but the result still being the same, can't put camera layer behind other elements.

**Comment by danmobilers** [comment]
Excuse my naivete, but this is no different?

My: cordova.plugins.camerapreview.startCamera ({x: 0, y: 0, width: larguraTela, height: alturaTela}, "back", tapEnabled, dragEnabled, Toback);

Your: cordova.plugins.camerapreview.startCamera ({x: 0, y: 0, width: 200, height: 200}, "back", tapEnabled, dragEnabled, true);

Toback = true?

Sorry I can not help you!

I am an adventurous programming    : /

**Comment by erperejildo** [comment]
Toback is a variable which could be true (send preview box to the back of the webview) or false.
Anyway, I tried with both and the result was the same unfortunately.

I'm pretty sure this is something related with that but no idea either.

Thanks!

**Comment by JimPee** [comment]
I'm having the same problem, @erperejildo have you found a solution to bring the cameraview behind the html elements? When I inspect it it even says that my body tag is behind the camerapreview.

**Comment by erperejildo** [comment]
Sorry for the delay @JimPee, haven't worked with this for a while.
Nope, still having the issue

**Comment by erperejildo** [comment]
@JimPee update to new version and try this:
```
CameraPreview.startCamera({
      x: 0,
      y: 0,
      width: 200,
      height: 200,
      camera: "back",
      tapPhoto: false,
      previewDrag: false,
      toBack: true
    });
```
and in the css:
```
html, body {
  background-color: transparent;
}
```

**Comment by danmobilers** [comment]
Yeah

**Comment by JulianArdila** [comment]
I use the same code of @erperejildo, but it's not working, does this work with capacitor?
