### ISSUE TITLE
Get picture w/o saving it

### ISSUE THREAD

**Issue by cfjedimaster** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#130]
Forgive me if this actually works already and I just didn't see it - but it would be nice if a developer could get the current picture without it actually saving the photo the gallery.

**Comment by erperejildo** [comment]
You mean get access to the picture while you are developing? In that case you should convert the image to base64

**Comment by cfjedimaster** [comment]
And is that possible? I don't see that documented as a method. I see it mentioned as something you can do with the picture once saved.

**Comment by erperejildo** [comment]
Try with this:
```
// when picture is taken
      cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result) {
        // convert the image to base64
        resolveLocalFileSystemURL('file:///'+result[1], function(fileEntry) {
          fileEntry.file(function(file) {
            var reader = new FileReader();
            reader.onload = function(event) {
             // this would be your image
              base64 = event.target.result; //Here is your base64 string
              // in this part I stop the loader spinner which I started to load in takePicture()
            };
            reader.readAsDataURL(file);
          });
        });
        that.stopCamera();
      });
```

**Comment by cfjedimaster** [comment]
Ah but to be clear - this requires a 'real' picture taking event - which means it gets saved to the gallery. Right?

**Comment by erperejildo** [comment]
No no, I don't save the picture. In fact, after take picture I've got another view to add filters and some stuffs.
I save the picture at the end in a hosting with a CDN, but never in my device.

**Comment by cfjedimaster** [comment]
Interesting. So to be clear - I call takePicture, and use your handler, and stopCamera is what prevents the data from doing what it would normally do - save to gallery. Right?

**Comment by erperejildo** [comment]
stopCamera() doesn't prevent to save the picture in your gallery, it's just to stop the preview (in my case when I take the picture I go to next step, so I stop the camera).

```
takePicture() {
    // you can start here you spinner o whatever
    cordova.plugins.camerapreview.takePicture({
      maxWidth: 1200,
      maxHeight: 1200
    });
  }

// start and show camera
  startCamera() {
    var tapEnabled = false;
    var dragEnabled = false;
    
    cordova.plugins.camerapreview.startCamera({
      x: 0,
      y: window.innerHeight/2 - window.innerWidth/2,
      width: window.innerWidth,
      height: window.innerWidth
    }, "back", tapEnabled, dragEnabled);
    // show it
    cordova.plugins.camerapreview.show();
  }

stopCamera() {
    this.camera = false;
    cordova.plugins.camerapreview.hide();
    // prevent problems with camera
    setTimeout(function() {
      cordova.plugins.camerapreview.stopCamera();
    }, 500);
  }
```

With these different functions you never save your picture into your gallery.
BTW, some lines are angular stuffs.

**Comment by cfjedimaster** [comment]
Sorry to be dense - so you said it doesn't stop the camera from saving to gallery - so what part of your code *does* do that?

**Comment by erperejildo** [comment]
The things is there is no part to say "don't save it into gallery" it's exactly the opposite, if you want to save it then you have to specify it when you take the picture (not sure right now how because I don't need it).
Anyway, resuming, **by default the picture is not saved**.

**Comment by cfjedimaster** [comment]
Ah - thank you! Is that clear in the docs - that you have to specifically make it save to the gallery?

**Comment by erperejildo** [comment]
I think that would be more related probably with the camera plugin itself. I mean, this plugin uses the normal camera plugin to do the rest of the work.
Take a look into a this repository: https://github.com/apache/cordova-plugin-camera
But I repeat, if you don't want to save the picture in your gallery when its taken should be ok by default (like in takePicture())

**Comment by cfjedimaster** [comment]
Ok - thank you for your help.

**Comment by erperejildo** [comment]
No worries ;)

**Comment by erperejildo** [comment]
BTW, I've created a new repository and I'm adding some features which another guys added here:
https://github.com/erperejildo/cordova-plugin-preview-camera

**Comment by cfjedimaster** [comment]
Ok, so I'm seeing the opposite of what you've described. When I do takePicture, it is saving to the gallery. I'm using Ionic Native. When I take a picture, it gets saved. It shouldn't, right?

Here is my ts:

https://gist.github.com/cfjedimaster/432acfe0b8bafc85d6e5bbfccebe4493

**Comment by erperejildo** [comment]
Haven't work with Ionic before but I'm using AngularJS as well.
I'd recommend use the normal camera plugin first:
http://ngcordova.com/docs/plugins/camera/
Add `saveToPhotoAlbum: false`

And then if works trying changing your `startCamera `function:
```
startCamera() {
    var tapEnabled = false;
    var dragEnabled = false;
    
    cordova.plugins.camerapreview.startCamera({
      x: 0,
      y: window.innerHeight/2 - window.innerWidth/2,
      width: window.innerWidth,
      height: window.innerWidth
    }, "back", tapEnabled, dragEnabled);
    // show it up
    cordova.plugins.camerapreview.show();
  }
```

**Comment by cfjedimaster** [comment]
"Add saveToPhotoAlbum: false"
That doesn't make sense though. I do have the Camera plugin. I am *not* calling it directly. I'm only calling this plugin.

**Comment by erperejildo** [comment]
I wanted to say to try the normal plugin (link above) first with that parameter on it.

The other test would be try your current plugin with exactly that `startCamera` function

**Comment by cfjedimaster** [comment]
... ok maybe I'm just confused. :) I do not doubt that the *Camera* plugin has the ability to take a picture and not save it. It is documented. It works. I'm not asking about that. I'm asking about *this* plugin and the ability to take a picture w/o saving it.

Is that not clear? Or am I missing something fundamental here? The *only* code I'm using is code for this plugin. I can fire up the preview just fine, take a picture, but it saves it. That's what I want to avoid.

**Comment by Craigstock** [comment]
Hi Guys,

Has anyone found a way to not save the two images that get captured using this plugin (on iOS)?

**Comment by numerized** [comment]
Hi There, I need this too, I don't want the plugin to save to my Camera Roll on Ios.
Is that possible ?

**Comment by Eli13** [comment]
Hi there!
The workaround I used is to save the pictures in the app folder instead of in the Asset Library. This is possible editing CameraPreview.m. I'm sorry if the code is not so clean, I'm not an iOS developer.
In method `- (void) invokeTakePicture`, after line `CGImageRef finalImage = [self.cameraRenderController.ciContext createCGImage:finalCImage fromRect:finalCImage.extent];` add this code that first deletes all the images previously saved (I found out that it was not always possible to override the image using the same name), than save the new picture.
Consider that I didn't keep the original picture. Since I needed to return the preview picture only,  I could remove almost all the code in with task 1 and task 2.

```
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);

            NSDate *today = [NSDate date];
            NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
            [dateFormat setDateFormat:@"MMddyyyy_HHmmssSS"];
            NSString *dateString = [dateFormat stringFromDate:today];
            NSString *filePath = [[paths objectAtIndex:0] stringByAppendingPathComponent:[NSString stringWithFormat:@"%@_image.jpg",dateString]];
            NSFileManager *fileManager = [NSFileManager defaultManager];
            NSError *error;
            int count;
            NSString *dirPath = [[paths objectAtIndex:0] stringByAppendingPathComponent:@""];
            NSString *remFilePath;
            NSArray *directoryContent = [[NSFileManager defaultManager] contentsOfDirectoryAtPath:dirPath error:NULL];
            for (count = 0; count < (int)[directoryContent count]; count++)
            {
                remFilePath =[directoryContent objectAtIndex:count];
                NSLog(@"File %d: %@", (count + 1), remFilePath);
                
                if ([remFilePath rangeOfString:@".jpg"].location == NSNotFound) {
                    NSLog(@"%@ was not a jpg", remFilePath);
                }
                else
                {
                
                    [fileManager removeItemAtPath:[[paths objectAtIndex:0] stringByAppendingPathComponent:remFilePath] error:&error];
                    if (error) {
                        NSLog(@"Could not delete file -:%@ ",[error localizedDescription]);
                    
                    }
                    else
                    {
                        NSLog(@"Successfully removed:%@ ",remFilePath);
                    }
                }
            }
            
            // Save image.
            UIImage *finalUImage = [[UIImage alloc] initWithCGImage:previewImage];
            [UIImageJPEGRepresentation(finalUImage,1) writeToFile:filePath atomically:YES];
```


At the end return correct filepath: 
```
[params addObject:@"hhhh"]; //I don't need this
[params addObject:filePath];
```

I really hope this can help someone!

**Comment by Robdeprop** [comment]
The solution of @Eli13 comes close, but isn't quite there yet. By adding that code, you still save the images to the iOS gallery. Also, the preview picture, rather than the original picture, gets saved to the app folder. I took the code and tweaked a bit more to not save the pictures to the iOS gallery at all anymore, and save the original picture to the app folder instead.

I forked this solution here, for anyone interested:
[https://github.com/Robdeprop/cordova-plugin-camera-preview](url)

**Comment by westonganger** [comment]
If this fix is helpful I encourage you to make a PR out of it. We need more PRs and less forks.

**Comment by Robdeprop** [comment]
It's not really a fix but more of an alternate functionality. Instead of saving to the gallery, it now saves to the app folder. For it to be useful as a PR here there should probably be an extra parameter for specifying where to save the taken pictures or so, but my fork does not feature any such functionality. Therefore I am reluctant to create a PR for it.

**Comment by mikewagz** [comment]
+1 for being able to pass in an option saveToCameraRoll:true/false

**Comment by joshuachestang** [comment]
+1

**Comment by rapideinternet** [comment]
+1
