### ISSUE TITLE
Camera Permission

### ISSUE THREAD

**Issue by finchen** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#131]
On android, the plugin is currently forcing to have a camera (in the manifest)

``` xml
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
```

it can be useful if it's a camera based app, but maybe it would be good if it is optional.
It is possible to test at runtime if a camera exists

``` java
/** Check if this device has a camera */
private boolean checkCameraHardware(Context context) {
    if (context.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA)){
        // this device has a camera
        return true;
    } else {
        // no camera on this device
        return false;
    }
}
```

On iOS it seems possible to check too

```
if ([UIImagePickerController isSourceTypeAvailable: UIImagePickerControllerSourceTypeCamera])
   // Has camera
```

Thanks!

**Comment by qpwr** [comment]
@finchen, did you manage to remove the forced permission by patching the plugin somehow? I tried removing them from some files, but they're still added to AndroidManifest.xml on every build...

**Comment by finchen** [comment]
Yes it did work. I cloned the project.
See the last 2 commits: https://github.com/finchen/cordova-plugin-camera-preview/commits/master
but I stopped using the plugin, so I don't know if it is working with the latest cordova version

**Comment by erperejildo** [comment]
I've never heard about this but feel free to open a PR with your changes please

**Comment by westonganger** [comment]
Permissions should now be fixed in master.

**Comment by maximilianloy** [comment]
How can I make the permissions optional? Currently it is required on my build, using latest commit on master (1cc03476ab986b4b704c74c9f2b643ff5164ab39)
