### ISSUE TITLE
Uncaught ReferenceError: CameraPreview is not defined

### ISSUE THREAD

**Issue by stardand** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#133]
$ cordova run android --device
Discovered plugin "cordova-plugin-camera-preview" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-camera-preview" via npm
Plugin "com.mbppower.camerapreview" already installed on android.
Plugin "com.mbppower.camerapreview" already installed on ios.
...

But when I run the app:

[INFO:CONSOLE(47)] "Uncaught ReferenceError: CameraPreview is not defined", source: file:///android_asset/www/js/index.js (47)
[INFO:CONSOLE(3)] "Uncaught ReferenceError: CameraPreview is not defined", source: file:///android_asset/www/js/index.js (3)

**Comment by stardand** [comment]
Seems to work if "CameraPreview" is replaced with "cordova.plugins.camerapreview"

**Comment by BJSingh** [comment]
I tried both( CameraPreview and cordova.plugins.camerapreview) way but not working. Getting same Uncaught error.

**Comment by erperejildo** [comment]
New version requires `CameraPreview`. Have a look to the new README file, was changed a few days ago.
Feel free to reopen if still having issues

**Comment by BJSingh** [comment]
Hello erperejildo,
I tried CameraPreview method still facing same issue. Below is my code screenshot with log error
![code_snippet](https://cloud.githubusercontent.com/assets/5358553/22969678/6085611a-f395-11e6-82ba-587b9f8a3a76.PNG)

**Comment by erperejildo** [comment]
Are you trying with last version on Github? Don't try the npm one

**Comment by BJSingh** [comment]
I installed plugin as mentioned on readme file cordova plugin add cordova-plugin-camera-preview. Is there any way to identify whether it is npm one or not.

**Comment by westonganger** [comment]
Instead use:

```
cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git --save
```

I am going to update the readme.

**Comment by BJSingh** [comment]
I added plugin still same error but when I viewed plugin it is listed. 

![plugin_list](https://cloud.githubusercontent.com/assets/5358553/22985387/4a16c926-f3ce-11e6-8cdc-0dd15b40db74.PNG)


And more thing I am not able to remove previous plugin by cordova plugin rm cordova-plugin-camera-preview
