### ISSUE TITLE
Different result for base64 image in iOS and Android

### ISSUE THREAD

**Issue by cmartineztdl** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#136]
Working with android (first 100 chars base64 image):  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0d"

Working with iOS:
"data:image/jpeg;base64/9j/...."

**Comment by westonganger** [comment]
This is now fixed in master. All base64 data is now returned without the prepended img src metadata.
