### ISSUE TITLE
Crash with iOS 10

### ISSUE THREAD

**Issue by Damien514** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#137]
Hi there,
The plugin does not seems to work with iOS 10. My iPhone / simulator doesn’t even ask for authorization, crashing before that step.

Any clue on how to resolve that?

Thanks a lot!

**Comment by rafaelbuiu** [comment]
@Damien514 You should modify your Info.plist adding a description for Camera usage

![image](https://cloud.githubusercontent.com/assets/6061404/18945915/a18ab054-863d-11e6-9653-eac647d8a40a.png)

**Comment by PabloFNK** [comment]
@rafaelbuiu I've tested what you has said and it works. The problem is adding those permissions out of the platform folder just in case the platform is removed and added again.

**Comment by Xwalk-Company** [comment]
In plugin XML  in platform name = "ios"

```
<config-file target="*-Info.plist" parent="NSPhotoLibraryUsageDescription">
        <string>Muvzi use</string>
    </config-file>
    <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
        <string>Muvzi use</string>
    </config-file>
    <config-file target="*-Info.plist" parent="NSMicrophoneUsageDescription">
        <string>Muvzi use</string>
    </config-file>
    <config-file target="*-Info.plist" parent="NSContactsUsageDescription">
        <string>Muvzi use</string>
    </config-file>
    <config-file target="*-Info.plist" parent="NSCalendarsUsageDescription">
        <string>Muvzi use</string>
    </config-file>
    <config-file target="*-Info.plist" parent="NSBluetoothPeripheralUsageDescription">
        <string>Muvzi use</string>
    </config-file>
```

**Comment by gorghoa** [comment]
@Xwalk-Company's solution works fine but you had to install https://github.com/dpa99c/cordova-custom-config cordova plugin
