### ISSUE TITLE
code is not working with android 4.4.2 version model no.HTC Desire 526Gplus

### ISSUE THREAD

**Issue by agarwalnupur3** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#138]
My code is:
var tapEnabled = true; //enable tap take picture
var dragEnabled = true; //enable preview box drag across the screen
var toBack = true; //send preview box to the back of the webview
var rect = {x: 100, y: 100, width: 200, height:200};
cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack)

But I could not find any output with this.Help me reslove with this.

**Comment by KamranakwardaK** [comment]
Please add 

<gap:plugin name="cordova-plugin-camera-preview" />

to your config.xml and also       

xmlns:gap="http://phonegap.com/ns/1.0" 

inside <widget> tag

in your config.xml

**Comment by KamranakwardaK** [comment]
Also toBack = false to see if its not a background-color issue

**Comment by BernhardSmuts** [comment]
Good Day.

Has anyone got the example wiht the HTML cat working. I can not see CameraPreview as an object, always returns undefined and I have tried all the options I can think of...
