### ISSUE TITLE
Can not get CameraPreview object...Always Undefined

### ISSUE THREAD

**Issue by BernhardSmuts** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#140]
Good day all.

I have tried everything and I can not recognise the CameraPreview object.

I have used the standard cordova-plugin-camera as a reference to work from and where I can get the navigator.camera to return as an object, I structure it the exact same way and CameraPreview always returns as undefined.

I have tried building the plugin from all the forks associated with this plugin and have gone through as much of the code as I can understand, and everything seems to be fine but the CameraPreview is never an object to work on...

Is there anyone who could assist me in this?

Regards

**Comment by egibaja** [comment]
Hi

I got it working using the plugin in this branch 

https://github.com/westonganger/cordova-plugin-camera-preview

Use the version in the master branch and call the plugin with CameraPreview instead of cordova.plugin.camerapreview

**Comment by BernhardSmuts** [comment]
Hi @egibaja 

Thanks for the reply. I tried it an didn't seem to work. 

I tested it with the following setup:

1. I created a blank phonegap app with: `phonegap create camTest`
2. I installed the master branch using the github address: `cordova plugin add `https://github.com/westonganger/cordova-plugin-camera-preview`
The call to this object has already been set to CameraPreview and no where is cordova.plugins.camerapreview anymore.
3. I created an android platform: `phonegap platform add android`
4. I setup a button the `console.log(typeof navigator.camera )` //for the normal cordova camera object
5. I setup a button the `console.log(typeof CameraPreview )` //for the overlay camera 

However,
step 4 still returns object
step 5 returns undefined

Anything I am missing?

**Comment by egibaja** [comment]
Hi again,

Did you include <script type="text/javascript" src="cordova.js"></script> in your index.html file? 
Besides, I think you should add the platforms to your project before adding any plugin (not sure how important is this, I am pretty new with cordova myself)

A simplified version of a working version of my code is as follows:

```javascript
document.addEventListener('deviceready', function () {
      console.log('device ready')
      console.log(typeof navigator.camera)  // returns undefined
      console.log(typeof CameraPreview)  // returns 'function'
      CameraPreview.startCamera({ x: 0, y: 0, height: window.innerHeight, camera: 'back', toBack: true }) // camera is displayed. remember to set the background to transparent for the html and body tags
     // some more code
}, false)
```

Good luck!

**Comment by westonganger** [comment]
That will be the new API however its not yet implemented here, hopefully within the next couple of days. From now on always refer the this repository's readme for the documentation and API. 

We're stopping all these extended forks and want more PR's here.

**Comment by XaiNano** [comment]
In the browser, it console logs me: 
object
function
However, running my app on android(PhoneGap mobile app) gives me:
object
undefined
