### ISSUE TITLE
video capture wrong orientation in cordova

### ISSUE THREAD

**Issue by malvin91** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#143]
Hey guys ...
I am encountering some problem with Cordova Camera plugin and Android.

When taking video in Android, video is captured & saved in portrait mode but the url I am getting after upload is landscape mode :

    Myscript.SocialVideocapture = function(){
    var ramv;
    var options = {
    limit: 1,
    duration: 100000000
        
    };
    
    navigator.device.capture.captureVideo(onSuccess, onError, options);
    
    function onSuccess(mediaFiles) {
        
        VideoEditor.createThumbnail(
		trimSuccess, // success cb
		trimFail, // error cb
		{
		fileUri: mediaFiles[0].fullPath, // the path to the video on the device
		outputFileName: 'output-name', // the file name for the JPEG image
		atTime: 2, // optional, location in the video to create the thumbnail (in seconds)
		width: 320, // optional, width of the thumbnail
		height: 480, // optional, height of the thumbnail
		quality: 100 // optional, quality of the thumbnail (between 1 and 100)
		}
		);
        
        ramv=mediaFiles[0].fullPath;
        var cvid=Math.floor((Math.random() * 1000000) + 1);
        socialvideosendurl=mediaFiles[0].fullPath;
        
    }
    
    function onError(error) {
        
        
    }
    
    
}

[ Original Video File Uploaded](https://d1wst0behutosd.cloudfront.net/videos/11871769/33526249.mp4?Expires=1479992248&Signature=Sq3atTnO9PDnnB4qqcdkjSz9xQMlPQ~DDO2W9~fb5ZUxXZXfUidziN~ML~~ABHced7Xp6tj82froFP81EZFaa3Bf8gOyzu6ij~kgDSxfxRVzCGI0FAnpIkpljA1V-8Vcpifw6~E-JXdtNh6F8XnCbaHO9J35yrtsmeoQDcSLPBCA0nF6~RHYibbyFQOE-cS1npPPgo1nPus2RB5RbG6tDR7kD4h11ipjugA~uTtxgvI2Z7kGUF-kSpzhfoh48MdPKMXwsSduc-Qz1MQMX-IcYZNS6muPYIiNkejHNOmA-oPWrYHziAbViw4XaF8GR3I8-NafmzTr7L8VnfC1LG3DlQ__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ)

[Video File I am getting from server](http://appcdn.media/user_space/3dad4cff4494/posts/video/scvideo_1479983603_5679_new.mp4)

**Comment by berserker001** [comment]
Hi.Which one plugin are you using to capture video?

**Comment by h-morales** [comment]
I think this issue should have been posted to this plugin:
https://github.com/jbavari/cordova-plugin-video-editor

This is not for Camera Preview plugin
