### ISSUE TITLE
Preview position

### ISSUE THREAD

**Issue by NawazKhanMd** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#145]
Hi, if you see the example two screen shots of  the documentation, I wonder how to shape the window in to form of Cat ?? can we scroll the camera preview with the page

**Comment by Luukschoen** [comment]
You should move the camerapreview toback, and add the cat inside your HTML page. So i.e. set a background with a transparent cat out of the background, or put a full width/height image on top of your cameraview with the cat cut out

**Comment by NawazKhanMd** [comment]
Okay Lemme Try It , ThankYou @Luukschoen
