### ISSUE TITLE
I need help ionic 2 option toBack work 

### ISSUE THREAD

**Issue by wuilmerj24** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#146]
Hello I have an app with ionic 2 and add the plugin. But I do not know how I can make it show with the toback option

**Comment by chakke** [comment]
i set background-color for ion-app(index.html) and current page to transparent, so the camera should show as expected. working on android for me.

**Comment by wuilmerj24** [comment]
ok. ready thank you i can solve it.

**Comment by tordnilsen** [comment]
@wuilmerj24 Do you have a working Ionic example to share?

**Comment by wuilmerj24** [comment]
@tordnilsen hi. yes https://github.com/wuilmerj24/Enkiapp/blob/master/src/pages/profesionali/profesionali.ts

**Comment by wuilmerj24** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        
                 

    
        
            
                
                    
                
            
            
                
                    Join me on PeoplePerHour
                
            
        
        
            
                
                    
                
                
                    Wuilmer is using PeoplePerHour and thinks you need to check it out. 
                    Never heard of it? PeoplePerHour is a global freelance hub connecting revolutionaries around the world. Come splash the cash.
                    Your £20 gift will expire in 3 days. Don’t let Wuilmer down... :)
                
            
        
    


                 
                   
                 
                 



    
    	
    		
    			
                	ACCEPT INVITATION
            	
        	
        
    


                 

    
        
            
                Kind Regards,
                The PeoplePerHour Team
            
        
    

                                     
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                    © 2007 - 2017 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here

**Comment by wuilmerj24** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        

    
    
        
          Wuilmer gave you £20 to spend on PeoplePerHour
        
      

      
        
      

      
        
          
          
      
    


	
		Hello,
	
		Wuilmer has been on PeoplePerHour for 3 days and they've invited you to join as well. 
	
		Accept the invitation today and get £20 off your first purchase on PeoplePerHour
	
		



    
    	
    		
    			
                	Join now
            	
        	
        
    


	
		

    
        
            
                Kind Regards,
                The PPH Team
            
        
    



                    
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                    © 2007 - 2017 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here
