### ISSUE TITLE
Start from front camera

### ISSUE THREAD

**Issue by ronaldoasevedo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#148]
I put the front option but it does not start on the front camera, it always starts on the back of the smartphone!

Help!

**Comment by erperejildo** [comment]
Use this:
CameraPreview.startCamera({x: 0, y: 0, width: window.device.width, height: window.device.height, camera: "back", tapPhoto: true, previewDrag: false, toBack: false});

If doesn't work specify OS and phone model

**Comment by westonganger** [comment]
Closing as this should be working. Please ensure you are using the master version of the plugin.
