### ISSUE TITLE
Cannot find symbol: Buildhelper for Android

### ISSUE THREAD

**Issue by nc5ff** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#149]
I started getting an error after upgrading the camera plugin (not plugin-preview) version to 2.3.1 for Android. It says the symbol "org.apache.cordova.BuildHelper" cannot be found. with a carat pointing to the period symbol between cordova and BuildHelper. Can anyone help me with this? I'm not sure whether you need any more information about this. Let me know. Thanks.

**Comment by zabojad** [comment]
I'm having the same issue. @nc5ff have you solved it?

**Comment by nc5ff** [comment]
Man, I can't remember off the top of my head but I think I was using an older version of cordova. Did you try updating everything? I think that solved it for me.
