### ISSUE TITLE
Support for Video?

### ISSUE THREAD

**Issue by gitlovenotwar** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#150]
Hi, is this plugin support for video?

**Comment by vintage** [comment]
You mean the video capture? It's impossible currently - https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/122

**Comment by Pinbandit** [comment]
@vintage Is it able to capture multiple pictures in the same preview or capture automatically with Observable. Struggling to find another way

**Comment by erperejildo** [comment]
Have a look to this issue:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/150
