### ISSUE TITLE
Cordova Camera Preview Plugin Shows Preview Only After Re Orienting Screen

### ISSUE THREAD

**Issue by UnFlimFlammable** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#152]
I'm unable to show the camera preview image until I reorient the device, then it works fine. Until I reorient the device, it just shows a white screen. I checked the inspector and there are no errors, nor are there matching issues in the plugin repo. This occurs about 50% of the time, and I have no idea why.

I'm using this Cordova Plugin on IOS: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/tree/master/src/ios

I've tried manually reorienting the camera with this plugin: https://github.com/apache/cordova-plugin-screen-orientation

This is what I'm using to call the camera preview, its pretty much taken directly from the example code on the plugin repo.

    $('.app').css('display', 'none')
    $('body').css('background-color', 'transparent')

    var tapEnabled = true; //enable tap take picture
    var dragEnabled = true; //enable preview box drag across the screen
    var toBack = true; //send preview box to the back of the webview

    var rect = {x: 0, y: 0, width: $(window).width() , height:$(window).height()};

    cordova.plugins.camerapreview.startCamera(rect, "back", tapEnabled, dragEnabled, toBack)
    cordova.plugins.camerapreview.show();

    window.screen.lockOrientation('landscape');
    window.screen.lockOrientation('portrait');

**Comment by wwallace** [comment]
I'm having to do the same.

**Comment by QiaoyuanMaxDeng** [comment]
I am suffering the same issue. Camera version 2.3.1, iOS 9.2.1/10.0/10.1, Device iPad mini 2/iPad2/iPad Pro. 

My case is turning device in landscape than start run camera plugin to take a picture. I tried to load camera image after "Use photo", it shows white screen. I also tried to just do nothing, which should return to app, after "Use photo", it still shows white screen. If I turn the device to portrait, everything is back, then turn to landscape, it shows up correctly. This does not happen on portrait at all.

Please help. Thanks.

**Comment by flogr** [comment]
Could you fix this issue? I'm using the latest version of this plugin and experiencing the same error on an ipad air with ios 10.2. after changing orientation i see a camera preview.

Any help would be highly appreciated. Thx!

**Comment by benydc** [comment]
I have same issue, I really need this fixed please!

**Comment by sjdrew** [comment]
Same issue also. IOS 10.2. Only seems to do this on iPads.

**Comment by benydc** [comment]
I found the fix for this already, it's in the plugin CameraPreview.m and because of cordova latest version. 
I did fork and then made a pull request.

**Comment by westonganger** [comment]
Fixed in master thanks to @benydc PR
