### ISSUE TITLE
Does the flashlight work (Android 6.0) on the 'westonganger fork'?

### ISSUE THREAD

**Issue by dnmd** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#154]
In the [fork from westonganger](https://github.com/westonganger/cordova-plugin-camera-preview) I noticed the `CameraPreview.setFlashMode()` can be set to either `'OFF', 'ON' and 'AUTO'`, did anyone manage to get it working? I assume with the new permissions on Android 6, some additional modifications need to be made...(?)

**Comment by erperejildo** [comment]
Try updating from master and adding this:
`cordova.plugins.camerapreview.setFlashMode(3);`

**Comment by westonganger** [comment]
Flash is now implemented for Android in master.
