### ISSUE TITLE
app crashes due android 6 permissions

### ISSUE THREAD

**Issue by diego-cortez** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#156]
Android app crashes when trying to take a picture.

I believe this is an android 6 issue related, as the developer should ask the user for permissions in real time. I know this repo is not maintained anymore, as well ' westonganger' fork, but.. does anybody found a solution to this? 

I think there is no other plugin that allows interaction between html-camera.

Any help would be great at this time, thanks in advance.

**Comment by danielECP** [comment]
A possible work-around is to implement the following plugin: https://github.com/dpa99c/cordova-diagnostic-plugin
Then in your platform ready method, call `Diagnostic.requestCameraAuthorization()`. 
It will prompt the user for your app to have access to the Camera on first load, and shouldn't cause a crash by the time it loads the camera-preview plugin.

**Comment by diego-cortez** [comment]
Hi @danielECP, 
Yes that's exactly what I did and works very good, anyway, I think this repo must be updated to fix issues like pixelated images / autofocus in android and other details, hope some native developers works on this great plugin, thank you for sharing your solution, I appreciate it. cheers.

**Comment by westonganger** [comment]
This is now fixed in master.
