### ISSUE TITLE
Activity in repository

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#158]
A few months ago I created another repository, which was a copy of this one with a few improvements added (but the only one that I have tested is the auto-focus) by @julitroalves here:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/104

I'm watching too many bug reports these days but no one is updating the repository with all of these fixes, so I'd like to invite you to use my repository instead, at least till this one have more activity from the owners (at that point we could merge the original one with mine anyway):
https://github.com/erperejildo/cordova-plugin-preview-camera
https://www.npmjs.com/package/cordova-plugin-preview-camera

I have no knowledge (no Java experience) or time to fix them but if someone do a pull request I'll be happy to test and merge it ASAP.
I'm going to deploy this month an app which is using this plugin so I'll test it in different devices to be sure is working perfectly (just Android for now).

If you have any recommendation or comment just let me know here and use the other repository to report the issues:
https://github.com/erperejildo/cordova-plugin-preview-camera/issues

Cheers!

**Comment by westonganger** [comment]
Hey guys I have updated the readme with the projects status. I added yours as one of the recommended forks.

We are still accepting PR's however there doesn't seem to be much of that happening.

I would like to encourage the community to create PR's that bring these fixes and enhancements from the forks back to this repo to get a good new version released.

**Comment by erperejildo** [comment]
Great @westonganger!

I forked it and updated with my changes. I just created a PR:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/159

Not sure if I had to merge with master or with skanygin. This last one looks older anyway.

**Comment by erperejildo** [comment]
@westonganger can you update the npm package as well?

**Comment by diego-cortez** [comment]
@erperejildo, @westonganger 

Hi guys, glad to see you still have interest in maintain this repo, our team is about to deploy an ios/android app to production next March, now I am currently using @westonganger fork because the clean api but I am interested in implement @erperejildo fork to take advantage of android autofocus. I am wondering if anything (PR's) goes to the main repo (this) I would prefer to fork this one so it can be more maintainable.
Also I am about to report a new issue (in both forks) that I just found in iOS with .stopCamera() method, I just need more testing before I do it.

Hope to see those PR's merged into the main repo soon.

Thank you guys, our team appreciate the effort invested on this nice plugin.

**Comment by westonganger** [comment]
Hopefully I can merge mine in here sometime today. 

Afterwards it will require some testing time and any fixes before releasing a new version.

**Comment by erperejildo** [comment]
Cool.

In order to test it, can we do it from the repository? At least me I have to remove/install the npm package in my app

**Comment by westonganger** [comment]
While testing master you should use the git source in your package.json

"cordova-plugin-camera-preview": "github:cordova-plugin-camera-preview/cordova-plugin-camera-preview"

**Comment by erperejildo** [comment]
@diego-cortez you can create PRs to master.
To report issues just use this one.

What we also can do is remove skanygin if it's not longer necessary or complex to be merged and create a develop one for further PRs

**Comment by westonganger** [comment]
I've merged in the most important forks now. The rest is just bug fixing and enhancing, finally.
