### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#161]
Following this instructions the camera doesn't start:
```
var tapEnabled = true; //enable tap take picture
var dragEnabled = true; //enable preview box drag across the screen
var toBack = true; //send preview box to the back of the webview
var rect = {x: 0, y: 100, width: 200, height:200};
cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack)
```

I have to remove the last parameter to fix it, otherwise I get this warning (but no problem, just empty canvas):

> The key "target-densitydpi" is not supported.

I think this fix could fix as well this issue:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/129

**Comment by westonganger** [comment]
Updated documentation.
