### ISSUE TITLE
Size Error 

### ISSUE THREAD

**Issue by HartHerbert** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#164]
Using your plugin I noticed there is a error with the preview-size.

See the following image.

![screenshot_20170207-112750](https://cloud.githubusercontent.com/assets/22191877/22687678/621fd4d2-ed29-11e6-86ed-2868cfcdee40.png)

This screenshot was taken with my Samsung Galaxy S6 Edge. On my Samsung Galaxy Alpha it works fine.

- Samsung Galaxy S6 Edge Display Resolution **2560 x 1440 Pixel (576 PPI)**
- Samsung Galaxy Alpha  Display Resolution **1280 x 720 Pixel (312 PPI)**

I could not find the error in your code, so that's why I am asking you to add the feature to support larger image sizes.

the plugin from [techieyann](https://github.com/techieyann/CordovaCameraPreview) displays the preview-size right on my S6 Edge.

Thanks

**Comment by erperejildo** [comment]
Which branch are you using in that repo?

**Comment by HartHerbert** [comment]
I am using the master of [that repo](https://github.com/erperejildo/cordova-plugin-preview-camera)

**Comment by erperejildo** [comment]
Sorry, I meant which repo in techieyann is working for you. I'll merge it with this one

**Comment by HartHerbert** [comment]
I was working with the master repo. The only thing that wasn't working on techieyan's master was the autofocus.

**Comment by erperejildo** [comment]
I'm have a look later on.

Also to this file located in the other branch which looks newer:
https://github.com/techieyann/CordovaCameraPreview/blob/cameraSwitch/src/ios/CameraPreview.m

**Comment by erperejildo** [comment]
Can you try again @HartHerbert ?

**Comment by HartHerbert** [comment]
did you fix it?

**Comment by HartHerbert** [comment]
Guys, looks like your merge didn't work as espected. I cant build the project anymore because this errors get thrown:

```
C:\Development\Fctop\platforms\android\src\com\cordovaplugincamerapreview\CustomSurfaceView.java:7: error: duplicate class: com.cordovaplugincamerapreview.CustomSurfaceView

class CustomSurfaceView extends SurfaceView implements SurfaceHolder.Callback{
^

C:\Development\Fctop\platforms\android\src\com\cordovaplugincamerapreview\Preview.java:21: error: duplicate class: com.cordovaplugincamerapreview.Preview

class Preview extends RelativeLayout implements SurfaceHolder.Callback {
^
C:\Development\Fctop\platforms\android\src\com\cordovaplugincamerapreview\TapGestureDetector.java:6: error: duplicate class: com.cordovaplugincamerapreview.TapGestureDetector
class TapGestureDetector extends GestureDetector.SimpleOnGestureListener{
^

C:\Development\Fctop\platforms\android\src\com\cordovaplugincamerapreview\CameraActivity.java:419: error: cannot find symbol

          eventListener.onPictureTaken(originalPictureFile.getAbsolutePath(), picFile.getAbsolutePath());
                                                                              ^
  symbol: variable picFile
```

I am using the ```master``` of this repo

**Comment by erperejildo** [comment]
I'll try tonight or tomorrow pushing a temporary version to npm. Otherwise I can't try on my Meteor app.

**Comment by HartHerbert** [comment]
Yeah thx it would be great if you would do this asap

**Comment by westonganger** [comment]
I fixed the merge issues and it now builds successfully.

**Comment by westonganger** [comment]
I dont want to release a new version to npm until we iron out the initial kinks of this merging. But once its been tested we will surely do that.

**Comment by erperejildo** [comment]
@westonganger doesn't matter, I found another way to install the package in Meteor from Github (updated README).
I tried new version and it works perfectly (at least for me)

@HartHerbert check it out if you can.
And also one question. I saw that you've got your first icon above preview. Can you have a look to this other issue as well? https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/129 Can't figure out what I need to do

**Comment by erperejildo** [comment]
@HartHerbert I created this spritesheet for testing purposes:
https://docs.google.com/spreadsheets/d/1plw7ybr6kWyendpA5DvkJVju2bw9XFZrTGeKG906hyw/edit#gid=0
Would you main to add your devices?

**Comment by HartHerbert** [comment]
it works now, thx guys.
