### ISSUE TITLE
Flash on iOS?

### ISSUE THREAD

**Issue by CharlieCamp98** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#167]
cordova.plugins.camerapreview.setFlashMode() does not seem to work on iOS 10.2.

How can I go about resolving this? Flash is a must for my app.

**Comment by CharlieCamp98** [comment]
Anyone?

**Comment by westonganger** [comment]
I am fairly sure it still needs to be implemented for iOS. Why don't you implement this and then create a PR.

**Comment by erperejildo** [comment]
As @westonganger said this was and improvement just for Android so it's not an actual issue on IOS.
If you need some help to fork the repository and create some PRs just let us know to help you

**Comment by westonganger** [comment]
I am reopening this issue as ios and android should have the same feature set or very close anyways. I want to see this implemented for ios too.

**Comment by erperejildo** [comment]
Is too complex to translate the Android code to IOS? 
Not only for the flash, also for zoom and autofocus

**Comment by CharlieCamp98** [comment]
I'm not sure. I just simply use this plugin without modifying it as I'm not a native developer.

We should consider updating the README.md file, considering that not many people (including myself) have any idea as to what features were merged from other PRs etc. Good documentation is crucial.

**Comment by westonganger** [comment]
Yes every PR should be coming with documentation updates as required.

**Comment by erperejildo** [comment]
Updated README

**Comment by CharlieCamp98** [comment]
This repository successfully added Flash on iOS (but has issues with flipping images).

Perhaps someone could use this source code as inspiration and commit a PR here to add flash to iOS?

https://github.com/clariontools/CordovaCameraPreview

**Comment by westonganger** [comment]
Why dont you try yourself? I don't think many Cordova developers do native, including myself.

**Comment by CharlieCamp98** [comment]
@westonganger I'll take a look and see what I can do

**Comment by CharlieCamp98** [comment]
Sorry for not getting around to this yet -- I'm currently working full time on two projects.

I'll take a look within a few days -- but no promises if I'll be able to do anything. I've never developed Cordova plugins before.

**Comment by westonganger** [comment]
I was looking in the code today and I saw that flashMode was in ios as well it was just broken and documentation was poor it was forgotten about.

Anyways flash should now re-hooked up in ios, currently it only does not support the `torch` option, that would require additional implementation.

**Comment by jlongman** [comment]
Looking at this - I'm seeing that the flash state is being set before the camera is changed to the back camera - and of course the front camera has no flash. This results in the flash being on, despite being set to off.



```
2017-03-07 12:12:04.044696 FD Snow[8065:1362537] setOnPictureTakenHandler
2017-03-07 12:12:04.046899 FD Snow[8065:1362537] getSupportedPictureSizes
2017-03-07 12:12:04.191446 FD Snow[8065:1362676] Starting session
2017-03-07 12:12:04.216077 FD Snow[8065:1362537] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-03-07 12:12:04.221042 FD Snow[8065:1362537] [MC] Reading from public effective user settings.
2017-03-07 12:12:04.224350 FD Snow[8065:1362537] THREAD WARNING: ['CameraPreview'] took '176.384033' ms. Plugin should use a background thread.
2017-03-07 12:12:04.225546 FD Snow[8065:1362537] Flash Mode
2017-03-07 12:12:04.225646 FD Snow[8065:1362537] This device has no flash
2017-03-07 12:12:04.225811 FD Snow[8065:1362537] hideCamera
2017-03-07 12:12:04.227587 FD Snow[8065:1362676] defaultCamera: back
```

The code which calls this is: 

```
                CameraPreview.setOnPictureTakenHandler(function (base64PictureData) {
                //..
                });
                CameraPreview.startCamera({
                    x: 0,
                    y: 40,
                    width: 300,
                    height: 200,
                    camera: "back",
                    tapPhoto: true,
                    previewDrag: false,
                    toBack: false,
                    alpha: 1
                });
                CameraPreview.setFlashMode("off");
                CameraPreview.hide();
```

One would think the `startCamera` call would set the camera to `back` before the flash was set, but clearly this doesn't happen.  I wonder if the flash state should be moved up and into `CameraPreview` and then applied each time the camera is switched, front to back.

**Comment by westonganger** [comment]
This is in master. Closing

**Comment by ragcsalo** [comment]
Can't disable flash on iOS :-(
