### ISSUE TITLE
Switch camera not working file!! help

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#168]
cordova.plugins.camerapreview.switchCamera();
It stuck some time, when i switch the camera Preview stop and nothing happen, it stop camera when click on switch.

**Comment by HartHerbert** [comment]
yeah that happend to me at the beginning too.
just do this:

`switchCamera(){
    cordova.plugins.camerapreview..stopCamera();
    cordova.plugins.camerapreview..switchCamera();
   
    this.startCameraPreview();

  }`

**Comment by aliwaqassi** [comment]
Thanks Bro it works, :)

**Comment by aliwaqassi** [comment]
There is also one issue renaming, when camera is start and then i lock my phone then i unload the camera is crashed , did this happen with you?

**Comment by HartHerbert** [comment]
yeah this happens to me too but I didn't start to solve it. maybe just listen to a event when the dsvice unlock then restart the camera like you did when you switched the camera

**Comment by aliwaqassi** [comment]
But this is not a proper way, well i put an other for crashed app, thanks bro

**Comment by HartHerbert** [comment]
ok good but please close this issue here

**Comment by CharlieCamp98** [comment]
Could you please specify the device and OS version in which this error is occurring so there is a potential for the community to recreate this bug?
