### ISSUE TITLE
app crashed! help

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#169]
When CameraPreview start correctly then i lock my phone and then unlock the camera app is crashed why??

**Comment by CharlieCamp98** [comment]
On iOS 10 you may be having issues with camera permissions. You must specify usage descriptions for some plugins in your **.plist** file via XCode or some other means.

Check out [this plugin](https://www.npmjs.com/package/cordova-plugin-ios-camera-permissions) to alleviate these issues.
