### ISSUE TITLE
dynamic width height issue on takePicture.

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#170]
var width  = $(window).width();
 var height = $(window).height();
cordova.plugins.camerapreview.takePicture({maxWidth:width, maxHeight:height});
When i do this, the camera preview app has stopped why?

**Comment by erperejildo** [comment]
Android or IOS?
Can you share also your startCamera()?

**Comment by erperejildo** [comment]
That's the correct way to initialise it. 
Not sure on IOS, but that's the code that I have on Android and it works. Could you do the simplest scenario posible and be sure that $(window).height() is a real value? Maybe this loads before jQuery.
Try with `window.innerHeight`, jQuery is not necessary to get those sizes

**Comment by CharlieCamp98** [comment]
The following would work as well:
`
var width = window.screen.width;
var height = window.screen.height;
`

**Comment by erperejildo** [comment]
If you have problem with these I'll reopen this
