### ISSUE TITLE
toBack argument doesn't work on Android

### ISSUE THREAD

**Issue by thesciz** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#177]
Hey folks,

I'm trying to use the toBack argument, but it always puts the preview on top of my webview.

`cordova.plugins.camerapreview.startCamera({x: 0, y: 0, width: window.innerWidth, height: 570, camera: "front", tapPhoto: true, previewDrag: false, toBack: true});`

It works fine other than that. Any advice?

**Comment by HartHerbert** [comment]
really? 😂 
you forgot to close the bracket after you height property because its one object ({x, y, width, height}, camera, tap, drag, toBack) 

It's this error because the plugin works just fine for me and I'm also using the toBack=true.

**Comment by thesciz** [comment]
Hah, well, it was the code they have on the main page, so I guess they have some typos :P

**Comment by HartHerbert** [comment]
yeah I guess. 
so if it's working now, close this issue.
