### ISSUE TITLE
Preview streched at first load

### ISSUE THREAD

**Issue by Sorikairo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#178]
I'm using the plugin into Ionic 2 as following for a full screen preview for AR stuff : 

` let options = {x: 0, y: 0, width: this.platform.width() ,height: this.platform.height()};
      CameraPreview.startCamera(options, "back", false, false, true, 1);`

But whenever I start my app on my mobile with the apk, the preview is streched however I position my phone.
If I lock my phone and unlock it, it relaunch the camera and it's back to normal.

**Comment by flogr** [comment]
I got the same problem, on Android 6.0.1. I'm using

{x: 0, y: 0, width: screen.width, height: screen.height}

As soon as i lock and unlock my phone, preview isnt stretched any more.

**Comment by erperejildo** [comment]
Please, try with new version (not the one on npm)

**Comment by flogr** [comment]
Thanks for your fast response @erperejildo , but how do i install the new version if not with "ionic plugin add cordova-plugin-camera-preview", which uses npm (i'm also using ionic)?

**Comment by erperejildo** [comment]
Hmm, not sure about that, but should be similar to Meteor:
Installing from npm:
`meteor add cordova:cordova-plugin-camera-preview@X.X.X`
Installing one specific commit from github:
`meteor add cordova:cordova-plugin-camera-preview@https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git#[commit_id]`

Try replacing with the Ionic commands

**Comment by flogr** [comment]
Unfortunately, if i match your meteor command to ionic, it still retrieves the plugin from npm...

I run:
ionic plugin add cordova-plugin-camera-preview@https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git#44e00af8bdf7c710af8ed0a5b77eaccc31590ff8

And get:
Fetching plugin "cordova-plugin-camera-preview@https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git" via npm
...

It's not that much of a hurry for me, as soon as this fix will be released on npm to anytime soon!?

**Comment by erperejildo** [comment]
You also could try updating this repository to your own npm (I did once) but I'm pretty sure that this should be possible from Ionic.
http://stackoverflow.com/questions/25140383/adding-plugins-from-specific-revision-github-project-to-the-cordova-project
Unfortunately with need to test this in order to know that we have a stable version for npm.

I'll close this issue. Feel free to reopen if you still having problems with new version

**Comment by flogr** [comment]
Ah, great. I had to remove the plugin before and then reinstall it with

cordova plugin add cordova-plugin-camera-preview@https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git#44e00af8bdf7c710af8ed0a5b77eaccc31590ff8

Now i have the latest version installed and the stretching error seems to be fixed!
Thanks a lot!

**Comment by erperejildo** [comment]
Great!

Either Meteor or Ionic use Cordova and the commands at the end are quite similar.

**Comment by Sorikairo** [comment]
Hi there,

I don't know how to re-open the issue so, let's hope you'll get this.

It sadly still doesn't work as expected, the view is still streched, despite the fact that I removed the plugin, and installed it back with 

cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-
plugin-camera-preview.git

Let me know whatever information you need to be able to handle this.
