### ISSUE TITLE
Error compiling on iOS

### ISSUE THREAD

**Issue by fastcodeUBB** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#180]
Hi!

When compiling in iOS with the latest version of the plugin
Show me the following

`CameraSessionManager.m:21:56: No known class method for selector 'deviceWithMediaType:preferringPosition:'`

`CameraSessionManager.m:65:60: No known class method for selector 'deviceWithMediaType:preferringPosition:'`

How can you solve?

**Comment by fastcodeUBB** [comment]
Make this change, based on the previous version

`AVCaptureDevice * videoDevice = [self cameraWithPosition: self.defaultCamera];`

And now compiles, is it correct?

**Comment by erperejildo** [comment]
If it's working for you it should be correct. Can you try in another IOS version (trying two ways) and make a PR?

**Comment by ander2** [comment]
Hit this problem just now. @fastcodeUBB solution's solves the problem.

**Comment by BBosman** [comment]
Hitting the same issue. @fastcodeUBB where do I need to make that change?

**Comment by fastcodeUBB** [comment]
@BBosman in line 21 and 65 and of `CameraSessionManager.m`

`
  AVCaptureDevice *videoDevice = [self cameraWithPosition:self.defaultCamera]; //line 21
`

and 

`
      AVCaptureDevice *videoDevice = [self cameraWithPosition:self.defaultCamera];  //line 65
`

`CameraSessionManager.m` lo encuentras en la carpeta plugins de tu proyecto xcode

**Comment by BBosman** [comment]
@fastcodeUBB Thank you!

**Comment by erperejildo** [comment]
@fastcodeUBB would you like to make a PR with your change?

**Comment by fastcodeUBB** [comment]
@erperejildo yes, I would like it

**Comment by westonganger** [comment]
No.  Do you want to create a pr or should I just update it now?

**Comment by fastcodeUBB** [comment]
What you find easier

**Comment by westonganger** [comment]
I was in bed on my phone so was hoping for a PR. However this fix is now in master. 

Thank you for providing the solution. Closing.
