### ISSUE TITLE
does takePicture() store an image on an android device?

### ISSUE THREAD

**Issue by flogr** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#181]
I'm struggling with getting the image data of taken preview pictures.

I take pictures this way:

```
$scope.takePicture = function () {
                        cordova.plugins.camerapreview.takePicture();
                    }
```

Everything works, the setOnPicuterTakenHandler callback is called, implemented like this:

```
cordova.plugins.camerapreview.setOnPictureTakenHandler(function (picture) {
alert(picture);
});
```

The value in "picture" is a path to an actual image, but i can't find it on my testing device.
Also, the return value specified in the example preview in https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app/blob/master/www/js/index.js is an array with 2 entries.

Now my actual question:
What do i have to do to save the image taken on "takePicture" in a customized directory in my app?

I'm testing on an Android 6.0.1 device, building my app with ionic.

**Comment by Et3rnal** [comment]
I have the exact same question. Did you happen to find what's wrong? and how to set where to save it?

**Comment by Et3rnal** [comment]
Okay, so the plugin "by default" doesn't save the image to the device. If you want to save it you have to write the base64 to file.

There is a plugin does that but it has been discontinued so ill post the js script I used and its working fine till now:

`
	CameraPreview.setOnPictureTakenHandler(function(picture) {
	  //document.getElementById('originalPicture').src = picture; // base64 picture;
	  document.getElementById('originalPicture').style.backgroundImage = "url('"+picture+"')"; // base64 picture;
	  
	    // convert the image to base64
        resolveLocalFileSystemURL('file:///'+picture, function(fileEntry) {
          fileEntry.file(function(file) {
            var reader = new FileReader();
            reader.onload = function(event) {
             // this would be your image
              base64 = event.target.result; //Here is your base64 string
              // in this part I stop the loader spinner which I started to load in takePicture()

			  /** Process the type1 base64 string **/
			var myBaseString = base64;

			// Split the base64 string in data and contentType
			var block = myBaseString.split(";");
			// Get the content type
			var dataType = block[0].split(":")[1];// In this case "image/png"
			// get the real base64 content of the file
			var realData = block[1].split(",")[1];// In this case "iVBORw0KGg...."

			//alert(dataType);

			// The path where the file will be created
			var folderpath = "file:///storage/emulated/0";
			
			//timestamp from image name
			var d = new Date();
			var n = d.getTime(); 
			
			// The name of your file, note that you need to know if is .png,.jpeg etc
			var filename = "image-"+n+".jpeg";

			savebase64AsImageFile(folderpath,filename,realData,dataType);
			  
			  
            };
            reader.readAsDataURL(file);
			
          });
        });
        //this.stopCamera();	  
	  
	});

/**
 * Convert a base64 string in a Blob according to the data and contentType.
 * 
 * @param b64Data {String} Pure base64 string without contentType
 * @param contentType {String} the content type of the file i.e (image/jpeg - image/png - text/plain)
 * @param sliceSize {Int} SliceSize to process the byteCharacters
 * @see http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript
 * @return Blob
 */
function b64toBlob(b64Data, contentType, sliceSize) {
        contentType = contentType || '';
        sliceSize = sliceSize || 512;

        var byteCharacters = atob(b64Data);
        var byteArrays = [];

        for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
            var slice = byteCharacters.slice(offset, offset + sliceSize);

            var byteNumbers = new Array(slice.length);
            for (var i = 0; i < slice.length; i++) {
                byteNumbers[i] = slice.charCodeAt(i);
            }

            var byteArray = new Uint8Array(byteNumbers);

            byteArrays.push(byteArray);
        }

      var blob = new Blob(byteArrays, {type: contentType});
      return blob;
}

/**
 * Create a Image file according to its database64 content only.
 * 
 * @param folderpath {String} The folder where the file will be created
 * @param filename {String} The name of the file that will be created
 * @param content {Base64 String} Important : The content can't contain the following string (data:image/png[or any other format];base64,). Only the base64 string is expected.
 */
function savebase64AsImageFile(folderpath,filename,content,contentType){
    // Convert the base64 string in a Blob
    var DataBlob = b64toBlob(content,contentType);
    
    console.log("Starting to write the file :3");
    
    window.resolveLocalFileSystemURL(folderpath, function(dir) {
        console.log("Access to the directory granted succesfully");
		dir.getFile(filename, {create:true}, function(file) {
            console.log("File created succesfully.");
            file.createWriter(function(fileWriter) {
                console.log("Writing content to file");
                fileWriter.write(DataBlob);
            }, function(){
                alert('Unable to save file in path '+ folderpath);
            });
		});
    });
}
`

Can't find where I got the functions from.

**Comment by westonganger** [comment]
For a while it did store the device on image. I have now just update master so it no longer saves to device, it only save image data as base64. You  the developer will be responsible with what you want to do with your base64 image data.
