### ISSUE TITLE
takePicture sizes

### ISSUE THREAD

**Issue by erperejildo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#182]
I have taken 2 different pictures: one with 150px has maximum sizes and another one without sizes. Both look the same and have same size:
![screenshot_2017-02-15-23-14-03-254_com drodriguez recipic](https://cloud.githubusercontent.com/assets/5629919/22999811/54e9e660-f3d5-11e6-809e-d26adf4c2da0.png)
![screenshot_2017-02-15-23-12-58-703_com drodriguez recipic](https://cloud.githubusercontent.com/assets/5629919/22999771/1e798f54-f3d5-11e6-8c0d-42f8e65aa7d7.png)
Not sure if we had this issue in previous version or if I'm doing something wrong

**Comment by Cale-Rubeus** [comment]
Same issue with me

**Comment by Et3rnal** [comment]
im not getting higher resolution as well no matter what I have in takepicture

**Comment by erperejildo** [comment]
That's a different one @Et3rnal

**Comment by Et3rnal** [comment]
@erperejildo So how to get the highest resolution image? changing the takePicture doing no differences. is there another build I should use? thanks

**Comment by erperejildo** [comment]
I think the highest resolution is not expecting anything so it takes the native resolution

**Comment by Et3rnal** [comment]
I don't think I got you.
Is this a bug? or am doing something wrong? how can I set the taken image resolution? if this plugin was built on top of the Cordova one can we use the same codes they have to configure it ?

**Comment by erperejildo** [comment]
What I wanted to mean is in takePicture function don't specify any sizes so it will take the native resolution

**Comment by Et3rnal** [comment]
Okay, I see, because I read that somewhere in here.
So what is the right way to get higher resolutions image?

**Comment by erperejildo** [comment]
Again, don't specify any size on takePicture

**Comment by Et3rnal** [comment]
im not, what im getting around 1000px only! my normal camera takes 5000px images?

**Comment by westonganger** [comment]
I have made some updates in master. Please let me know if the latest updates fix your issue.

**Comment by Et3rnal** [comment]
I had quick fix to make my code works with the new changes but I can confirm I still can't get pass 1080x1920

passing arguments or not make no difference
`CameraPreview.takePicture({Width: 5312, Height: 2988, quality: 100});`

Maybe someone can update the sample app to use the new changes and we use it test?

**Comment by westonganger** [comment]
I have now updated the sample app this morning. From now on we should be using this sample app for testing and debugging to eliminate app specific errors being logged as issues.

I did some minor testing on the sample app with android and a few things seemed broken so we will have to iron out all the bugs but were getting there.

We need all the help we can get for testing and debugging this plugin.

**Comment by Et3rnal** [comment]
Okay so I have tried the app and as you said many things don't work but, I haven't use GitHub for ages so I'll just go through what I did to get it to work out:

> **on index.css:**
> just add ../ to the background location to become: background-image: url('../img/background.png');

> **on index.js:**
> startCamera doesn't open the camera at the back so I added {camera: "back", tapPhoto: true, toBack: true}) to become:
> CameraPreview.startCamera({camera: "back", tapPhoto: true, toBack: true});

> takePicture function returns width unidentified so I just removed the attributes or maybe we can use
> var width = (window.innerWidth > 0) ? window.innerWidth : screen.width; if this is the value we looking work as that code works fine.

Effects, flash and zoom didn't work "I haven't tested them before as have no use for them atm"

showSupportedSize doesn't work, I tried to fix it be I still get no values back on both types!

I have this function to return the taken image size and still can't get pass 1080x1920
  
```
  getimagesize: function(){
	console.log('getimagesize fired');
	
	var img = document.getElementById('originalPicture'); 
	//or however you get a handle to the IMG
	var width = img.naturalWidth;
	var height = img.naturalHeight;
	console.log("Image Size\n\nWidth: " + width + "\nHeight: " + height);
  },
```

Can't remember what else I have done to fix it. I'll try to make a fork with all the changes when I can.

**Comment by westonganger** [comment]
Okay I added a few of your fixes and more to the sample app repo.

Question is image size issue happening on Android, iOS or both?

**Comment by westonganger** [comment]
After digging through the code I think your using Android. 

It was ignoring the width and height passed in. This has now been fixed. Please try again using master.

**Comment by Et3rnal** [comment]
Your changes to Preview.java broke it

> 
> Error: cmd: Command failed with exit code 1 Error output:
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> F:\EasyPHP-12.1\www\cordova-build\camera-preview\platforms\android\src\com\cordovaplugincamerapreview\Preview.java:301: error: incompatible types: possible lossy conversion from double to int
> YuvImage yuvImage = new YuvImage(data, format, width, height, null);
> ^
> F:\EasyPHP-12.1\www\cordova-build\camera-preview\platforms\android\src\com\cordovaplugincamerapreview\Preview.java:303: error: incompatible types: possible lossy conversion from double to int
> Rect rect = new Rect(0, 0, width, height);
> ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
> 2 errors
> 
> FAILURE: Build failed with an exception.

But, before these changes I noticed that **device.platform** been used and this requires "cordova plugin add cordova-plugin-device" to work.

After adding the showSupportedSize become functional and I was able to get images with 1088x1088 but as you said it ignored my input.

Also testing everything seems to work except for the flash!, the only time I get an error is when choosing "Touch" mode but I was not able to test the fix and I have no idea why the code never changes on my device!

on CameraPreview.js:88
change
` }else if(flashMode === 'torch' && window.device.platform() === 'Android'){`
to
` }else if(flashMode === 'torch' && window.device.platform === 'Android'){`

ps: as you applied all the changes I have nothing on my repo other than an updated readme for now.

**Comment by westonganger** [comment]
`window.device` comes from another plugin. I was mistaken in adding this here. I have now added a different method that doesn't require additional plugins. I just fixed this is master. 

As for the compile issues I am just waiting to hear back from @anneb on his PR #207 .

**Comment by Et3rnal** [comment]
I managed to fix it last night but passing any value over 1088x1088 will result in green image or crash the app!. Will try the last updates soon.

**Comment by westonganger** [comment]
PR #209 addresses this issue. It still requires a bit of work before we merge it.

**Comment by westonganger** [comment]
Alright we have addressed PR #209. I just updated the documentation surrounding takePicture. Please try master again.

**Comment by Et3rnal** [comment]
Awesome I bearly read it. ill get back to you once I finish testing.

**Comment by Et3rnal** [comment]
It was crashing, stopping the preview before taking the image was the reason.
However the app ignores the values passes through CameraPreview.takePicture();

But we can now have full res images 💃  thanks

**Comment by westonganger** [comment]
takePicture now returns full res images.
