### ISSUE TITLE
switchCamera erro Fail to connect to camera service - Android 5.1

### ISSUE THREAD

**Issue by Cale-Rubeus** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#184]
Always i execute the method switchCamera i receive the following error : 'Fail to connect to camera service', only works on Android 7.0 or above

**Comment by aliwaqassi** [comment]
this error comes in IOS only?
can you provide your switchCamera() method how you are using?

**Comment by Cale-Rubeus** [comment]
Comes in Android too, the method is simple,
var cam = CameraPreview;
cam.switchCamera();

**Comment by aliwaqassi** [comment]
i did this for android create click event with your logic
    /*
    Start front camera
    */
    frontCamera:function()
    {
        cordova.plugins.camerapreview.stopCamera();
        cordova.plugins.camerapreview.switchCamera();
        var width  = $(window).width();
        var height = $(window).height();
        var tapEnabled = false; //enable tap take picture
        var dragEnabled = false; //enable preview box drag across the screen
        var toBack = true; //send preview box to the back of the webview
        var rect = {x: 0, y: 0, width:width, height:height};
        cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack);
        cordova.plugins.camerapreview.setZoom(100);
    },
    /*
    Start back camera
    */
    backCamera:function()
    {
        cordova.plugins.camerapreview.stopCamera();
        cordova.plugins.camerapreview.switchCamera();
        var width  = $(window).width();
        var height = $(window).height();
        var tapEnabled = false; //enable tap take picture
        var dragEnabled = false; //enable preview box drag across the screen
        var toBack = true; //send preview box to the back of the webview
        var rect = {x: 0, y: 0, width:width, height:height};
        cordova.plugins.camerapreview.startCamera(rect, "back", tapEnabled, dragEnabled, toBack);
        cordova.plugins.camerapreview.setZoom(100);
    },

**Comment by aliwaqassi** [comment]
`    /*
    Start front camera
    */
    frontCamera:function()
    {
        cordova.plugins.camerapreview.stopCamera();
        cordova.plugins.camerapreview.switchCamera();
        var width  = $(window).width();
        var height = $(window).height();
        var tapEnabled = false; //enable tap take picture
        var dragEnabled = false; //enable preview box drag across the screen
        var toBack = true; //send preview box to the back of the webview
        var rect = {x: 0, y: 0, width:width, height:height};
        cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack);
        cordova.plugins.camerapreview.setZoom(100);
    },
    /*
    Start back camera
    */
    backCamera:function()
    {
        cordova.plugins.camerapreview.stopCamera();
        cordova.plugins.camerapreview.switchCamera();
        var width  = $(window).width();
        var height = $(window).height();
        var tapEnabled = false; //enable tap take picture
        var dragEnabled = false; //enable preview box drag across the screen
        var toBack = true; //send preview box to the back of the webview
        var rect = {x: 0, y: 0, width:width, height:height};
        cordova.plugins.camerapreview.startCamera(rect, "back", tapEnabled, dragEnabled, toBack);
        cordova.plugins.camerapreview.setZoom(100);
    },`

**Comment by Cale-Rubeus** [comment]
I did like you, but this is a wrong way

**Comment by westonganger** [comment]
Please use master and follow the instructions in the readme, please re-read. Closing.
