### ISSUE TITLE
Orientation not saved

### ISSUE THREAD

**Issue by fizdalf** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#190]
I've been banging my head against the wall with this plugin, in IOS, I cannot get the pictures to show with the correct orientation, I'm using a plugin to lock phone orientation to 'landscape' prior to calling cameraStart, then I'm taking a picture, and I'm getting a portrait picture every time, I have had this problem before, but I could extract the EXIF and correct the orientation from it, but with this plugin I'm not getting any EXIF data to work with..so how do I fix the orientation of the photo?

If required I can provide screen shots and example pictures

**Comment by benydc** [comment]
do you have the toBack set to true?

**Comment by fizdalf** [comment]
No, it's on false, I want the camera to be shown above my html.

**Comment by h-morales** [comment]
I am also experiencing this issue on iOS but with toBack set to true and camera set to FRONT.
The Base64 output image has wrong orientation on Portrait mode, Reverse Portrait Mode, and Reverse Landscape but correct output for Landscape mode. I also noticed when debugging on XCode, the orientation was always OrientationUp.

**Comment by h-morales** [comment]
I was able to fix the base64 wrong orientation output with the following changes to the function radiansFromUiImageOrientation:

`(double)radiansFromUIImageOrientation:(UIImageOrientation)orientation
{
double radians;

  switch ([[UIApplication sharedApplication] statusBarOrientation]) {
    case UIDeviceOrientationPortrait:
      radians = M_PI_2;
      break;
        case UIDeviceOrientationLandscapeLeft:
      radians = 0.f;
      break;
case UIDeviceOrientationLandscapeRight:
      radians = M_PI;
      break;
        case UIDeviceOrientationPortraitUpsideDown:
      radians = -M_PI_2;
      break;
  }
  return radians;
}`

**Comment by westonganger** [comment]
This is now fixed in master. Thanks for helping point out the fix in the native code.
