### ISSUE TITLE
Camera-preview only shows after changing orientation when using toBack true - only iOS

### ISSUE THREAD

**Issue by flogr** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#191]
I have a functioning version of your plugin (using the latest version with all forks merged) working on Android 6.0.1, everything is fine.

But on an iPad Air 2 with iOS 10 the camera preview isn't showing on startup of the app, it only shows after i change orientation of my iPad from portrait to landscape or the other way round.

I execute this code on startup of the app and it gets triggered correctly on both Android and iOS, i debugged that.

var startCam = function () {
                        CameraPreview.startCamera({x: 0, y: 0, width: window.screen.width, height: window.screen.height, camera: "back", tapPhoto: true, previewDrag: false, toBack: true});
                    };

It only seems to happen when using toBack:true, if i set it to false it also works on iOS

window.screen.width and height are both defined and have the same values on Android and iOS, so it seems to be an error in the plugin itself i think.

Please help!

**Comment by benydc** [comment]
same problem here. I think I was able to fix it in dev mode by touching one of the CSS elements from within JS, but in production still same issue. What JS framework are you using?

**Comment by flogr** [comment]
I'm using Ionic v1.

How did you fix this issue with CSS, would be nice if you could give me a few details!

Thx!

**Comment by flogr** [comment]
By the way, just tested it on an Iphone 5c with iOS 10, where this error occurs, too.

**Comment by benydc** [comment]
I got it working! the bug is inside the plugin, since latest cordova there is a function that needs to be run before it lays the html elements.  I also changed the way the CameraRender is inserted in the webView. I'm gone make a pull request for the fix.

**Comment by flogr** [comment]
@benydc that is great news! Let me know when your pull request got merged! Thx!

**Comment by flogr** [comment]
This solved the issue for me, preview now works on all my iOS devices from start.
Thanks a lot to @benydc and @westonganger
