### ISSUE TITLE
CameraPreview now requires file access permission and fills up storage space?

### ISSUE THREAD

**Issue by anneb** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#192]
On Android, the onPictureTakenHandler(picture) now returns a path to a picture file. Some older versions/forks of CameraPreview provided the base64 encoded data instead of a file name. 

How to overcome the following disadvantages of storing pictures in files? 
1. CameraPreview now requires file access permission. Some users may not like that, because they cannot know WHICH files CameraPreview will be accessing?
2. developers using the CameraPreview plugin now need to take care of file cleanup: for every picture taken, a new file seems to be created. After a while this may clog up storage space?

Some use cases where file storage may not be necessary:
- apps that temporarily display pictures only
- apps that upload pictures to remote locations

Could there be an option to choose how to return the picture data? File or base64 data? Would that work on iOS as well?

**Comment by anneb** [comment]
Android hack/fix to replace filename return by by base64 image data:

file CameraActivity.java, method generatePictureFromView

replace
`         final File originalPictureFile = storeImage(originalPicture, "_original");
          eventListener.onPictureTaken(originalPictureFile.getAbsolutePath());
`

by

`         ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
          originalPicture.compress(Bitmap.CompressFormat.JPEG, 85, byteArrayOutputStream);
          byte[] byteArray = byteArrayOutputStream.toByteArray();

          String encodedImage = Base64.encodeToString(byteArray, Base64.NO_WRAP);

          eventListener.onPictureTaken(encodedImage);
`

**Comment by westonganger** [comment]
I think that base64 should be the default and writing to a file shouldn't be an option in this plugin. Writing the file to storage should be the developers responsibility. Then we can probably remove the file permissions.

Everyone, let me know your comments on this matter.

**Comment by anneb** [comment]
Ofcourse, being the creator of this issue, I am in favour of changing (back) to base64 and removing the file side-effect completely, see also related issues #186, #181, #172, #171, #136. However, this will certainly break existing implementations completely (again). This could be made more acceptable if the information on how to deal with the base64 change on the client side is properly documented.

Also, one should be consistent on how the data will be returned on all platforms (issue #136). On older commits/forks, on some platforms meta data in the form of 'data:image/jpeg;base64,' was prepended to the base64 output, and on other platform the developer had to provide this string on the client side. 

The current documenation in README.md is a bit ambiguous about base64/file:
```
CameraPreview.setOnPictureTakenHandler(function(picture) {
  document.getElementById('picture').src = picture; // base64 picture;
});

```

I propose the documentation could be updated to become something like:
```
CameraPreview.setOnPictureTakenHandler(function(base64PictureData) {
  // base64PictureData is base64 encoded jpeg image
  // use this data to store to a file or to upload
  // the image can assigned to an <img> element as follows:
  document.getElementById('picture').src = 'data:image/jpeg;base64,' +base64PictureData;
});

```

**Comment by westonganger** [comment]
I am okay with breaking current functionality, I think file saving is causing a lot of other headaches in this plugin that are outside the scope of this plugin. Yes of course the readme will need proper documentation surrounding this. 

What is the benefit of forcing the developer to prepend the metadata? Could they then save the file as png or something?

**Comment by anneb** [comment]
the metadata is for use in an <img> src only. The base64 data is de actual jpeg image data. Inline data in a browser/dom is required to start with data:mimetype;encoding,'.
If the metadata is prepended by the plugin, then developers need to remove it before streaming it to a file or upload. If metadat is not prepended by the plugin then developers need to prepend it for the case they want to use it as an img src. I think it is cleaner to send the image data as is and let the developer add something if required for their specific purposes.

**Comment by westonganger** [comment]
Thanks for the clear description. I agree then lets keep the metadata out of it and return only base64 data. I would say this is the current top priority issue in the plugin.

I see above you have some code for the Android side. Is it possible you could add the iOS part too and create a PR? If not I will look into this it when I have some time.

**Comment by westonganger** [comment]
This is now implemented in master. , see README for more details. 

* takePicture now only returns base64 data. 
* The plugin no longer required read/write storage permissions..
* takePicture now accepts a quality/compression value
