### ISSUE TITLE
Android: cameraPreview fixes display orientation to portrait for ever?

### ISSUE THREAD

**Issue by anneb** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#193]
After starting the camera, cameraPreview forces a (portrait) orientation and the app stops responding to any orientation changes, even after the camera is stopped/closed.

**Comment by anneb** [comment]
The always PORTRAIT orientation seems to be caused by CameraActivity onCreate:
@Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    **getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);**
  }

**Comment by benydc** [comment]
there is so many issues and outdated code on this plugin...

**Comment by benydc** [comment]
What framework are you using? version of cordova?

**Comment by anneb** [comment]
I am using cordova 6.5.0 and plain HTML/Javacsript
I commented out line:
//getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
and that solved the problem for me.
I was using https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview, branch master, commit 8a9554ff1a4735f93855c7d0a219dbe6480d38c6

**Comment by westonganger** [comment]
This is now fixed in master
