### ISSUE TITLE
Error when trying to compile in Ionic 2

### ISSUE THREAD

**Issue by tordnilsen** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#202]
Hi. 
When I add this plugin to my newly created project it get:

java:301: error: incompatible types: possible lossy conversion from double to int
      YuvImage yuvImage = new YuvImage(data, format, width, height, null);

Any ideas?

regards

**Comment by anneb** [comment]
I have submitted pull request #203 to fix this

**Comment by westonganger** [comment]
Fixed in master
