### ISSUE TITLE
Can't build the project with phonegap builder

### ISSUE THREAD

**Issue by catakkio** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#204]
This is the error /project/src/com/cordovaplugincamerapreview/Preview.java:301: error: incompatible types: possible lossy conversion from double to int
      YuvImage yuvImage = new YuvImage(data, format, width, height, null);
                                                     ^
/project/src/com/cordovaplugincamerapreview/Preview.java:303: error: incompatible types: possible lossy conversion from double to int
      Rect rect = new Rect(0, 0, width, height);
                                 ^
Note: Some input files use or override a deprecated API.

**Comment by diegolamonica** [comment]
Hi @catakkio I've solved casting updating those rows as follows `/project/src/com/cordovaplugincamerapreview/Preview.java` @ row 301:

```
#java
YuvImage yuvImage = new YuvImage(data, format, (int)width, (int)height, null);
```

Same @ row 303:

```
#java
Rect rect = new Rect(0, 0, (int)width, (int)height);
```

**Comment by anneb** [comment]
see also PR #203

**Comment by westonganger** [comment]
Fixed in master
