### ISSUE TITLE
Add option to disable shutter sound

### ISSUE THREAD

**Issue by westonganger** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#214]
Current behaviour in Android and iOS makes a shutter sounds when a photo is taken.

Enhancement is to add `shutterSound: false`  option to disable the sound.

<br>
Some notes for the native side:

The Android Camera API has a method enableShutterSound(boolean) for this. iOS has to be determined

**Comment by aliwaqassi** [comment]
please explain how to use this option and where?

**Comment by westonganger** [comment]
So after researching this I found out a few things. 

1. This is not allowed at all in iOS. 
2. Only available on Android for devices/countries which support it. For example in Japan it is illegal to take a photo without sound for privacy concerns.

Given this information, I think its better to have the shutter sound always enabled as it seems to be best practice at this time.

**Comment by mennii** [comment]
Maybe you can look this document about the Camera.Parameters : https://developer.android.com/reference/android/hardware/Camera.Parameters.html 

there is one tip: Applications can set shutter callback as null to avoid the shutter sound. It is also recommended to set raw picture and post view callbacks to null to avoid the interrupt of preview display.

I tested only on my MI device, and it successfully shut down the shutter sound. but i am  extremely unfamiliar to iOS development, Maybe you give a better resolution.

**Comment by luispimenta** [comment]
@westonganger 

I can not turn off the sound, could you help me?

I tried

`CameraPreview.takePicture({width:640, height:640, quality: 85, shutterSound: false}, function(base64PictureData){
        
 });`

And it did not work. :( 

Help

**Comment by luispimenta** [comment]
This here worked for the android. Now I need to know how to do it on ios.

https://github.com/luispimenta/cordova-plugin-camera-preview/commit/5efd7914e33859b1b903acb9805504120268da53

**Comment by DavidRyu123** [comment]
Awesome @luispimenta ! It works like charm! Hope we can find a way to disable iOS shutter sound too! :)

**Comment by luispimenta** [comment]
@DavidRyu123 But it has, I got it done, see my commit:

https://github.com/luispimenta/cordova-plugin-camera-preview/commit/dcc1edf4fc3769729cca4ff449483ed495c2aa92

Use my repository which is ok on android and ios :)

**Comment by DavidRyu123** [comment]
@luispimenta awesome! Thanks for sharing.

**Comment by DavidRyu123** [comment]
@luispimenta Hi Luis, I have implemented your awesome code in my project. I wonder you are experiencing same issues that I have: 1. Most of time it does not emit the sound (means it's working) but sometimes it emit the shutter sound twice. 2.  The app started radiating heat a bit.

**Comment by luispimenta** [comment]
@DavidRyu123 Hi. I did not realize that. I call the camera only once the camera, so I can not say. About the sound, here it is ok! I'll try to find something.

**Comment by DavidRyu123** [comment]
@luispimenta Thanks. Also, some countries force phone to generate the sound. In those phones, I found that iOS still generate sound in both mute and vibrate mode. Cheers! :)

**Comment by keminjk** [comment]
> This here worked for the android. Now I need to know how to do it on ios.
> 
> [luispimenta@5efd791](https://github.com/luispimenta/cordova-plugin-camera-preview/commit/5efd7914e33859b1b903acb9805504120268da53)

It was working just fine until android 10 comes in.
It just stopped working after I updated my os to the latest one and it started back ringing camera sound while taking pictures.
