### ISSUE TITLE
takePicture result is 'OK'

### ISSUE THREAD

**Issue by my-poi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#216]
Hello,
 
always I get 'OK' as a result of takePicture :-(
 
```
CameraPreview.takePicture({ width: 100, height: 100, quality: 100 }, onSuccess, onError)

function onSuccess (pictureData) {
    alert(pictureData) <<< ‘OK’
    document.getElementById('result').src = 'data:image/jpeg;base64,' + pictureData
}
 
function onError (message) {
    console.debug('Failed because: ' + message)
}
```

Regards,
Maciej

**Comment by westonganger** [comment]
This is because you must use take setOnPictureTakenHandler method, not the onSuccess function.

I think it is time to change the API for this so I am going to change it to that approach sometime today.

**Comment by westonganger** [comment]
setOnPictureTakenHandler has now been removed. For the new instructions see readme for takePicture.

**Comment by my-poi** [comment]
Thanks!
