### ISSUE TITLE
cannot find symbol   private CameraPreviewListener eventListener

### ISSUE THREAD

**Issue by kdomagoj** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#218]
After last commit android build throws error:

platforms/android/src/com/cordovaplugincamerapreview/CameraActivity.java:49: error: cannot find symbol
  private CameraPreviewListener eventListener;
          ^
  symbol:   class CameraPreviewListener
  location: class CameraActivity

platforms/android/src/com/cordovaplugincamerapreview/CameraActivity.java:74: error: cannot find symbol
  public void setEventListener(CameraPreviewListener listener){
                               ^
  symbol:   class CameraPreviewListener
  location: class CameraActivity

platforms/android/src/com/cordovaplugincamerapreview/CameraPreview.java:24: error: cannot find symbol
public class CameraPreview extends CordovaPlugin implements CameraActivity.CameraPreviewListener {
                                                                          ^
  symbol:   class CameraPreviewListener
  location: class CameraActivity

**Comment by westonganger** [comment]
This is now fixed in master.

**Comment by kdomagoj** [comment]
Great ! Thanks a lot!
