### ISSUE TITLE
i want more effect

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#229]
i want more effect in camera how can i add more effect like other professional camera please help needed

**Comment by aliwaqassi** [comment]
help need please

**Comment by HartHerbert** [comment]
on the native side or the Javascript-side?

**Comment by aliwaqassi** [comment]
both i want if possible

**Comment by westonganger** [comment]
Please stop posting "I want this now / help me now please" issues they are annoying and discouraging to the maintainers.

Also please be clear and specific with your posts.

**Comment by aliwaqassi** [comment]
sir people are helping you to solve issue , but we need more effect like you cam perfect , if it is possible plase help me sir. or other plugin just for image filter i need really need

**Comment by erperejildo** [comment]
@aliwaqassi this is a open project in which everyone can contribute. No one is making money with this (at least not directly). As you said people are helping to fix issues (either way with PR or testing) but that doesn't mean we have the obligation to add everything people want.

"I want more effect" is not a correct title for a post. This should be more related with issues.
Again, you can create a PR with your code and we can integrate it to the package but please, don't use Github to have a free development there are a lot of websites to hire freelance developers.

Don't take it personally I've read these kind of post many times as just wanted to wrote this down.
