### ISSUE TITLE
Add Photo Library

### ISSUE THREAD

**Issue by maabalaji** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#231]
How difficult to add photo library option ?

**Comment by westonganger** [comment]
Storing files was adding to much complexity to this plugin. We now return base64 image data that you as the developer can do whatever you want with. Do a google search on how to save a base64 image to your device in cordova.

**Comment by maabalaji** [comment]
I think, I am not clear asking my question, like Camera Preview, I would like to have Photo Library/Gallery Preview show up in this plug-in.
like getting photo library option (below is for cordova-plugin-camera):
camOptions.sourceType = Camera.PictureSourceType.PHOTOLIBRARY;
navigator.camera.getPicture(this.cameraSuccess, this.cameraError, camOptions);

**Comment by erperejildo** [comment]
This is a plugin related to **take pictures from HTML** other plugins like filters/effects or galleries are extra functions already covered (and tested) by others plugins. Also quite well supported.

Features like zoom, flash, focus, etc. are related with this
