### ISSUE TITLE
ionic 2 starting project

### ISSUE THREAD

**Issue by riccardotreagles** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#232]
I start new ionic2 project. Then I add the plugin (master) with
ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

But I cannot find the reference for CameraPreview.

If I import ionic-native, the signature of the method startCamera() is the old. It said me "Invalid number of arguments, expected 6". I would like to use new methods with new signature startCamera(opt,success,error)

**Comment by Ghayyas** [comment]
Use this.

`http://ionicframework.com/docs/v2/native/camerapreview/`

**Comment by riccardotreagles** [comment]
Ok but if I follow http://ionicframework.com/docs/v2/native/camerapreview/ it uses 0.0.8 version, the last release. I'd like to use the master, with new features.

**Comment by shaneparsons** [comment]
@riccardotreagles just add `declare var CameraPreview: any;` to the top of the page and it'll work when previewed on a device.

**Comment by riccardotreagles** [comment]
It works!
Just add **declare var CameraPreview: any;** after the import

Thank you  very much @shaneparsons
