### ISSUE TITLE
Camera Preview App Crash in android 6.0 on Ionic 2

### ISSUE THREAD

**Issue by Ghayyas** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#234]
Hello all,
Im facing this issue in my android 6.0. App runs fine and start perfectly. But when I click on StartCamera app Crashed. 

code:

        startCamera(){
        let react: CameraPreviewRect = {x: 40, y: 100, width: this.calcWidth ,height: 220};
        // let react = {x: 40, y: 100, width: this.calcWidth ,height: 220}   //Decrepted due to previous code
        CameraPreview.startCamera(react,'back',true,true,true,1);
        //.startCamera(react, defaultCamera:'back',tapEnabled: true, dragEnabled: true, toBack:true, alpha:1); //Decrepeted        
         }

**Comment by riccardotreagles** [comment]
Check if you have camera permission and retry.

**Comment by ksp147** [comment]
Can you tell me how to request the permission?

**Comment by Ghayyas** [comment]
Dear @ksp147 I have made the Example in Ionic 2. Follow this..
https://github.com/TeamClouders/Ionic-2-camera-preview

**Comment by ksp147** [comment]
Thank You! I can try it!

**Comment by Donbelar** [comment]
Did you solve your problems @Ghayyas

**Comment by Ghayyas** [comment]
Not in ionic 2 native. But I use Core Camera Preview. You can see it here..
https://github.com/TeamClouders/Ionic-2-camera-preview
