### ISSUE TITLE
can we have more camera effects?

### ISSUE THREAD

**Issue by RahibAly** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#235]
I need camera effects like camera360, Retrica, ucam and other similar android apps have.. Can I expect in near future to have such effects in this plugin? my app is in development process and I have to add more effects..

**Comment by erperejildo** [comment]
Similar to this one:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/229

You also can use other third party libraries to apply more effects to your picture. That's what I'm doing. There are already packages focused on this and I personally think that this one should be more related to take a picture and get the image

**Comment by RahibAly** [comment]
Can you recommend some of those packages which you are using to add effects on photo?

**Comment by aliwaqassi** [comment]
@erperejildo can you please tell me that third party libraries?

**Comment by erperejildo** [comment]
There are a quite of few just search by "filters" instead "effects":
http://techslides.com/instagram-image-filters-with-html5-canvas
http://evanw.github.io/glfx.js/demo/
http://joelb.me/jsmanipulate/
I personally tried some of them and work like a charm.

Depending what you are looking for you could do some filters on css as well:
https://www.w3schools.com/cssref/css3_pr_filter.asp

Feel free to add here new more
