### ISSUE TITLE
takePicture: successCallback gets an array in iOS version

### ISSUE THREAD

**Issue by ander2** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#236]
According to the documentation, `takePicture` accepts a successCallback as argument, which is provided a base64 representation of the taken picture(`base64PictureData` in the docs).

In the iOS version, `takePicture`'s successCallback is being provided a 1 element array, which contains the base64 representation of the picture.

Please, make function consistent with the documentation.

**Comment by Choppel** [comment]
@ander2 
Hi,
in the current version it is working for me.
Please check if this is still a problem. If so, please update. If not, please close this ticket.

regards Choppel
