### ISSUE TITLE
picture save in IOS gallery

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#242]
this was in old version take picture and save into gallery but now its not it return base64 , now i want to know how you do disable save taken picture to gallery , share your code for IOS
thanks

**Comment by anneb** [comment]
I am not sure if I understand the question. Do you want to save the picture in the gallery or not? The newer versions of the plugin do NOT save the picture in the gallery.

**Comment by aliwaqassi** [comment]
sorry for my english
i have an older version that version save pictures in gallery preview and original , now in the newer version  of the plugin dont save the picture in the gallery, so i am using an old one just tell me how to disable save image to the ablum ,  method
thanks
