### ISSUE TITLE
White balance parameter

### ISSUE THREAD

**Issue by SVANNER** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#262]
Hi, i first want to thank your working to keep this very interesting plugin working. I found the idea of getting the camera preview inside the application and take a picture 'as it will be used' in the app contributing to a better user experience. 

One important parameter in photography is the white balance. Setting this before taking the picture, induces less picture corrections and gives a better chance to use the picture directly in the app.

A second parameter very useful is the ability to compensate the exposure.

**Should it be possible to methods for handling this parameter (like you do for the flash mode) and have access to the exposure compensation.**

Thanks a lot !

**Comment by westonganger** [comment]
Is this still an issue with the latest master?

**Comment by SVANNER** [comment]
The exposure is now ok. I'll close this issue knowing that one of my further PR will address the white balance parameters.
