### ISSUE TITLE
No promise returned from takePicture method in iOS.

### ISSUE THREAD

**Issue by rrundle** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#263]
In iOS, when I call the takePicture method on CameraPreview a picture is taken but nothing is returned in the callback function (or promise). I find both the pictures in the device's library. To verify, I console logged a string in the promise function that never runs.

Any ideas what this might be? 

Thanks!

**Comment by westonganger** [comment]
Are you using master or the version on npm. Must use master

**Comment by rrundle** [comment]
I see. I was importing CameraPreview from @ionic-native. How shall I declare the plugin from master? I tried <code>(<any>window).plugins.cameraPreview.takePicture(pictureOpts)</code> and got an error code saying <em>undefined is not an object</em>.

**Comment by westonganger** [comment]
Please follow the readme from master. Your code is wrong.

**Comment by SVANNER** [comment]
@rrundle 

To use the master in Ionic 2, her is the installation from master that worked for me:

**Install**
```
ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git
sudo npm install --save @ionic-native/camera-preview
```

Note i was not able to use some methods (see my issue #258)

**Code**
```
import { CameraPreview, CameraPreviewOptions, CameraPreviewDimensions } from '@ionic-native/camera-preview';
...
constructor(private cameraPreview: CameraPreview) {
...
}
...

this.cameraPreview.takePicture(options).then((imageData) => {
          var picture = 'data:image/jpeg;base64,' + imageData;
...
})
```

**Comment by rrundle** [comment]
Thanks @SVANNER. I've tried using the method described in master as @westonganger pointed out. I just used
<code>import { CameraPreview } from 'ionic-native'</code>

It seemed to access the plugin fine but my build broke.
I now get this build error:

<code>Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CameraRenderController", referenced from:
      objc-class-ref in CameraPreview.o
  "_OBJC_CLASS_$_CameraSessionManager", referenced from:
      objc-class-ref in CameraPreview.o
ld: symbol(s) not found for architecture arm64
</code>

**Comment by rrundle** [comment]
@SVANNER Your solution worked!! Using the plugin directly made it worse in Ionic. Thank you so much for chiming in :)!
