### ISSUE TITLE
startCamera() fails in IOS

### ISSUE THREAD

**Issue by SVANNER** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#267]
Hi, I've built a simple Ionic 2 app that startCamera() when pushing a button. The code is:

```
openCamera() {
         
      let options = {
        x: 0,
        y: 0,
        width: 120,
        height: 120,
        camera: "back",
        toBack: false,
        tapPhoto: false,
        previewDrag: false
      };
      console.log("camera: " + options.camera);
      this.cameraPreview.startCamera(options).then(() => {
          console.log("startCamera");
```
**Issue**
When starting the camera the app exits without any message or return code.
Note the same app works perfectly when tested an an Android device.

**Plugin version:**
I used the plugin 0.9.0 from the master.

**Ionic Info:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**IOS Device:**

```
iPhone SE
IOS 10.3.1
```
Edit:

I finally found what's happens: IOS 10 requires an key/value pair for the description of the usage of the camera when it asks authorisation to use the camera to the user. If this information is not provided, the app crashes.
I tried to pass the following variable in the installation command of the plugin but, did not work:  

`--variable CAMERA_USAGE_DESCRIPTION="My description"
`

I finally set it directly in the plist of the Xcode project using Xcode.

Does somebody knows how to do it properly using Ionic 2 framework ?

Thanks a lot !

**Comment by westonganger** [comment]
Is this still an issue with the latest master?

**Comment by SVANNER** [comment]
To my opinion it was already there before. I think the problem appears whenrunning on an IOS 10 device (ie my iPhone SE currently running IOS 10.3.1). I do not see any way to configure the plugin so it is directly integrates in a plist in Xcode.

Kind regards,

**Comment by SVANNER** [comment]
Re-test with the last master: same problem.

Kind regards,

**Comment by tarikboschi** [comment]
Hi @SVANNER, I had the same problem, I solved it by adding the following configuration in the plugin.xml file

` <platform name="ios">
         .... 
   <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
        <string>Your description</string>
    </config-file>`

**Comment by SVANNER** [comment]
@tarikboschi, @westonganger 
Thanks a lot for the information. I'll try this night. If ok i'll close the issue.

**Comment by SVANNER** [comment]
Hi, this solves the problem !
Thanks a lot !

**Comment by westonganger** [comment]
@SVANNER Do I need to add anything to the Readme?

**Comment by NishiGaba** [comment]
@tarikboschi , I had the same problem even after adding this configuration to plugin.xml file.

**Comment by tarikboschi** [comment]
@NishiGaba You rebuild app and run in device?

**Comment by NishiGaba** [comment]
@tarikboschi , I rebuild the app but still facing the same issue.

**Comment by tarikboschi** [comment]
@NishiGaba, I'm using version 0.9.0
![screen shot 2017-05-31 at 08 15 41](https://cloud.githubusercontent.com/assets/1490331/26629650/af204fba-45d9-11e7-80a5-feb5cca5ac0e.png)

**Comment by juliusanwar** [comment]
@tarikboschi I've a problem with my cordova-plugin-camera, it can be used after I back to the homescreen and touch the camera again in my app. I'm currently using <plugin name="cordova-plugin-camera" source="npm" spec="~2.4.1"/>. Its just stuck in there and never show the camera. Can you help me ? I hope so. Thanks!

**Comment by tarikboschi** [comment]
@juliusanwar In your code is starting and stopping the camera or starts and after use only hidden? With me it gave a similar problem to starting and stopping the camera.

**Comment by F1LT3R** [comment]
Thanks for the pointer @SVANNER - I was able to update this from Xcode.

- Goto: Xcode > Targets > Info
- Click the little `+` in the Custom iOS Target Properties
- Enter: `Privacy - Camera Usage Description` as the key
- Enter: "taking pictures" as the Type

<img width="1157" alt="screen shot 2017-12-14 at 3 50 58 pm" src="https://user-images.githubusercontent.com/1218446/34013794-df141af0-e0e6-11e7-98cb-ca0067eef5dc.png">
