### ISSUE TITLE
Is it possible to access the video preview stream somehow?

### ISSUE THREAD

**Issue by brewh0use** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#269]

**Comment by westonganger** [comment]
No its not possible. Someone tried in issue #135. This is not going to get implemented unless we have some wizard come onboard that wants to create and maintain this feature.

**Comment by westonganger** [comment]
@vipulsharma144 has submitted PR #587 which completes the work done from @icetec-solutions implementation. I would appreciate if anyone has any comments on that PR.

**Comment by westonganger** [comment]
Video recording functionality for Android has been implemented in master via #587
