### ISSUE TITLE
takePicture() returns a one member array.  

### ISSUE THREAD

**Issue by artemis-prime** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#273]
Docs say it returns a string (examples)

**Comment by westonganger** [comment]
Please ensure you are using master, not the one on NPM. Also which platform(s) is this occurring?

**Comment by Choppel** [comment]
@artemis-prime 
Hi,
in the current version it is working for me.
Please check if this is still a problem. If so, please update. If not, please close this ticket.

regards Choppel
