### ISSUE TITLE
Landscape preview not 100% width

### ISSUE THREAD

**Issue by jedofus** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#275]
Hello i have problem on landscape orientation. Preview camera is not of 100% width of my screen...
On my rotate/resize screen event of javascript, i stopped and reactivated camera but it didn't works. I try also function CameraPreview.setPreviewSize but not resolved my problem.

You can see that at the bottom of this description.

Portrait: 
![img_0400](https://cloud.githubusercontent.com/assets/18715353/25134081/f139c7fc-244e-11e7-941b-ed3c905d7831.PNG)

Landscape 
![img_0401](https://cloud.githubusercontent.com/assets/18715353/25134090/f66e0c9c-244e-11e7-88ae-94f8378a5574.PNG)

how can i resolved it ? thank you

**Comment by jedofus** [comment]
I come to notice something.
When app is initially starting with Portrait position, when you rotate, the preview is not 100% of device purpose (only on landscape position)

When app is initially starting with Landscape position, when you rotate, the preview have 100% width of device on portrait & landscape position.

**Comment by jedofus** [comment]
Hi @westonganger,
Lock orientation preview on "CustomCameraViewController.m" or "CameraPreview.m" is a solution to resolved landscape problem or not ?

**Comment by mvg1984** [comment]
Hi! Did you find the solutiion?

**Comment by realivanjx** [comment]
i know this is late but restarting camera fix this problem
