### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by FrancescoMussi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#277]
Hey guys there is something wrong with the installation of the plugin.
I have tried several times to install it, each time on a fresh Ionic 3.0.1 app, and each time I test it in the device I get the following error:

`plugin_not_installed`

![image](https://cloud.githubusercontent.com/assets/5312907/25239744/9bbe42a6-25f9-11e7-96c0-4af11bf9be2c.png)

Could you please take a look at that?

For the installation I have followed the [documentation](https://ionicframework.com/docs/native/camera-preview/):

```
ionic plugin add cordova-plugin-camera-preview
npm install --save @ionic-native/camera-preview

```

Thanks!

**Comment by westonganger** [comment]
You must use the master version of the plugin. We are still actively working on v1.0.0. See the readme for install instructions.

**Comment by FrancescoMussi** [comment]
Thanks for fast reply.
Made as you suggested and is working fine.

**Comment by FrancescoMussi** [comment]
Sorry one last question.
Should I propose a modification in the Ionic documentation about installation?
Or soon will be possible to install it using the following command:
`ionic plugin add cordova-plugin-camera-preview`?

**Comment by westonganger** [comment]
Propose the change, it could take a little while.
