### ISSUE TITLE
toBack false doesnt show the preview

### ISSUE THREAD

**Issue by Gerem** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#282]
Hi,

I have this issue, if you can answer will be good.

**Comment by hatimmakki** [comment]
make the background transparent (colorless)
```
html, body, .ion-app, .ion-content {
  background-color: transparent;
}

```
if it's still hidden, try to find what is blocking the camera, e.g. some div with black bg. and give it a transparent bg.

background-color: transparent;
or
background: rbg(0,0,0,0.0);
