### ISSUE TITLE
CameraPreview.getMaxZoom doesn't fire on android

### ISSUE THREAD

**Issue by riccardotreagles** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#283]
On android I used:

CameraPreview.getMaxZoom(function(maxZoom){
  console.log(maxZoom);
});

but it seems not working. I can't see the value. I put a breakpoint in debug mode, but nothing happens.

**Comment by SVANNER** [comment]
Hi,
Could you please share your code, so i can take a look at it ?

Thanks !

**Comment by riccardotreagles** [comment]
I Integrated the plugin on my Ionic v3 project. All work fine. I used the master.
ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

At the top of my ionic component I put `declare var CameraPreview: any`;

These methods work fine on my android device.
```
CameraPreview.startCamera(..)
CameraPreview.takePicture(..)
CameraPreview.setZoom(..)
```

But if I use a button with this handler function, it fires, but I don't get the callback, and I have no error in my console:

- in html;

`<button ion-button (click)="getMaxzoom()">max Zoom</button>`

- in my .ts file

```
import ...;

declare var CameraPreview: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})
export class HomePage {

	getMaxzoom(){
		CameraPreview.getMaxZoom((maxZoom)=>{
                       //HERE NOT EXECUTE
			console.log(maxZoom);
			alert('max zoom ' + maxZoom);
		});
	}
}
```

**Comment by SVANNER** [comment]
Hi thanks for sharing your code.
I'll comeback this night with some piece of code working with Ionic 3 framework.
Kind Regards,

**Comment by SVANNER** [comment]
Hi,
Assuming you've got installed the plugin from the master, first, did you install the Ionic native wrapper ? If this is not the case, you should install it using:

`npm install --save @ionic-native/camera-preview`

Here is the code i put in the **_app.module.ts_**:

`import { CameraPreview } from '@ionic-native/camera-preview';`

and in the providers, add the CameraPreview:

```
providers: [
    StatusBar,
    SplashScreen,
    CameraPreview,
    ....
```
in a page like **_home.ts_**

`import { CameraPreview } from '@ionic-native/camera-preview';`

In the constructor of the class for the page, define a cmeraPreview object:

 `constructor(public navCtrl: NavController, private cameraPreview: CameraPreview,...`

Then, for example, using the trigger for a button, first start the camera using (promize syntax):

```
openCamera() {
      this.events.publish("lockScreen", "portrait");
      let options = {
        x: 40,
        y: 210,
        width: window.screen.width-80,
        height: 120,
        camera: this.cameraPreview.CAMERA_DIRECTION.BACK,
        toBack: false,
        tapPhoto: true,
        previewDrag: false
      };
      this.cameraPreview.startCamera(options).then(() => {
        console.log("startCamera");
      }, (error) => {
        console.log("startCamera error: " + error)
      })
  }
```
Then using the trigger of a button (like you do), also using the promize syntax:

```
getMaxzoom() {
      this.cameraPreview.getMaxZoom().then((value) => {
           console.log("getMaxZoom:" + value)
      }, (error) => {
            console.log("getMaxZoom error: " + error)
      })
}

```
Let me know if any issue...

**Comment by riccardotreagles** [comment]
Yes your code works fine!

But my mistake was that I didn't call the method after the startCamera(). I called it before.

Sorry for the waste of time. It was my issue, not of the plugin.

I appreciate a lot your job.

**Comment by SVANNER** [comment]
You're welcome !

I propose you close the issue.

Thanks,
