### ISSUE TITLE
Is there an option to put the camera preview inside a div.

### ISSUE THREAD

**Issue by JCepedaVillamayor** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#284]
Hi everyone!

I'm using this plugin to preview the camera inside the app, but you must indicate the coordinates, the width and height. 
Is there a way to put the camera preview inside an html tag? This would allow us to fix the camera preview in the same position, adapting it with multiple resolutions and layouts.

Thank you for your help! 

Regards.

**Comment by SVANNER** [comment]
I also get this problem. If i remember well, Cordova allows to add and native activity as a view, but do not allow to put a native activity in an html element.
As a workaround in an app allowing to change an image by taking a photo shoot, i managed the preview to be placed exactly at the same place and size of the image. Additionally, i also arrange to lock the screen orientation while the preview is displayed, restoring screen orientation when the preview is closed.

**Comment by JCepedaVillamayor** [comment]
Yes @SVANNER I was thinking about blocking the screen orientation, thanks!
