### ISSUE TITLE
How to get the current flash mode?

### ISSUE THREAD

**Issue by hatimmakki** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#285]
How to get the current flash mode?
I am looking to away to get the current flash mode, so I can save it in the localStorage and set the same flash mode again when restarting the app.
thanks

**Comment by SVANNER** [comment]
Indeed, i note this method is not implemented. I am currently working in a new PR to mainly adress focus mode changes. i will also include the getFlashMode() method in this PR.

Kind regards,

**Comment by westonganger** [comment]
This functionality is now in master. Thanks @SVANNER
