### ISSUE TITLE
Tap to Focus give "Invalid Action"

### ISSUE THREAD

**Issue by alilishan-omniphics** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#286]
Hi I'm trying to use CameraPreview.tapToFocus and the response is "Invalid Action"  can pls  anyone tell me what i am missing.

CameraPreview.tapToFocus(100, 100, function(success){
			console.log('ss '+success)
		}, function(error){
			console.log('ee '+error)
		});

Thanks

**Comment by SVANNER** [comment]
Hi,

Did you tried to use it in Android ?
Please note that the tapToFocus() method is currently available for IOS only.

**Comment by alilishan-omniphics** [comment]
Hi

Yes. I am trying to use it on an Android Mi.
Is there a way I can do for Android?

**Comment by westonganger** [comment]
Not available in android as stated in readme. Closing
