### ISSUE TITLE
setPreviewSize: size error

### ISSUE THREAD

**Issue by catakkio** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#296]
Every time that i set a previewSize, on android i get that the size inserted is not supported. The only supported size seems to be 1980 x 1080. Can i get the list of supported preview size ?

**Comment by westonganger** [comment]
1920x1080 is probably your max screen resolution.

**Comment by Choppel** [comment]
@catakkio 
Is this issue still relevant to you? If not, please close it.
