### ISSUE TITLE
Ionic 2, iOS, startCamera doesn't work when toBack is set to true

### ISSUE THREAD

**Issue by marcocarosi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#298]
I am trying to make the `toBack: true` option working with Ionic 2 on an iOS device.
I have set the background as transparent, with (see app.scss):

`html, body, .ion-app, .ion-content, ion-app.ios, .ion-page ion-content {
  background-color: transparent;
}`

but the camera preview does not appear when I try to put it behind the html.
On the other hand, the preview works fine when it is above the html.
You can find a sample project here showing this issues (just created, using the latest Ionic 2 version, 3.1.1) here:
[https://github.com/foneclay/ionic2-camera-preview-test](url)

Of course, the cordova-plugin-camera-preview Sample App works fine on the device I am testing it (iOS iPad, iOS version 10.3)

Let me know how I can help to fix this issues.

**Comment by mikewagz** [comment]
Try this in your scss:
`html, body, ion-app, ion-content, ion-page, .nav-decor{
  background-color: transparent !important;
}`

**Comment by marcocarosi** [comment]
.nav-decor class! My bad I missed that!
Ionic 2 does not used html and body tags so the minimal css configuration seems to be:

`ion-app, ion-content, .nav-decor {
  background-color: transparent !important;;
}`

I will updated the test app, in case somebody stumbles upon it.

I guess I can close this issue as fixed.
Thank you!
