### ISSUE TITLE
[Bug] Issue with android crosswalk

### ISSUE THREAD

**Issue by crissi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#3]
If you are using crosswalk to speed up your android app it only works after first closing the app and then opening it again, then the preview shows.

**Comment by crissi** [comment]
To easily get an crosswalk app running you can see this post:

http://ionicframework.com/blog/crosswalk-comes-to-ionic/

**Comment by crissi** [comment]
If I click the sleep button (power button) and click it again it also works.

**Comment by dested** [comment]
I can confirm this is still happening. Does anyone have any insight into a potential fix? As far as I can tell the fragment is being displayed BELOW the crosswalk activity, but I do not know how to properly bring it to front.

**Comment by angeltveit** [comment]
This is still very relevant. Any news on this issue?

**Comment by julitroalves** [comment]
I have same issue with crosswalk 18+ beta. I can show camera on ionic view just when using "toBack" parameter as `true` on **startCamera** but when I use `false` the plugin don't show camera square.
Another thing when I using toBack false on startCamera I'm not able to put the camera square when I want with x,y parameters.

Anyone have a solution?

**Comment by Giriton** [comment]
Same issue here with Crosswalk 18+ and 19+ . As soon as we add crosswalk into the project (cordova plugin add cordova-plugin-crosswalk-webview) , the camera preview will never show anymore.

Does anybody have a clue how to hotfix such issue?

**Comment by Giriton** [comment]
Ok, I managed to make the camera preview work with Crosswalk 18+ by adjusting following settings in config.xml of the cordova project: `xwalkZOrderOnTop` set to `false` and `CrosswalkAnimatable` set to `true`. The part of config.xml looks like this:

`<preference name="xwalkVersion" value="18+" />`
`<preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />`
`<preference name="xwalkMode" value="embedded" />`
`<preference name="xwalkMultipleApk" value="true" />`
`<preference name="xwalkZOrderOnTop" value="false" />`
`<preference name="CrosswalkAnimatable" value="true" />`
