### ISSUE TITLE
How to import it in a Ionic 2.x with ts?

### ISSUE THREAD

**Issue by yolosaucisson** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#300]
I have "cannot find module cordova-plugin-camera-preview" :(

**Comment by cmdickson** [comment]
Without any details of what you've done or when/where the error occurs, I'm going to be guessing, but you probably want to use the Ionic Native plugin API.  

Basically comes down to:

1. Add the plugin via Ionic
2. Install @ionic-native/core and @ionic-native/camera-preview
3. Declare `CameraPreview` in module providers
4. Have `CameraPreview` injected into your component or wherever

Full documentation: http://ionicframework.com/docs/native/camera-preview/

**Comment by SVANNER** [comment]
This error is also raised when you have an outdated version of ionic-native core libraries. Try

`npm install --save @ionic-native/core@latest`

**Comment by SVANNER** [comment]
@cmdickson 
The camera preview plugin is in beta version and is changing very often. I recommend to install the plugin from the master using:

`ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git `
