### ISSUE TITLE
CameraPreview.js is not found

### ISSUE THREAD

**Issue by uzairali001** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#303]
I have installed the plugin in my project via `cordova plugin add cordova-plugin-camera-preview` and added `<script type="text/javascript" src="CameraPreview.js"></script>` right after `cordova.js` and before my `script.js` but I am getting error `GET file:///android_asset/www/CameraPreview.js net::ERR_FILE_NOT_FOUND` I don't know why, have I missed something?

**Comment by aliwaqassi** [comment]
remove this line in your html
<script type="text/javascript" src="CameraPreview.js"></script>
