### ISSUE TITLE
Set color effect ?

### ISSUE THREAD

**Issue by jedofus** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#304]
Hi i want to use function setColorEffect(),
i don't see any effect on preview camera on iOS .
How can i resolved this function on iOS platform ?  
________________________________________________________
**UPDATE :** 
After debug on Xcode, 
I see that the function is well called on setColorEffect on camerapreview.m but color effect is only applied on preview take picture on not on preview camera and i have no idea to apply color effect on preview camera

**Comment by Scriptonita** [comment]
SetColorEffect work in my app on Android, but not in IOS.

`
$efectos = ["negative", "mono", "posterize", "sepia", "none"];
$efectIndex= 0;
...
...
function scanner() {
  CameraPreview.setColorEffect($efectos[$efectIndex],
          function() {
            $("#nombreApp").html("Filtro " + $efectos[$efectIndex] + " aplicado");
          },
          function() {
            $("#nombreApp").html("Error efecto" + error);
          });
...
  $efectIndex++;
}
`
