### ISSUE TITLE
iOS memory usage

### ISSUE THREAD

**Issue by MikeBurgher** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#31]
This is a GREAT plugin! Kudos.

I use it in a time-lapse app. Works great on Android, for hours; but on iOS, I observe that the heap continues to grow as pictures are taken, until the device is eventually out of memory.  Any thoughts?

Again, a great plugin.

**Comment by cyounghusband** [comment]
I'm also finding that it leaks memory terribly.  I got about 40 photos out of an Iphone6 before it just crashes.

**Comment by orlovev88** [comment]
@cyounghusband Try to use CFRelease(preivewImage) and CFRelease(finalImage). That's helps for me

**Comment by phii01** [comment]
is there any update on that? is there a stable version in some of the many forks/branches which contains a fix?

**Comment by orlovev88** [comment]
@phii01 try this version https://github.com/skanygin/CordovaCameraPreview. we made some fixes for this plugin. maybe it will help you

**Comment by phii01** [comment]
thanks! i'll have a look on that!

**Comment by erperejildo** [comment]
Version updated and merged

**Comment by Tawsif** [comment]
is this issue fixed ?
