### ISSUE TITLE
Multiple pictures

### ISSUE THREAD

**Issue by wemaro** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#317]
I am quite new to cordova / ionic development so forgive me if my question is obvious.
I want to take an x amount of pictures without closing the camera preview. The image data will be pushed into an array which will be send to the next page whenever the user is done with taking pictures. The problem I face right now is when I take a picture, the taken picture is displayed forever. I was wondering if I can remove the taken picture from my screen or not show it at all. I thought this would be easy by just manipulating the html element in which the taken picture is set, but I can't seem to find this element.  Does anyone has an comparable scenario? What's your solution?

Also, The takePicture function doesn't seem to work as it is supposed to, my image array remains empty and the console.log inside takePicture doesn't fire.

This is my code:
```

export class CameraPage {
	images: Array<{src: string}>;

	constructor(public navCtrl: NavController,
		public toastCtrl: ToastController,
		private cameraPrev: CameraPreview,
		private diagnostic: Diagnostic,
    	private platform: Platform) {
			this.images = [];
        	this.checkPermissions();
    }

    checkPermissions() {
        this.diagnostic.isCameraAuthorized().then((authorized) => {
            if (authorized)
                this.initializePreview();
            else {
                this.diagnostic.requestCameraAuthorization().then((status) => {
                    if (status == this.diagnostic.permissionStatus.GRANTED)
                        this.initializePreview();
                    else {
                        // Permissions not granted
                        // Therefore, create and present toast
                        this.toastCtrl.create(
                            {
                                message: "Cannot access camera",
                                position: "bottom",
                                duration: 5000
                            }
                        ).present();
                    }
                });
            }
        });
    }

    initializePreview() {

        this.platform.ready().then(() => {
            let options = {
                x: 0,
                y: 0,
                width: window.screen.width,
                height: window.screen.height,
                camera: this.cameraPrev.CAMERA_DIRECTION.BACK,
                toBack: true,
                tapPhoto: true,
                previewDrag: false
            };
            this.cameraPrev.startCamera(options).then((res) => {
				console.log(res)
			}, (err) => {
				console.log(err)
			});

		})
	}

	takePicture() {
		this.cameraPrev.takePicture().then((imgData) => {
			console.log(imgData);

			let imageSrcData = 'data:image/jpeg;base64,' + imgData;
			this.images.push({
				src: imageSrcData
			});
			console.log(this.images);
		}, (err) => {
			console.log(err);
		})
		console.log(this.images);
	}
}

```

**Comment by LightMind** [comment]
Hello :)
CameraPreview.takePicture() does not return a promise. You need to use callbacks instead.
See https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview#takepictureoptions-successcallback-errorcallback

What do you mean by 

> the taken picture is displayed forever

Does the preview of the camera freeze?

**Comment by wemaro** [comment]
Thanks for your answer!
You're right. Didn't realize I needed to use callbacks. 
Indeed, the camera froze after I took a picture. I've just changed the promise to a callback and everything works the way it's supposed to now. :)
