### ISSUE TITLE
keep awake behavior?

### ISSUE THREAD

**Issue by cesarve77** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#318]
First, thanks and congratulation for this amazing plugin, second sorry for my english.

Is possible keep awake the app while the preview camera is working?

In android the app get block in few seconds if nothing is tap

**Comment by westonganger** [comment]
Use the cordova plugin insomnia for this functionality.

**Comment by cesarve77** [comment]
thanks a lot

2017-06-05 11:05 GMT+10:00 Weston Ganger <notifications@github.com>:
