### ISSUE TITLE
How to set CameraPreview orientation according to the Device Orientation ?

### ISSUE THREAD

**Issue by Ekta09** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#32]
I need to set CameraPreview orientation according to Device orientaion i.e. Landscape or portrait. 
By default what it shows is wrong. How can I change it ?

**Comment by rrNuvoPoint** [comment]
Android/iOS? And is it the preview or captured file?

tor. 16. apr. 2015 kl. 11.27 skrev Ekta09 <notifications@github.com>:

**Comment by Ekta09** [comment]
It's my Cordova project and I want it to work for both platforms android and ios.

**Comment by rrNuvoPoint** [comment]
I dont have this issue. So i ask if you Can describe the error better so i
can understand and help.
tor. 16. apr. 2015 kl. 11.30 skrev Ekta09 <notifications@github.com>:

**Comment by Ekta09** [comment]
![screenshot_2015-04-16-16-10-05](https://cloud.githubusercontent.com/assets/10953781/7179452/98e7648c-e455-11e4-8f08-d3e20ad2f863.png)
![screenshot_2015-04-16-16-07-18](https://cloud.githubusercontent.com/assets/10953781/7179451/98e75168-e455-11e4-8a8f-7650556c06e7.png)
See these two screen shots in my phone.. 1st image is in portrait mode : In that cameraPreview is opening in portrait mode.
In 2nd image I changed my device orientation to landscape mode but cameraPreview is still showing preview in portrait mode. while captured image is proper according to landscape only. 

So here there is a problem with cameraPreview. I hope I have given enough detail. Thank you..

**Comment by rrNuvoPoint** [comment]
You have. Looking through the code. It dose not seem to support this option
(minor change). If the autor had not corrected this at monday, i will fork
a version and correct it for you. :-)
tor. 16. apr. 2015 kl. 13.05 skrev Ekta09 <notifications@github.com>:

**Comment by Ekta09** [comment]
I think I have got to know where the problem is..
1. If we start camera in portrait mode, CameraPreview opens up in portrait mode only.
2. In case of Landscape mode, When I make my device orientation as landscape first  and then if I start camera, CameraPreview opens up as landscape mode only.
3. But in case if camera is already started in landscape/portrait mode and during that if we change device orientation, It doesn't get changed again. Means I need to restart my camera if I want to change device orientation and cameraPreview orientation accordingly. ! 
I have attached here screenshots to show that, I hope it helps. Thanks.

![screenshot_2015-04-16-16-15-32](https://cloud.githubusercontent.com/assets/10953781/7179632/a62c49da-e457-11e4-97a6-11288b2ed7aa.png)
![screenshot_2015-04-16-16-16-53](https://cloud.githubusercontent.com/assets/10953781/7179633/a62f7e52-e457-11e4-8c8b-6add32cc74f2.png)

**Comment by Ekta09** [comment]
Its really so kind of you. Thanks a ton . :)

**Comment by rrNuvoPoint** [comment]
Sorry.. I can't seem to reproduce this error on my device so cannot solve it..

**Comment by westonganger** [comment]
This should now be fixed in master. Closing

**Comment by rrath-edr** [comment]
I am facing the same issue, I have the latest code from master the issue seems persist. Please suggest how to resolve it.

**Comment by parraclaudio** [comment]
I am facing the same issue, I have the latest code from master the issue seems persist. Please suggest how to resolve it.
