### ISSUE TITLE
plugin needs android:required="true" in plugin.xml

### ISSUE THREAD

**Issue by abariatti** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#321]
That plugin needs the camera feature to work thus plugin.xml should reflect that.

`<uses-feature android:name="android.hardware.camera" />`
should be 
`<uses-feature android:name="android.hardware.camera" android:required="true" />`

plus it would solve this issue:
**https://stackoverflow.com/questions/34510751/cordova-android-duplicated-uses-feature-from-two-plugins**

**Comment by westonganger** [comment]
#321 was merged.
