### ISSUE TITLE
Crashing on iOS 10

### ISSUE THREAD

**Issue by roddicki** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#325]
The sample app seems to be crashing on iOS 10 but working fine on iOS 8.3.
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app

I tested with and without an additional content security declaration (that is not in the sample app). 
`<meta http-equiv="Content-Security-Policy" content="default-src * gap://ready file:; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src * 'unsafe-inline' 'unsafe-eval'">`
Same result. Is anyone else experiencing this (tested on 3 iOS devices)

**Comment by HartHerbert** [comment]
no its working fine for me. Can't reproduce this error. Works from 8.3 to 10.3.2 for me like charm. I think you just doing some wrong things in your code.

**Comment by roddicki** [comment]
Thanks very much.  Have you built the example / sample app with Phonegap build? Or locally (Just trying to isolate the problem). I can't get the sample app working (I haven't made any code adjustments).

**Comment by roddicki** [comment]
I'm now pretty sure that sample app is crashing because of the Content Security Policy, which has changed for iOS 10. I wonder if anyone would be willing to share a Content Security Policy that they have had success with using Camera-Preview on iOS 10.

**Comment by roddicki** [comment]
I've now solved this.
After iOS 10 you have to define and provide a usage description of all the system’s privacy-sensitive data accessed by your app. This includes the camera.
The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

Without this the app will crash with a error message in the log (on the IOS device):
"This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data"

This can be achieved by adding the following to your config.xml 
`<gap:config-file platform="ios" parent="NSCameraUsageDescription" overwrite="true">`
  `       <string>We are using the Camera to take a photo, or similar string</string>`
`</gap:config-file>`
