### ISSUE TITLE
Unable to use previous version

### ISSUE THREAD

**Issue by gauravmehla** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#326]
I was building an ionic application and using last release of the plugin (0.0.8). All of my application is depend on this plugin. But suddenly the new release comes and now if i use `ionic plugins add cordova-plugin-camera-preview` it downloads the new version (0.9.0). But in this version there is nothing like .setOnPictureTakenHandler. i have to change the code now. Is there any way i can install the previos version of this plugin ?. i don't know how to proceed now.

**Comment by fyras** [comment]
I think you will be able to install old version like this 
ionic plugins add cordova-plugin-camera-preview@0.0.8

**Comment by westonganger** [comment]
@fyras suggestions should work if not use 

```
cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git#0.0.8
```
