### ISSUE TITLE
app crash when camera DIRECTION to Front

### ISSUE THREAD

**Issue by aliwaqassi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#327]
in Android 5.1 app crash,  its working fine in 6.0 
           let options = {
            x: 0,
            y: 0,
            width: window.screen.width,
            height: window.screen.height,
            camera: CameraPreview.CAMERA_DIRECTION.FRONT,
            toBack: true,
            tapPhoto: false,
            tapFocus: true,
            previewDrag: false
            };
            CameraPreview.startCamera(options);

**Comment by millerbarros** [comment]
I have same problem, anybody have a solution?
