### ISSUE TITLE
ANDROID:Camera doesn't focus and preview looks blurred, Captured Picture also Blured !

### ISSUE THREAD

**Issue by Ekta09** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#33]
Many of the times **Camera doesn't focus and preview looks blurred**, I am working on a application which require accuracy in view/size of the dimensions of object in the captured photo. 
Is there any handle for **"Camera Auto Focus"** and also if any options to **manipulate "Exposure Value"** of camera ? I have gone through code I couldn't get any handle so posting here. Any help is much appreciated. Thanks a lot in advance.

**Comment by Ekta09** [comment]
Please help me out, Captured picture is so much Blurred !! Isn't there any ways to capture sharp edged picture with proper resolution?

**Comment by Ekta09** [comment]
My Problem is fixed. In android also it is "Auto Focusing" now and captured image is also clear and sharp edged. :) Thank you..

**Comment by lvelours** [comment]
I'm having the same issue as you @Ekta09, how do you resolve it ? My phone is a MotoE4G on Android 5.0.2 and when i switch to other app and then return everything works well, resolution is good, no blur. @mbppower is there anything we can do ? How can we set another resolution or force native api to make it when there is resume/pause events coming from switching app ?

**Comment by ioRekz** [comment]
Any one find something here ?

**Comment by RichardBoyder** [comment]
Hi Guys

Any news on this ? Mine is also blury and the camera doesnt auto focus while using this plugin on android.

**Comment by RichardBoyder** [comment]
lvelours, did you come right? ?

**Comment by lvelours** [comment]
nope still not unfortunately !

**Comment by donny08** [comment]
@Ekta09 Can elaborate solution for blurry picture quality in android

**Comment by westonganger** [comment]
Autofocus is now implemented in master.
