### ISSUE TITLE
Base64 return rotate image

### ISSUE THREAD

**Issue by appongit** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#330]
CameraPreview.takePicture({width:640, height:640, quality: 85}, function(base64PictureData){
  /*
    base64PictureData is base64 encoded jpeg image. Use this data to store to a file or upload.
    Its up to the you to figure out the best way to save it to disk or whatever for your application.
  */

  // One simple example is if you are going to use it inside an HTML img src attribute then you would do the following:
  imageSrcData = 'data:image/jpeg;base64,' +base64PictureData;
  $('img#my-img').attr('src', imageSrcData);
});

**Comment by westonganger** [comment]
This is an application specific problem that can easily be found with a little research. Closing.
