### ISSUE TITLE
App Crash on iOS

### ISSUE THREAD

**Issue by HartHerbert** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#331]
i have an ionic 3 App and when I enter the Camera, sometimes it works fine, but sometimes the whole app crashes.

XCode target output:
`2017-06-30 13:47:43.312575+0200 myApp[3473:984333] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0xa0000006f7475614'
*** First throw call stack:
(0x18d47afe0 0x18bedc538 0x18d481ef4 0x18d47ef54 0x18d37ad4c 0x100056218 0x100165330 0x100164c2c 0x18df57c0c 0x18d429aa4 0x18d4297a8 0x18d429068 0x18d426c8c 0x18d356da4 0x18edc0074 0x193611058 0x100027884 0x18c36559c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

and XCode refer me to this line:

![screenshot 2017-06-30_13-55-45](https://user-images.githubusercontent.com/22191877/27734637-0037ffb8-5d9c-11e7-8e58-d1964905b473.png)

![screenshot 2017-06-30_16-37-42](https://user-images.githubusercontent.com/22191877/27740512-8989003a-5db2-11e7-9de6-7dc297111500.png)

maybe the exception have something in common with this one : [https://stackoverflow.com/questions/12657018/nsnumber-to-nsstring-conversion-with-stringvalue-fails](url)
Any advice ? 

EDIT:

Digging deeper into this:
it is the webView that throws the error (XCode log):

`*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0xa0000006f7475614`

On the spotify ios-sdk they had the same error, saying that this comes from a new class from WKWebview 
https://github.com/spotify/ios-sdk/issues/271#issuecomment-81721027

EDIT:
the only point you use `stringValue` is at the line `175` in the `CameraPreview.m` in the ios-src folder.
`NSString * focusMode = [[command.arguments objectAtIndex:0] stringValue];` 

Aren't you converting a string into a string again? isn't this the error ?

**Comment by HartHerbert** [comment]
@SVANNER  @westonganger could one of you take a quick look at this?

**Comment by HartHerbert** [comment]
I found out what was the problem.
When I add `setFocusMode(CameraPreview.FOCUS_MODE.AUTO);` the webview error gets thrown (See above). Even when I add callbacks, it doesn't work and the callbacks don't trigger (no success neither the error callback). 
`CameraPreview.setFocusMode(CameraPreview.FOCUS_MODE.AUTO,
        function()
{
console.log("FOCUSMODE SUCCESS");
},
        function(err){
console.log("FOCUSMODE ERROR:",err);
}
);`

**Comment by stramanu** [comment]
The problem is just this line:
`NSString * focusMode = [[command.arguments objectAtIndex:0] stringValue];`
It should be:
`NSString * focusMode = [command.arguments objectAtIndex:0];`

...
Can you correct this??
Thanks

**Comment by westonganger** [comment]
@stramanu Thanks for the hint on the fix. I just pushed a commit which should fix this. Please test out master and let me know if the problem is fixed.
