### ISSUE TITLE
Android width too small, image distorted/squeezed

### ISSUE THREAD

**Issue by s-zoke** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#34]
Full screen Android images are squeezed horizontally. Using window.innerWidth and window.innerHeight, the height appears to be right, but width is too small. I've temporally fixed this by multiplying my width by 1.5, but this obviously isn't a permanent solution.

**Comment by keeganmccallum** [comment]
+1

**Comment by thomascrown** [comment]
+1

**Comment by thomascrown** [comment]
@s-zoke More specifically, i found that I could temporarily fix this by getting the ratio of the screen height/width, and multiplying the width by that... but its a temporary fix as you said

**Comment by wesleygauntt** [comment]
+1 Still unresolved

@thomascrown 
@s-zoke 
Even in trying the suggested fixes (multiplying the width by either 1.5 or the ratio (height/width)), the preview does not seem to extend more than 60% across the screen. Furthermore, any attempt to bring the preview to a width more than 150px results in a larger formatting error that messes with the height of the preview (slightly different for other device sizes). In taking the photo, the photo looks blown up and is very pixelated (separate issue). Any ideas?

@mbppower Is this repo still being maintained? The above issues are for Android only.

**Comment by erperejildo** [comment]
Fixed with new version. Feel free to reopen if still facing issues
