### ISSUE TITLE
camera preview box using a background?

### ISSUE THREAD

**Issue by bits8** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#345]
wanna use camera preview box in my page full background and add controls to front located on full background camera preview box.
is it possible? can't get the preview html, is there element id or z-index value? 
i tried 999999 z-index for my front controls didn't work.
any help i'd appreciate it. thank you.

**Comment by kostap13** [comment]
Use ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

instead of release version

**Comment by bits8** [comment]
U kidding?
