### ISSUE TITLE
Android back button exiting app

### ISSUE THREAD

**Issue by marceljdb** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#347]
When I call the plugin, it closes the application if I press the back button of Android without going through the "backbutton" listener on the "deviceready".

**Comment by marceljdb** [comment]
I fixed this problem using the onkeylistener inside createCameraPreview, if someone have this problem here the code:

 frameContainerLayout.setFocusableInTouchMode(true);
 frameContainerLayout.requestFocus();
frameContainerLayout.setOnKeyListener( new android.view.View.OnKeyListener() {
			@Override
			public boolean onKey( android.view.View v, int keyCode, android.view.KeyEvent event ) {
		
				if( keyCode == android.view.KeyEvent.KEYCODE_BACK )
				{
					return true;
				}
				return false;
			}		    
 });

**Comment by diegofuks** [comment]
hi, I dont get where should I put this new code. The CameraPreview.js has not a frameContainerLayout object.

**Comment by diegofuks** [comment]
sorry foun it in CameraActivity.java I have updated this file with your code and built the cordova app but still the backbutton exists app after startcamera. What Im missing? tks

**Comment by marceljdb** [comment]
Hi, this is the entire method

`private void createCameraPreview(){
    if(mPreview == null) {
      setDefaultCameraId();

      //set box position and size
      FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(width, height);
      layoutParams.setMargins(x, y, 0, 0);
      frameContainerLayout = (FrameLayout) view.findViewById(getResources().getIdentifier("frame_container", "id", appResourcesPackage));
      frameContainerLayout.setLayoutParams(layoutParams);

      //video view
      mPreview = new Preview(getActivity());
      mainLayout = (FrameLayout) view.findViewById(getResources().getIdentifier("video_view", "id", appResourcesPackage));
      mainLayout.setLayoutParams(new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT));
      mainLayout.addView(mPreview);
      mainLayout.setEnabled(false);

      final GestureDetector gestureDetector = new GestureDetector(getActivity().getApplicationContext(), new TapGestureDetector());

      getActivity().runOnUiThread(new Runnable() {
        @Override
        public void run() {
          frameContainerLayout.setClickable(true);
          frameContainerLayout.setOnTouchListener(new View.OnTouchListener() {

            private int mLastTouchX;
            private int mLastTouchY;
            private int mPosX = 0;
            private int mPosY = 0;

            @Override
            public boolean onTouch(View v, MotionEvent event) {
              FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) frameContainerLayout.getLayoutParams();


              boolean isSingleTapTouch = gestureDetector.onTouchEvent(event);
              if (event.getAction() != MotionEvent.ACTION_MOVE && isSingleTapTouch) {
                if (tapToTakePicture && tapToFocus) {
                  setFocusArea((int)event.getX(0), (int)event.getY(0), new Camera.AutoFocusCallback() {
                    public void onAutoFocus(boolean success, Camera camera) {
                      if (success) {
                        takePicture(0, 0, 85);
                      } else {
                        Log.d(TAG, "onTouch:" + " setFocusArea() did not suceed");
                      }
                    }
                  });

                } else if(tapToTakePicture){
                  takePicture(0, 0, 85);

                } else if(tapToFocus){
                  setFocusArea((int)event.getX(0), (int)event.getY(0), new Camera.AutoFocusCallback() {
                    public void onAutoFocus(boolean success, Camera camera) {
                      if (success) {
                        // A callback to JS might make sense here.
                      } else {
                        Log.d(TAG, "onTouch:" + " setFocusArea() did not suceed");
                      }
                    }
                  });
                }
                return true;
              } else {
                if (dragEnabled) {
                  int x;
                  int y;

                  switch (event.getAction()) {
                    case MotionEvent.ACTION_DOWN:
                      if(mLastTouchX == 0 || mLastTouchY == 0) {
                        mLastTouchX = (int)event.getRawX() - layoutParams.leftMargin;
                        mLastTouchY = (int)event.getRawY() - layoutParams.topMargin;
                      }
                      else{
                        mLastTouchX = (int)event.getRawX();
                        mLastTouchY = (int)event.getRawY();
                      }
                      break;
                    case MotionEvent.ACTION_MOVE:

                      x = (int) event.getRawX();
                      y = (int) event.getRawY();

                      final float dx = x - mLastTouchX;
                      final float dy = y - mLastTouchY;

                      mPosX += dx;
                      mPosY += dy;

                      layoutParams.leftMargin = mPosX;
                      layoutParams.topMargin = mPosY;

                      frameContainerLayout.setLayoutParams(layoutParams);

                      // Remember this touch position for the next move event
                      mLastTouchX = x;
                      mLastTouchY = y;

                      break;
                    default:
                      break;
                  }
                }
              }
              return true;
            }

          });

		  frameContainerLayout.setFocusableInTouchMode(true);
		  frameContainerLayout.requestFocus();
     	  frameContainerLayout.setOnKeyListener( new android.view.View.OnKeyListener() {
			@Override
			public boolean onKey( android.view.View v, int keyCode, android.view.KeyEvent event ) {
		
				if( keyCode == android.view.KeyEvent.KEYCODE_BACK )
				{
					return true;
				}
				return false;
			}		    
		  });
        }
      });
    }
  }`


And the params i use to start the camera is: 
` CameraPreview.startCamera({
                tapPhoto: true,
                previewDrag: false,
                toBack: true
            })`

Remember to delete the platform files after you do this change.

**Comment by rasaturyan** [comment]
Still got this issue, please create a pull request.
