### ISSUE TITLE
takePicture not running onSuccess function

### ISSUE THREAD

**Issue by StratoYE** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#348]
So, I have been trying to update an app which had an older version of the plugin which still had the method setOnPictureTaken. I figured out that now I can just call takePicture and set the function I had in the old method inside the function called onSuccess for takePicture. But I wasn't able to make it work, so I just switched to a number which should be incremented by the function but again it didn't do anything. Could you please tell me what am I doing wrong?
Here is the code:
takePicture envelope :
```
`    takePicture(test) {
        let push:number = test;

        this.cameraPreview.takePicture(function(imgData){
            // document.getElementById('originalPicture').src = 'data:image/jpeg;base64,' + imgData;
            push=push+1;
        });


        return push; 
}`

```
and takePicture function called inside the controller where I am using the provider containing the previous takePicture method:
```

takePicture() {
        // let url:string = 'prova';

        this.push = this.cameraPreview.takePicture(this.push);

        // this.uploadPicture(url);

}
```

P.S.=Don't mind the commented code, was used for the previous function I was trying to make.

**Comment by Choppel** [comment]
@StratoYE 
Hi,
you should add the second parameter (onError function) to see if the command fails.
```
this.cameraPreview.takePicture(function(imgData){
    console.log(imgData);
}, function(error) {
    console.log(error);
});
```

regards Choppel

**Comment by bsirmacek** [comment]
For me it does not return error, however it does not log imgData either. It looks like not executing the takePicture function at all. Any ideas on how to solve that?

**Comment by Choppel** [comment]
@bsirmacek 
Without any input, I am afraid not. Are you sure that the function call actually works? Take a look at the logs. Also, the basic call of takePicture would be without "this." before "cameraPreview.take...".
@StratoYE Is this still an issue. If not, please close it.

**Comment by bsirmacek** [comment]
> This log's nothing and gives no error:

`this.CameraPreview.takePicture({x: 0, y: 0, width: window.screen.width, height: window.screen.height, camera: CameraPreview.CAMERA_DIRECTION.BACK, toBack: false, previewDrag: false, tapPhoto: false, previewDrag:false, saveToCameraRoll: true, saveToPhotoAlbum: true},function(imgData){
		console.log(imgData);
		}, function(error) {
		console.log(error);
	});`

If I use this.cameraPreview.takePicture ('c' instead of 'C', it is not recognized).

I have also tried without 'this' as below. Again it logs nothing and returns no log.

`CameraPreview.takePicture({x: 0, y: 0, width: window.screen.width, height: window.screen.height, camera: CameraPreview.CAMERA_DIRECTION.BACK, toBack: false, previewDrag: false, tapPhoto: false, previewDrag:false, saveToCameraRoll: true, saveToPhotoAlbum: true},function(imgData){
		console.log(imgData);
		}, function(error) {
		console.log(error);
	});`

So how can I take a picture and find it in the camera roll?

**Comment by Choppel** [comment]
@bsirmacek 
1.) Are you sure that your code is being executed at all?

2.) With this plugin you cannot take pictures that are stored in the camera roll. It takes a picture from the cameras raw data stream and returns it as base64 data. You can then mingle with that data (transform, thumbnail, save) but you will need other libraries/plugins for that.

3.) Where did you get the impression that saveToCameraRoll and saveToPhotoAlbum are valid options?

**Comment by Choppel** [comment]
@bsirmacek 
You saw a post explaining these options but didn't take the time to look them up in the original documentation? Are you sure you are looking at the correct plugin page? Maybe you should refactor your code. It seems there is something weird going on, that has nothing to do with this plugin.
@westonganger Please close this issue as there is no input from OP. Thanks.
