### ISSUE TITLE
Initial blurry camera feed

### ISSUE THREAD

**Issue by dbroadhurst** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#35]
Running the code below for the first time renders a blurry camera image feed. Pressing the square app selector on the menu bar and simply reselecting the same app the camera feed is corrected and is no longer blurry.

Tested on Android Nexus 7.2 using 5.1

```
var tapEnabled = true; //enable tap take picture
var dragEnabled = false; //enable preview box drag across the screen
var toBack = false; //send preview box to the back of the webview
cordova.plugins.camerapreview.startCamera({x: 0, y: 0, width: 512, height:256}, "front", tapEnabled, dragEnabled, toBack);
```

**Comment by dbroadhurst** [comment]
I've also tried on the NVidia Shield with the same result.

**Comment by mbppower** [comment]
I think this is something related with some camera models. I am planning to implement a setFocus/setExposure/setFlash etc, so this kind of configuration could be done by Javascript.

**Comment by Ekta09** [comment]
What do you mean by square app selector ? 
If you are talking about CameraPreviewBox then in my case I am opening cameraPreviewBox behind the HTML. So a .png image image with some texture and transparent background is over the preview box. 
Thus tapEnabled or touch the previewBox isn't possible ! 
Can you suggest ?

**Comment by mbppower** [comment]
When you enable toBack, you can't tap the camera box, because it's behind the webview, to solve this you can add an onclick event to a div with the same position and dimensions as the preview box. Then you call takePicture function.

**Comment by dbroadhurst** [comment]
The square app selector I was referring to is the system button you use to switch apps.

**Comment by ramoncarreras** [comment]
@dbroadhurst , same problem here. Any solution? I'm on android 6.0.1.

**Comment by Xwalk-Company** [comment]
In Java for android, create an action

`mCamera.cancelAutoFocus();
mCamera.autoFocus`

or set the focus mode during init

`List<String> focusModes = params.getSupportedFocusModes();
		if (focusModes.contains(Camera.Parameters.FOCUS_MODE_AUTO)) {
		  	// Autofocus mode is supported
			params.setFocusMode(Camera.Parameters.FOCUS_MODE_AUTO);
			mCamera.setParameters(params);
		}`

**Comment by erperejildo** [comment]
Fixed in previous merge
