### ISSUE TITLE
but can you turn off the sound when taking pictures?

### ISSUE THREAD

**Issue by moonlitnighta** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#366]
Is the plugin good, but can you turn off the sound when taking pictures? The sound seems to be forcibly, because the device is still muted after it still has sound

**Comment by westonganger** [comment]
This is not really allowed. See #214

**Comment by luispimenta** [comment]
This here worked for the android. Now I need to know how to do it on ios.

https://github.com/luispimenta/cordova-plugin-camera-preview/commit/5efd7914e33859b1b903acb9805504120268da53
