### ISSUE TITLE
setFlashMode on camera start doesn't work

### ISSUE THREAD

**Issue by immnk** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#367]
I have the following code:
```
this.camera.startCamera(cameraPreviewOpts).then(
          () => {
            this.isCameraStarted = true;
            if (isForClaims) {
              this.camera.setFlashMode("on")
                .then(() => {
                  this.camera.getFlashMode().then(flashMode => {
                    this._logger.log("Camera start mode: ", flashMode);
                  });
                })
                .catch((err) => { this._logger.log("flash mode err: ", err) });
            }
            this.camera.show().then(() => {
              resolve();
            });
          },
          (err) => {
            // this._logger.log("startCamera: err: ", err);
            this._logger.log("startCamera: err: ", err);
            reject(err);
          });
```

I want to set the flash mode on by default when the camera starts but it always take auto by default. If I have another button to toggle the flash mode, then it goes to off and if I toggle again it would go to on state. But it never goes to on mode by default on camera start. Am I missing something here or is it an issue?'

Even though I set the flash mode, the success callback will still give older flash state.

**Comment by immnk** [comment]
I fixed this giving a timeout in the then callback.

**Comment by Choppel** [comment]
@immnk 
Hi,
glad to hear you got it to work.
Could you please close this ticket then.
Thanks in advance.

regards Choppel
