### ISSUE TITLE
How to get image of actual max resolution supported by phone's camera  ?

### ISSUE THREAD

**Issue by Ekta09** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#37]
I want accuracy at pixel level in captured picture resolution. How can I get the actual picture captured by phone according to its maximum Camera Angle Field Of View( CAFOV) ? 
I tried to get origionalPicture the existing functionality in plugin, but it doesn't seem to give me picture of original resolution. 
I am passing null argument in takePicture() method to allow camera to capture original supported resolution by device camera. But isn't giving me result as expected. Any other ways to solve it ?

**Comment by RealBrubru** [comment]
Hi @Ekta09, I have the same question! Did you find a way to managed it?

**Comment by proxsys** [comment]
I have the same issue.

The resolution and stretching of the image are making this plugin unusable for my intended application.

Has anyone obtained a better rez and non-stretched image?

Thanks!

**Comment by erperejildo** [comment]
If you want to use your native resolution don't specify any size when starting the camera
