### ISSUE TITLE
camera preview is not same as IOS its blurry

### ISSUE THREAD

**Issue by sumit-youngdecade** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#371]
Hello i found a bug while application development on IOS.Camera preview is diffrent as original .Its not open as quality preview.Please give me solution for hd preview on ios.

**Comment by Choppel** [comment]
Hi sumit-youngdecade,
is this always the case? If so, what device are you using exactly?
I have this problem sometimes but not very often and it is always temporary.

regards Choppel
