### ISSUE TITLE
Adding more arguments with invokeTakePicture

### ISSUE THREAD

**Issue by shubham14896** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#372]
CameraPreview.takePicture({ width: 640, height: 640, quality: 80, type: 1 }, function(pictureSource) {}, function(error) { alert(error) });

~ as i have added a type parameter along with (width,height,quality), so in the xcode its pointing array out of index exceptions in the function call.
~ refernce : (CGFloat)[command.arguments[3] floatValue];

Error : webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndexedSubscript:]: index 3 beyond bounds [0 .. 2]

**Comment by Choppel** [comment]
Hi shubham14896,
the key "type" is not documented. What do you expect to happen when you use it?

Looking at the code given I assume that ObjectiveC translates the javascript object to an array of fixed length. So maybe setting "command.arguments[3] floatValue" to "command.arguments[4] floatValue" could work.

regards Choppel
