### ISSUE TITLE
App crashes on back button

### ISSUE THREAD

**Issue by kdomagoj** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#373]
When back button is pressed (android 7) app crashes:

 java.lang.RuntimeException: Camera is being used after Camera.release() was called

It doesn't reach Cordova onBackButton callback

**Comment by kdomagoj** [comment]
I've downgraded plugin to latest released (0.9.0) and everything works ok.

**Comment by m-menon** [comment]
Add the below(onBackButton) before startCamera. For example
```
CameraPreview.onBackButton(function() {
	CameraPreview.stopCamera();
});
// Now your startCamera
CameraPreview.startCamera(options);
```

**Comment by kdomagoj** [comment]
This is not solution.. It is natural to have some workflow ( involving back button to go back) while camera is active, some setup/options dialog, for example. 
I have read that , that funcionality is intended for some old devices , so I guess it should be optional.

**Comment by m-menon** [comment]
@kdomagoj , yup it isn't a solution but but many ppl may miss the onBackbutton behavior and so the app will end up crashing - just like I missed it :) By handling the backbutton event, at least some folks may be able to prevent the crash. Cheers

**Comment by Choppel** [comment]
@m-menon @kdomagoj 
Hi,
because IMO the onBackButton function should not be part of this plugin, because it's not what the plugin is for, I'd advise you to use the standard cordova backbutton callback. http://cordova.apache.org/docs/en/7.x/cordova/events/events.html#backbutton
Inside the callback you can check if the camera preview is shown and then stop the camera. Or do something else instead.

regards Choppel

**Comment by westonganger** [comment]
@Choppel if you believe this should not be a part of the plugin then please create a PR to remove it.

**Comment by m-menon** [comment]
@Choppel 

hi,

It could be both a yes and a no :) For now the way I handle it is this way
In the beginning I attach a certain event handler to the backbutton ...
Then before calling the camera start, I remove that event handler ... and use the camera's onbackbutton event handler, from then on. Upon closing the camera, I "reattach" the earlier event handler ( in the camera -> stop -> success event callback) . Far from perfect but it has worked well for me so far. Cheers

**Comment by Choppel** [comment]
@m-menon 
Why not setting a global flag like "isCameraRunning" after starting the camera. Inside the cordova 'backbutton' event you look if this flag is set and then stop the camera (and unset isCameraRunning) or, if it's not set, execute the other code.
Then you wouldn't need the camera-preview's onbackbutton event and only one event handler.

**Comment by m-menon** [comment]
It's been a while since I visited that code but I kinda remember that without the camera-preview's onbackbutton event handler, the app used to crash ( at least on a few devices ). I remember having tried a number of permutations and combinations, including the flag trick :)

**Comment by kdomagoj** [comment]
Does camera need to be stopped in CameraPreview.onBackButton?

**Comment by m-menon** [comment]
Had a quick glance and here's what I did
I have a backevent handler called fnHandleBackbutton. In the beginning ( when the camera is not operating I have it attached to the cordova backbutton event. Then before calling the startCamera method I do a removeEventListener on the Cordova backbutton event ... and then use the fnHandleBackbutton inside of the onBackButton. When I am done with the Camera, I simply add back the fnHandleBackbutton using addeventhandler. Btw I don't stop the camera in the CameraPreview.onBackButton but I do hide the camera. I remember that stopping the camera again (through onBackbutton ) resulted in some crashes.

**Comment by kdomagoj** [comment]
@m-menon @westonganger @Choppel 

I don't have IOS device...
After browsing code herre on github and 0.9.0 version I use
I think that the problem is in `src/android/CameraPreview.java` :

```
public void onBackButton() {
    Log.d(TAG, "Back button tapped, notifying");
    PluginResult pluginResult = new PluginResult(PluginResult.Status.OK, "Back button pressed");
    tapBackButtonContext.sendPluginResult(pluginResult);
  }

```
Should be: 
```

public void onBackButton() {
    if(tapBackButtonContext == null) {
          return;
    }
    Log.d(TAG, "Back button tapped, notifying");
    PluginResult pluginResult = new PluginResult(PluginResult.Status.OK, "Back button pressed");
    tapBackButtonContext.sendPluginResult(pluginResult);
  }

```
Simply not to call callback if it's not defined.
Old devices shold work, new devices shold work...

This is where it gets called in `src/android/CameraActivity.java`
```
 frameContainerLayout.setOnKeyListener( new android.view.View.OnKeyListener() {
            @Override
            public boolean onKey( android.view.View v, int keyCode, android.view.KeyEvent event ) {

              if( keyCode == android.view.KeyEvent.KEYCODE_BACK )
              {
                eventListener.onBackButton();
                return true;
              }
              return false;
            }
          });

```

I don't know for IOS version...

**Comment by kdomagoj** [comment]
@m-menon @westonganger @Choppel
I have created PR (Android only)

I hope it is OK (tested on myproject/devices)
