### ISSUE TITLE
lookWidth != imageWidth AND lookHeight != imageHeight.

### ISSUE THREAD

**Issue by eccainiao** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#379]
toBack = true，width = 200  ,height = 200。lookwidth = 200,lookHeight = 200;
But  imgWidth = 320,imgHeight = 560.  （Part of the equipment）

**Comment by Choppel** [comment]
Hi eccainiao,
there is nothing in the docs about lookWidth or lookHeight. Are you sure you are at the correct plugin page?
Also your question is very vague. What is the actual problem?

regards Choppel
