### ISSUE TITLE
Detect when Camera Started

### ISSUE THREAD

**Issue by m-menon** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#38]
hi,

Is it possible to detect when the camera is ready (for taking a picture)? What I want to do is to trigger an event when the camera is ready / initialized.  I am pretty new to java / js, and I know it is kinda something simple I'd need to fit in somewhere to fire the camerapreview ready.

And also is it possible to add in a picture quality parameter?

Thanks a ton,
M&M

**Comment by ricardokrieg** [comment]
+1 for this

I would like to show a loading page while the camera isn't ready.

**Comment by erperejildo** [comment]
Not sure if I understood the question but the only thing you have to check if is Cordova/phone is ready, startCamera and takePicture

**Comment by m-menon** [comment]
hi,

Say I have a page with a button to start the camera preview plugin. Once I call the startpreview method it takes a little amount of time for the camera to initialise - and this seems to depend on the device itself. So I was wondering if there is an event that fires when the camera has been initialised and ready for snapping the picture. What I would want to do then is to snap a picture. Hope that explains it - Cheers - M&M

**Comment by erperejildo** [comment]
Hmm... haven't faced problems related with this. Could you try creating a callback in the startpreview function?

**Comment by m-menon** [comment]
hi,

I think I did try that earlier. I am a littles less acquainted with the cordova and stuff so I am not sure if I didn't do it right but I do remember having tried a callback and it didn't fire. Any pointers will be greatly help. Thanks once again

**Comment by erperejildo** [comment]
Well, for this the only thing you need I think is js so maybe doing something like this:
```
CameraPreview.startCamera({
      x: 0,
      y: window.innerHeight/2 - window.innerWidth/2,
      width: thatPhoto.windowWidth,
      height: thatPhoto.windowWidth,
      camera: "back",
      tapPhoto: false,
      previewDrag: false,
      toBack: false
    }, function(callback) {
       // do something
});
```
And in www/CameraPreview.js something like:
```
CameraPreview.startCamera = function(options,onSuccess, onError, callback){
// ...at the end

f (typeof callback === "function") {
    // Call it, since we have confirmed it is callable​
        callback(onSuccess);
    }
```
That should work (haven't try sorry, I'm at work)

**Comment by m-menon** [comment]
Cool. Thanks a ton. I will test and update on the outcome :+1:  Cheers - M&M

**Comment by westonganger** [comment]
There are success callbacks on everything in master now. Closing
