### ISSUE TITLE
CameraPreview is always undefined

### ISSUE THREAD

**Issue by Pakkes** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#380]
Hi,

I tried to get your plugin to work without success.
All tries to reference the CameraPreview object fail.
I tried
CameraPreview
window.CameraPreview
window.plugin.CameraPreview
Cordova.plugins.CameraPreview
and I tried to get the reference AFTER the onDeviceReady has fired.

Of course I well referenced the plugin on the config.xml file ... and I can observe that Phonegap Desktop downloads all files from your package (under plugins/cordova-plugin-camera-preview directory).
However I cannot access the CameraPreview, neither on Android or iOS.

Is there something I missed or something I need to do in order to get this working?

Regards

**Comment by Choppel** [comment]
Hi Pakkes,
CameraPreview and window.CameraPreview are basically the same and should work. If not, the plugin is not correctly included.

Create a new cordova app and add cordova-plugin-camera-preview like so
```
cordova create hello com.example.hello HelloWorld
cd hello
cordova plugin add cordova-plugin-camera-preview
cordova platform add android
```
and replace everything inside the js/index.js with the following source code
```javascript
document.addEventListener('deviceready', function() {
    CameraPreview.startCamera({}, function() {
        alert('camera started succesfully');
    }, function(_error) {
        alert('camera could not be started. ' + _error);
    });
}, false);
```
then run
```
cordova run android
```

Your phone should start the app and alert 'camera started succesfully'

regards Choppel
