### ISSUE TITLE
cordova camera plugin issue with FILE_URI

### ISSUE THREAD

**Issue by riteshnus** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#382]
I am using IONIC 3.7.0 in my current project. In one requirement I need to use cordova camera plugin to take photo uri from image gallery. Every time when I am trying to get the URI , I get the data_uri instead of File_uri. I only need the file_uri of image to go further. Please suggest.

**Comment by Choppel** [comment]
Hi riteshnus,
I think you could be at the wrong plugin page. This is the plugin cordova-plugin-camera-preview, not cordova-plugin-camera.

Please have a look at [(https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/#take-a-picture-)]

There is an option to the function takePhoto 
```javascript
destinationType: Camera.DestinationType.FILE_URI
```
which might be what you are looking for.

regards Choppel

**Comment by Choppel** [comment]
@riteshnus 
Please close this issue if it is resolved.
