### ISSUE TITLE
Image Resolution is low n blurry

### ISSUE THREAD

**Issue by odoyie** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#385]
Hi tried to use this plugin on Android,
i manage to take a Pictures but the resolution is really bad, the picture taken kinda blurry, 
I change the quality, width n height but no luck,

Any ideas?

Thanks & Regards,
Ari

**Comment by odoyie** [comment]
Anyone?

**Comment by ngt14** [comment]
+1 same problem

**Comment by ngt14** [comment]
You can use function of plugin 'CameraPreview.getSupportedPictureSizes' to get the last bigger height and width of your camera and fill this height and width on function takepicture

**Comment by odoyie** [comment]
thank you...
