### ISSUE TITLE
Has Zoom in zoom out feature added for IOS

### ISSUE THREAD

**Issue by suranavarun** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#387]
Hi, has the zoom in-out feature added for iOS also like how it is there for Android.

**Comment by Choppel** [comment]
Hi suranavarun,
although I don't exactly understand the question I assume it's about zooming.
This is supported in iOS and Android by the functions setZoom, getZoom and getMaxZoom. Just get the maxZoom for the currently used camera (front or back) and provide a way of setting the zoom level (e.g. an html slider element from 0 to maxZoom).

Getting the zoom to work with a pinch gesture can be accomplished by using hammer.js or a similar library.

regards Choppel

**Comment by suranavarun** [comment]
Thank you chopper..

Actually in the description of setzoom functionality it was mentioned that the feature works only for android, that's why wanted to know if it has been implemented for iOS or not.

**Comment by suranavarun** [comment]
Sorry choppel*
