### ISSUE TITLE
Can i get two or more camera screen?

### ISSUE THREAD

**Issue by wilybear** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#390]
hello, i'm learning cordova recently.
i want to make cammera app and i found your plugin.
How can i get two or more camera screen?
i'm looking forward for your help :D

**Comment by Choppel** [comment]
Hi wilybear,
as far as I know it is not possible for an app to get the input of multiple cameras at once (e.g. front and back at the same time). The documentation of iOS and Android don't mention anything like this and I never heard of it.

Showing the input of one camera in two separate preview windows could be possible but this plugin does not support it at the time.

Let me ask you. What are you trying to achieve in the first place? Maybe there is another possible approach.

regards Choppel

**Comment by westonganger** [comment]
As @Choppel said at this time it is not possible for an app to get the input of multiple cameras at once. Closing.
