### ISSUE TITLE
Autostart preview after take picture

### ISSUE THREAD

**Issue by PicklesAU** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#391]
Hi, 

I tried to implement this plugin, i want after take picture, the preveiw not re-start,
on android i can comment out the mCamera.startPreview(); on jpegPictureCallback function.
How can I do this on iOS ?

thank you

**Comment by Choppel** [comment]
@PicklesAU 
Hi,
you want to take one picture and then stop the preview? Just call stopCamera inside the takePicture success callback. Theres no need to change any source code of the plugin.

regards Choppel

**Comment by PicklesAU** [comment]
thank you @Choppel
