### ISSUE TITLE
Feature request: check and adjust contrast/brightness of taken picture

### ISSUE THREAD

**Issue by Lenndev** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#398]
Hi is it possible or an option to add a feature to check and adjust the brightness and contrast of a taken picture? 
or does anyone know a different plugin that makes it possible to check/adjust the brightness and contrast of a picture (ie. using a histogram)

**Comment by Choppel** [comment]
@Lenndev 
http://camanjs.com/

It's a JS canvas manipulation library including contrast and brightness etc. Haven't tested it though.

**Comment by westonganger** [comment]
Edits can be performed after the photo is taken using any JS plugin. Closing.
