### ISSUE TITLE
Minimum version

### ISSUE THREAD

**Issue by luispimenta** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#402]
What is the minimum version that the plugin should work for ios?

I'm testing on ipad version 9.3.5 model mx916ll / a and it did not work :(

**Comment by Bengejd** [comment]
@luispimenta what do you mean it did not work? The plugin can be a bit finicky to get up and running due to background-transparencies that are necessary, but once you fix that, everything should work perfectly.

**Comment by luispimenta** [comment]
Hi. I updated the ipad version and it worked, tks!
