### ISSUE TITLE
TakePicture with Front camera crashes app in Android

### ISSUE THREAD

**Issue by Chillamag** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#406]
I can take a picture fine with the Rear camera, and switch cameras and preview the front as well, but when I take a picture with the Front camera, the app crashes.. 

![image](https://user-images.githubusercontent.com/9051774/34436605-9311b182-ec97-11e7-9c6a-b09ae57f80aa.png)

**Comment by Choppel** [comment]
@Chillamag 
What device are you using and could you please post some source code?

**Comment by Choppel** [comment]
@Chillamag 
Is this still an issue? If not, please close it.
