### ISSUE TITLE
Samsung S6 small view of camara

### ISSUE THREAD

**Issue by adanreyes18** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#41]
Hi, I have been using a cell samsumg S6 and when opening the camera gives me a little screen of the camera that is not respect the size you assign can help me solve it.
In the line: var rect = {x: 100, y: 100, width: 200, height: 200}; assign values to get the width and height of the screen "$ (window) .width (), $ (window) .height ()".
The measures are right but the box is very small.
We are in contact
![20150529111144](https://cloud.githubusercontent.com/assets/11559443/7889306/5b08eb74-0604-11e5-97bf-10b31293eb53.jpg)
![20150529111147](https://cloud.githubusercontent.com/assets/11559443/7889305/5b08bb4a-0604-11e5-8643-40b76fe3ce3e.jpg)

**Comment by arturopn** [comment]
Hi, i have the same exact issue ... i have tried everything, this only happens on samsung, is there any workaround?
