### ISSUE TITLE
How to get rid of the confirmation dialogue (save/discard) after taking each picture with this plugin?

### ISSUE THREAD

**Issue by blue2609** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#411]
I just want to know if it's possible to get rid of the **save/discard** dialogue with this plugin. It's very annoying when I'm trying to make the app I'm currently developing to take multiple pictures as fast as possible. 

Thanks in advance~ 

EDIT:

IT WORKS!!! This plugin is perfect for anyone out there who's trying to make app that can take multiple pictures in one single session

**Comment by blue2609** [comment]
To anyone out there who's following this thread, OMG this plugin is awesome. It actually allows you to take multiple pictures without having the save/discard confirmation dialogue. IT WORKS!

**Comment by Choppel** [comment]
I believe @westonganger is glad to hear that.
Please close this issue.
