### ISSUE TITLE
QrCodeScan + Codova-camera-plugin can't run

### ISSUE THREAD

**Issue by MLSTAR23** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#416]
Hello Best developers.
I can't use QrCodeScan plugin with Cordova-Camera-Plugin to custom preview page.
Please fix this issue

**Comment by Choppel** [comment]
Please post more info on the error or post a link to the exact QR code plugin you are using and I will have a look at it.

**Comment by andersborgabiro** [comment]
Just interested: What plugin is that? cordova-plugin-qrscanner?

I use phonegap-plugin-barcodescanner, that has a nice set of options: torch, camera flip etc.

**Comment by Choppel** [comment]
@MLSTAR23 
Is this still an issue for you? If not, please close it.
