### ISSUE TITLE
Is that possible to disable camera in ionic ?

### ISSUE THREAD

**Issue by LimWeiHan** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#417]
I tried use CameraPreview.StopCamera() to disable camera for capturing but no luck ? is that the right function i am referring to ?

**Comment by Choppel** [comment]
The function **s**topCamera stops the camera preview. But only if it was started beforehand.

If you want to disable the camera so the user cannot take pictures at all - this plugin does not do that.

**Comment by danhab99** [comment]
@Choppel do you know a different way.. in general

**Comment by Choppel** [comment]
@danhab99 
Sorry, no.

**Comment by Choppel** [comment]
@LimWeiHan 
Please close this issue.
