### ISSUE TITLE
Please help: Getting error "Cordova CameraPreview plugin not installed" in ionic project

### ISSUE THREAD

**Issue by afficionaddo** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#418]
Bug Report:

Current behavior:

I installed camera-preview plugin. Everything is latest in terms of ionic, cordova etc.
I am testing the plugin using 'ionic-dev app' on a android device.
When I call the "startCamera()", I get the error 'plugin not installed'.

Other information:

I have verified the plugin installation multiple times but still get the error

IONIC Info:

cli packages: 

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.1
    npm  : 5.5.1
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by Choppel** [comment]
The angular implementation of this plugin is not part of this project. See #96
Please refer to the angular documentation (https://ionicframework.com/docs/native/camera-preview/) and close this issue.
