### ISSUE TITLE
toBack option not working in Android

### ISSUE THREAD

**Issue by wookiecookie87** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#419]
I am working on Ionic2 app with camera-preview cordova plugin.

I want to have a circular button on the camera view.
So, I have set 'toBack' option to true so that camera view would get behind of the HTML of the page.
But toBack option doesn't seem to work.   It was working before, but at some point, it stopped working.

It works fine on iOS.  Is it possible that this is some kind of bug in the updated version or compatibility issue?

ionic version: 3.19.1
ionic-native/camera-preview : ^4.3.2
cordova-plugin-camera-preview:  ^0.9.0

     this.platform.ready().then(()=> {
        const cameraPreviewOptions : CameraPreviewOptions= {
            x: 0,
            y: 0,
            width: window.screen.width,
            height: window.screen.height,
            camera: 'rear',
            tapPhoto: false,
            previewDrag: false,
            toBack: true
        }

        this.cameraPreview.startCamera(cameraPreviewOptions).then(
            (res) => {
                console.log(res)
            },
            (err) => {
                console.error(err)
            });
    })

**Comment by brittonk** [comment]
Just at a glance, I'm not sure 'rear' is an option and that might kill the remaining parameters. Try this and see if it fixes your issue:

` this.platform.ready().then(()=> {
    const cameraPreviewOptions : CameraPreviewOptions= {
        x: 0,
        y: 0,
        width: window.screen.width,
        height: window.screen.height,
        camera: CameraPreview.CAMERA_DIRECTION.BACK,
        tapPhoto: false,
        previewDrag: false,
        toBack: true
    }`

**Comment by wookiecookie87** [comment]
@brittonk 
Thank you for your suggestion, but I tried it, and it didn't make any difference.

**Comment by nerothe** [comment]
Same problem here

**Comment by vienom** [comment]
Here too. Maybe a problem with cordova 8.0.0? The option worked for me before.

**Comment by wookiecookie87** [comment]
@vienom  Yes. The options worked for me before too.  But my cordova version is 7.1.0

**Comment by andersborgabiro** [comment]
Is background color set to transparent? I set it for both html and body.

My settings:
```
    CameraPreview.startCamera({
        x: 0,
        y: 0,
        width: window.innerWidth,
        height: window.innerHeight,
        camera: frontOn ? CameraPreview.CAMERA_DIRECTION.FRONT : CameraPreview.CAMERA_DIRECTION.BACK,
        toBack: true,
        tapPhoto: true,
        tapFocus: false,
        previewDrag: false
    });
```

**Comment by vienom** [comment]
Html and body are transparent, but the camera view is in front of the the webview. Does your configuration work on Android?

**Comment by andersborgabiro** [comment]
Yup, on both.

![screenshot_20180225-183602 s](https://user-images.githubusercontent.com/1548064/36663889-43f5f688-1ae3-11e8-913b-e42eeb5fa909.png)

**Comment by vienom** [comment]
I tried it with phonegap build, but got the same problem there. Which cli version do you use on phonegap build?

**Comment by andersborgabiro** [comment]
8.0.0

Tested on Android 7.0 and 6.0.

My plugins:

```
    <plugin name="cordova-plugin-whitelist"/>
    <plugin name="cordova-plugin-device"/>
    <plugin name="cordova-plugin-statusbar"/>
    <plugin name="cordova-plugin-dialogs"/>
    <plugin name="cordova-plugin-splashscreen"/>
    <plugin name="cordova-plugin-globalization"/>
    <plugin name="cordova-plugin-tts"/>
    <plugin name="cordova-plugin-camera-preview"/>
```

Some of my CSS:

```
html, body {
    background-color: transparent;
}

body, div, table, tr, th, td, thead, tbody, span, p, ul, ol, li, input, textarea, img {
    box-sizing: border-box;
}

body {
    margin: 0em;
    padding: 0em;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 1.2rem;
}
```

**Comment by vienom** [comment]
Seems like a plugin problem. Just started a testproject, where the camera preview plugin worked as expected. Adding plugin per plugin I figured out the cordova-plugin-googlemaps is causing the problem.

**Comment by vienom** [comment]
Here is a solution: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/369

**Comment by wookiecookie87** [comment]
@vienom Thank you so much for your effort and help!  Without you, I wouldn't have solved this issue.  You are the best.

**Comment by vienom** [comment]
No problem. By the way I ended up using just the javascript sdk for google maps. Works fine too.
