### ISSUE TITLE
ionic 2 stopCamera(); too slow

### ISSUE THREAD

**Issue by jorgemejia** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#420]
I´am using ionic 2 and I have a page where I open the camera preview for AR locations, the problem is when I go back to the main page I use the next code for stops the camera preview.

```
ionViewDidLeave(){
      this.cameraPreview.stopCamera().then(_=>{
          //this._accelerometerService.stopAccelerometer();
          //this._compassService.stopCompass();
          //this._geolocationService.stopGeolocation();
      });
  }
```

But it takes a lot of time to stop the camera, this affects the main view because I can´t interact with  until the camera stops.

**Comment by ogezue** [comment]
reason for this is discussed here:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/421

**Comment by westonganger** [comment]
Solved via https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/422
