### ISSUE TITLE
threading warnings iOS

### ISSUE THREAD

**Issue by ogezue** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#421]
If I inspect the console on iOS I see several warnings from iOS that the threads are not used correctly:

THREAD WARNING: ['CameraPreview'] took '104.767334' ms. Plugin should use a background thread. 

AND

Main Thread Checker: UI API called on a background thread: -[UIView frame]

Has somebody investigated in this here? 

I'm using the current version of the demo app.

**Comment by ogezue** [comment]
After profiling the XCode project I think this is the reason why the camera is so slow. Several calls are made on the wrong thread and the current version of XCode is making clear where this happens.

Work should focus on this to improve performance and stability.

**Comment by ogezue** [comment]
One first attempt of improvement is to change the stopCamera method.

```
- (void) stopCamera:(CDVInvokedUrlCommand*)command {
    
     NSLog(@"stopCamera");
    
    [self.cameraRenderController.view removeFromSuperview];
    [self.cameraRenderController removeFromParentViewController];
    self.cameraRenderController = nil;
    
    [self.commandDelegate runInBackground:^{
     
      CDVPluginResult *pluginResult;
      if(self.sessionManager != nil) {

        [self.sessionManager.session stopRunning];
          self.sessionManager = nil;
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
      }
      else {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Camera not started"];
      }

      [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
     }];
}
```
With this there is no delay when stopping the camera and returning to parent view. But camera is not available if you want to take another photo directly after returning

**Comment by ogezue** [comment]
I think I solved it. Camera returns immediately and is immediately available on return.
There are still thread warnings which should be solved.

 Please see the folowing solution:

`- (void) stopCamera:(CDVInvokedUrlCommand*)command {
    
    NSLog(@"stopCamera");
    
    [self.cameraRenderController.view removeFromSuperview];
    [self.cameraRenderController removeFromParentViewController];
    self.cameraRenderController = nil;
    
    [self.commandDelegate runInBackground:^{
     
      CDVPluginResult *pluginResult;
      if(self.sessionManager != nil) {

          for(AVCaptureInput *input in self.sessionManager.session.inputs) {
              [self.sessionManager.session removeInput:input];
          }
          
          for(AVCaptureOutput *output in self.sessionManager.session.outputs) {
              [self.sessionManager.session removeOutput:output];
          }
          
        [self.sessionManager.session stopRunning];
        self.sessionManager = nil;
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
      }
      else {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Camera not started"];
      }

      [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
     }];
}`

**Comment by ogezue** [comment]
I created a pull request for this: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/422

**Comment by jorgemejia** [comment]
Well this works fine, thanks a lot @ogezue 👍
