### ISSUE TITLE
Not capturing photo without user intent

### ISSUE THREAD

**Issue by loubrevetti** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#426]
I have read in numerous post apparently this plugin has the capability to capture a photo without any user intent or interaction. preview loads to screen but I must set the "tapPhoto" within the camera config to true I am looking for the solution to set to false and have plugin just capture automatically

**Comment by Choppel** [comment]
Run this in a console
````
cordova create hello com.example.hello HelloWorld
cd hello
cordova plugin add cordova-plugin-camera-preview
cordova platform add android
````
then replace everything in index.js with the following code
````
document.addEventListener('deviceready', function() {

    let options = {
      camera: CameraPreview.CAMERA_DIRECTION.BACK,
      toBack: true
    };

    CameraPreview.startCamera(options, function() {
        setInterval(function() {
            CameraPreview.takePicture(function(base64PictureData) {
                var img = document.createElement("IMG");
                img.setAttribute("src", "data:image/gif;base64," + base64PictureData);
                img.setAttribute("height", 100);
                img.setAttribute("width", 100);
                document.body.appendChild(img); 
            });
        }, 5000);
    });
}, false);
````
and run this in the console
````
cordova run android
````

This code starts the camera preview for the backfacing camera behind the DOM ("invisible to the user"), takes a picture every 5 seconds and adds this picture as a 100x100 img to the dom.
