### ISSUE TITLE
Typescript does not find CameraPreview object

### ISSUE THREAD

**Issue by Konkrad** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#429]
I use this plugin with cordova and angular. My problem is that typescript does not recognize the global object CameraPreview. Only when changing the declaration in the following way in the typescript file the compiler accepts it.

```typescript
declare var CameraPreview: CameraPreview
```

Is this a missing line in the typescript file or do I use the types in the wrong way?

**Comment by Choppel** [comment]
The angular implementation of this plugin is not part of this project. See #96 
Please refer to the angular documentation (https://ionicframework.com/docs/native/camera-preview/) and close this issue.
