### ISSUE TITLE
CameraPreview.switchCamera() function called twice

### ISSUE THREAD

**Issue by vijeth-ag** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#430]

**Comment by vijeth-ag** [comment]
This is my controller
`.controller('DashCtrl', function($scope) {

  $scope.startCam = function(){
    $scope.camInstance = CameraPreview.startCamera({x: 50, y: 50, width: 300, height: 300, toBack: false, previewDrag: true, tapPhoto: true});
  }

  $scope.swapCam = function(){
    console.log('swapping');
    CameraPreview.switchCamera();
  }

})`

This is my html
`<ion-view view-title="Dashboard">
  <ion-content class="padding">
      <button ng-click="startCam()">Start Cam</button>
      <button ng-click="swapCam()">Swap Cam</button>
  </ion-content>
</ion-view>`

When I click startCam and try to swap, the swapCam function gets called twice.
I can see the console.log('swapping'); printing twice. 

Im confused as to how could the method tied to ng-click get called twice.
Have tested without CameraPreview.switchCamera(); method in it, gets called once.

Appreciate any help. Thanks

**Comment by Choppel** [comment]
Maybe the clicks don't work as expected. Put a "console.log" in startCam and see if startCam gets called after switchCamera was called. If so, theres a bug in your button event handling. Try "return false" at the end of both functions to stop processing of dom event handling.

**Comment by vijeth-ag** [comment]
Thanks for the reply @Choppel. No the startCam is not getting called on swapCam. And the return false did not help.

really strange how the line CameraPreview.switchCamera(); from the cordova plugin can call its function in the controller

For now have fixed like this
`
  $scope.enableSwapF = function(){
    $scope.enableSwap = true;
  }

  $scope.swapCam = function(){
    if($scope.enableSwap == false){
      return;
    }
    $scope.enableSwap = false;
    setTimeout($scope.enableSwapF, 1000);
    CameraPreview.switchCamera();
  }
`

**Comment by Choppel** [comment]
Maybe you can find the solution when evaluating the promises returned by switchCamera(). But otherwise I don't know what it could be. In a simple plain cordova app everything works fine so I suspect there is something about the ionic controller thats odd.

**Comment by andersborgabiro** [comment]
You shouldn't need enableSwap.

I use it directly via an onclick and don't have that problem, so it seems related to the triggered event.

**Comment by vijeth-ag** [comment]
@Choppel Yes I have had a look at Cordova Camera Preview Sample app, it works fine, its happening only with Ionic. 

The swicthCamera() is not a promise returning function.

I checked the success and error callbacks, it did not help,(Not error callback at all)
Even by seeing the breakpoints I could see the whole function calling again with SwitchCamera(). 
Very strange.

@andersborgabiro Are you using the camera preview plugin with Ionic or Just cordova. It seems this issue is seen with Ionic. and not with Just cordova app.

Thanks

**Comment by andersborgabiro** [comment]
Just Cordova.

**Comment by Choppel** [comment]
Hi @vijeth-ag 
if it is a problem with ionic then please open up a ticket at their support page and close this issue.
Thanks.

**Comment by vijeth-ag** [comment]
Yes Will do. Thanks
