### ISSUE TITLE
Camera Preview covers the body

### ISSUE THREAD

**Issue by johnroper100** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#434]
I have been working on a project for about a month now and the camera preview has been working with `toBack:true` as it should. However, it just started covering up my body so I can't see my buttons anymore.

These are my camera options:

```
const cameraPreviewOpts: CameraPreviewOptions = {
      x: 0,
      y: 0,
      width: window.innerWidth,
      height: window.innerHeight,
      camera: 'rear',
      tapPhoto: false,
      tapToFocus: true,
      toBack: true
    };
    this.cameraPreview.startCamera(cameraPreviewOpts).then(
      (res) => {
        console.log(res);
      },
      (err) => {
        console.log(err);
      });
```

**Comment by Choppel** [comment]
Hi @johnroper100 
there were no updates of this plugin recently so I assume the problem is not in its source code.

Your code also looks right.

Are you using ionic or another framework? Then you should look at their issue tracker, maybe they had an update causes this problem.

**Comment by johnroper100** [comment]
It turns out that it was the con.teleric.native-page-transitions plugin that was causing the issue. I don't know why. I wasn't using the plugin but as soon as I fully removed it from the project, the issue went away.
