### ISSUE TITLE
takePicture function does nothing, no error, no success

### ISSUE THREAD

**Issue by bsirmacek** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#438]
I call the following function with a button on my Android app. I can see the camera view, so the startCamera works. However, afterwards takePicture must make a photo automatically and save it to the camera roll. I cannot see imgData or error log. However, I can see my final log "photo is taken". 

It executes the takePicture function, however it doesn't give any success or error message and there is not any picture saved in the camera roll at the end. 

Can you please help with saving images to the camera roll automatically?

` function startImaging(){

	CameraPreview.startCamera({x: 0, y: 0, width: window.screen.width, height: window.screen.height, 
        camera: CameraPreview.CAMERA_DIRECTION.BACK, toBack: false, previewDrag: false, tapPhoto: 
        false, previewDrag:false, saveToCameraRoll: true, saveToPhotoAlbum: true});
	 
	CameraPreview.takePicture({x: 0, y: 0, width: window.screen.width, height: window.screen.height, 
        camera: CameraPreview.CAMERA_DIRECTION.BACK, toBack: false, previewDrag: false, tapPhoto: 
        false, previewDrag:false, saveToCameraRoll: true, saveToPhotoAlbum: true},function(imgData){
			console.log(imgData);
		}, function(error) {
			console.log(error);
		}); 

	 console.log('photo is taken');
 }`

**Comment by Choppel** [comment]
Hello again @bsirmacek 
so that's your actual code? As I suspected in #348 your code is completely wrong. It should be something like this (not tested).
````
CameraPreview.startCamera({
  x: 0,
  y: 0,
  width: window.screen.width,
  height: window.screen.height, 
  camera: CameraPreview.CAMERA_DIRECTION.BACK,
  toBack: false,
  previewDrag: false,
  tapPhoto: false
}, function() {
  console.log('camera started');

  CameraPreview.takePicture({
    quality: 95,
    height: 1080,
    width: 1920
  }, function(imgData) {
    console.log('got picture');

    console.log(imgData);
  }, function(error) {
    console.log('could not take picture. ' + error);
  }); 
}, function(error) {
  console.log('could not start camera. ' + error);
});
````
Please take a thorough look at the documentation next time.

**Comment by bsirmacek** [comment]
Thank you for your response. It is solved.
