### ISSUE TITLE
backbutton not firing , black flicker on startCamera and stopCamera

### ISSUE THREAD

**Issue by kdcro101** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#443]
cordova native backbutton event is not emitted (again?), something happened from my last PR when everything worked ok.

Some View flickering is happening (screen goes black ) when `startCamera` and `stopCamera` is executed which wasn't happening before ( tested 0.9.0 and version from Nov 29, 2017 [4c844ae]).

I've created PR for both issues:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/442

**Comment by westonganger** [comment]
Merged.
