### ISSUE TITLE
Is it possible to show buttons and custom html popup using this plugin

### ISSUE THREAD

**Issue by Gamerakki** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#446]
Hi,

Fristly thank you for such an good plugin. I am building an app in which user will click the photo and without exiting the camera view an html pop up should come which will have some data. Is it possible or there are any tweaks that i can do in the plugin to get this feature

**Comment by kdcro101** [comment]
Yes it is possible. Check option toBack:true

`toBack - Defaults to false - Set to true if you want your html in front of your preview`

**Comment by Gamerakki** [comment]
Hi 
i tried but still my html is going behind the preview
