### ISSUE TITLE
Managing the plugin lifecycle

### ISSUE THREAD

**Issue by waitopiggu** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#450]
I have been battling with this for the past few days without success.

My initial approach was to start and stop the camera when entering and leaving the view. This works very well on Android, but on iOS it can take up to 10 seconds for the `stopPreview()` success callback. 

Taking a series of pictures is difficult, because the camera obviously can't start again while still in the process of stopping. I can either wait for the success callback before leaving the view or leave immediately and risk the camera failing to start when re-entering the view.

Issue #20 suggests this problem is solved, but not if you depend on the callback.

My second approach was to start the preview once and use `show()` and `hide()`. As far as I can tell, this leaves the camera running in the background, which will have an effect on performance/battery.

Is there is a better/recommended way of handling this?

**Comment by KiwiKilian** [comment]
This is still a problem with the latest Release v0.10.0. Stopping takes sometimes just 1 second and another time it takes 10 seconds. @waitopiggu did you find any workaround?

**Comment by waitopiggu** [comment]
@KiwiKilian My solution was switching the project to React-Native. Deadlines and such...

**Comment by KiwiKilian** [comment]
My workaround is a service that keeps track of the state of the camera.

**Comment by jbotte** [comment]
any updates on this? as of now it looks like ill just have to keep the camera on.. not great :/
