### ISSUE TITLE
ToBack=true option doesn't work

### ISSUE THREAD

**Issue by muttineni2020** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#451]
ToBack=true option doesn't work. I have tried multiple options. below one is suggested in one of the forums,

 final ViewGroup webViewRoot = ((ViewGroup)webView.getView().getParent().getParent());
 webViewRoot.setBackgroundColor(0x00000000);
 webViewRoot.bringToFront();

Still it is not working.

Can any body help me on this.

**Comment by kdcro101** [comment]
@muttineni2020 ,

What do you mean by not working?

- Camera preview is not showing?
- some other functionality not working as expected?

Try to manually set  `background-color: transparent` to `html` element, using Chrome developlement tools while debugging your cordova app. Camera preview should be visible.

I work every day using latest commit in `toBack: true` mode. Everything works ok on following android versions: 

- 5.1
- 6.0.1 
- 7.0

**Comment by muttineni2020** [comment]
I have applied background-color: transparent to html element and infact i have tried below logic, suggested in github forum,

final ViewGroup webViewRoot = ((ViewGroup)webView.getView().getParent().getParent());
webViewRoot.setBackgroundColor(0x00000000);
webViewRoot.bringToFront();

none of the solutions were working. 

If i set toBack: false, camera preview is showing in my app. But i would like to add my custom html on camera preview so i applied toBack:true and background-color: transparent to html element, then camera preview is not showing in my ionic app.

Any suggestions would be appreciated.

Thanks,

**Comment by muttineni2020** [comment]
I have a version 0.9.0.

I feel it is latest version. I have installed day before yesterday.

Thanks,

**Comment by johnroper100** [comment]
I have this same issue as well with both the npm version and the git (master) version.

**Comment by kdcro101** [comment]
@johnroper100 ,

What kind of problems are you having (more detail)?

- Your HTML overlay is showing but there is no camera preview under?
- camera preview is visible but there is no your HTML overlay?
- any errors thrown?

**Comment by johnroper100** [comment]
Exactly. The html is showing but the background is just white. It was
working and I just did another build and it stopped and started doing this ^

**Comment by kdcro101** [comment]
@muttineni2020,

NPM version (installed by command `cordova plugin add cordova-plugin-camera-preview`) is released on May 9, 2017  and it is 75 commits behind master (at moment).

When you install from master branch version is also 0.9.0 but code is much diffferent than NPM version.

Use NPM version, for start and try  https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app, just to make sure that your OS/Device combo works.

**Comment by kdcro101** [comment]
@johnroper100 ,

I guess you have problem with CSS.

From documentation: 

When setting the toBack to true, remember to add the style below on your app's HTML or body element:

```
html, body, .ion-app, .ion-content {
  background-color: transparent;
}


```

**Comment by johnroper100** [comment]
I know that it works for sure. It could be that other packages are
interfering somehow. I haven't added any new plugins, but I did update my
package versions:

"dependencies": {
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/camera-preview": "^4.7.0",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/geolocation": "^4.7.0",
    "@ionic-native/local-notifications": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "^4.7.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "7.1.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-badge": "^0.8.7",
    "cordova-plugin-camera-preview": "^0.9.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.2.0",
    "cordova-plugin-local-notification": "^0.9.0-beta.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-windows": "6.0.0",
    "firebase": "^4.12.1",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "moniker-native": "git+https://github.com/knyga/moniker-native.git",
    "rxjs": "5.5.8",
    "sw-toolbox": "3.6.0",
    "time-ago": "^0.2.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.8",
    "typescript": "2.8.1"
  },

**Comment by johnroper100** [comment]
I have that on my body.

**Comment by kdcro101** [comment]
@johnroper100 ,

Every element must have transparent background between body and your html overlay.

It is not enough to put body/html background to transparent. 
For example you can have absolute positioned DIV that covers whole viewport that is NOT transparent.

```
html, body, .ion-app, .ion-content {
  background-color: transparent;
}
```

This css style only sets transparent background to HTML and BODY elements. If some other elements are covering viewport, they should be transparent too.

**Comment by johnroper100** [comment]
i just did another build and now it is working again. I didn't change anything.

**Comment by kdcro101** [comment]
@johnroper100,

No problem, glad to hear it worked out ok.

**Comment by AlexMokin** [comment]
@muttineni2020 
Indeed code you posted works fine on my galaxy s7 but doesn't work on all devices. I ended up replacing code in the 274-276 [that lines](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/blob/4c844ae72abc207a2d650d969bd822fccaa09991/src/android/CameraPreview.java#L274-L276) with this code:

```Java
final ViewGroup webViewRoot = ((ViewGroup)webView.getView().getParent().getParent());
webView.getView().setBackgroundColor(0x00000000);
webViewRoot.setBackgroundColor(0x00000000);
webViewRoot.bringToFront();
```

P.S. npm version of the plugin works fine as is

Cordova 8.0.0
Cordova Android 6.4.0
Android 7.0

**Comment by muttineni2020** [comment]
Thank you for all your comments.. I am able to resolve this by suggested css classes as transparent background.

Now I have another issue after this fix.. 

1. I opened camera in another one of the ionic tabs 
2. I have taken picture and close the camera
3. Now seems all the background color is transparent, how do I change that white background.
Can anybody help me on this

**Comment by MonicaTanglu** [comment]
android :`ion-app.md {
  background-color: transparent;
}`
ios:'ion-app.ios {
  background-color: transparent;
}'

**Comment by spacesuitdiver** [comment]
This seems to still be an issue, not sure why it's closed? @westonganger can you share why?

**Comment by jaswinder-walia-onebcg** [comment]
@muttineni2020 did you get to solve your 3rd point problem? I am facing it too.
