### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by LuizTokuhara** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#454]
I am trying to install the plugin but it is throwing an error.
Using "ionic cordova plugin add cordova-plugin-camera-preview"
Anyone is getting the same error?

> Error: Failed to fetch plugin https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm ERR! path /Users/user/app-folder/node_modules/.staging/cordova-app-hello-world-b6990d2d/template_src/res/icon/windows-phone/icon-62-tile.png
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall utime
npm ERR! enoent ENOENT: no such file or directory, utime '/Users/user/app-folder/node_modules/.staging/cordova-app-hello-world-b6990d2d/template_src/res/icon/windows-phone/icon-62-tile.png'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v8.1.3
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/luizimac2/Library/Android/sdk

Misc:

    backend : pro

**Comment by raxon** [comment]
"cordova plugin add cordova-plugin-camera-preview" should work :)
