### ISSUE TITLE
Trying to import CameraPreview getting 'CameraPreview.d.ts' is not a module' error 

### ISSUE THREAD

**Issue by Hodor9898** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#464]
I'm trying to import CameraPreview into my angular project and im getting 
'CameraPreview.d.ts' is not a module' error 

> import { CameraPreview } from 'cordova-plugin-camera-preview';
> 
> @Component({
>   selector: 'app-home',
>   templateUrl: './home.component.html',
>   styleUrls: ['./home.component.scss']
> })
> export class HomeComponent implements OnInit {
> 
>   quote: string;
>   isLoading: boolean;
>   options: any = {
>     x: 0,
>     y: 0,
>     width: window.screen.width,
>     height: window.screen.height,
>     camera: CameraPreview.CAMERA_DIRECTION.BACK,
>     toBack: false,
>     tapPhoto: true,
>     tapFocus: false,
>     previewDrag: false
>   };
>   constructor(private quoteService: QuoteService) { }
> 
>   ngOnInit() {
>     this.isLoading = true;
>     this.quoteService.getRandomQuote({ category: 'dev' })
>       .pipe(finalize(() => { this.isLoading = false; }))
>       .subscribe((quote: string) => { this.quote = quote; });
>   }
> 
>   CameraPreview.startCamera(options);
> 
> }
>

**Comment by jcnowland** [comment]
Having the same problem

**Comment by samscarsella** [comment]
Same problem here in a Vue.js/Quasar stack.
