### ISSUE TITLE
Plans to take video?

### ISSUE THREAD

**Issue by l0c0luke** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#470]
This is working great for me... but I would love to be able to take a video as well. Is this planned for this plugin? I know there are other plugins that can do this, but they all bring up the video application, and I would like to keep my own interface up while recording in the background.

**Comment by Bengejd** [comment]
Currently, there is no support or plans for supporting a video feed by the developer. He is open to someone creating/maintaining this feature but has no plans of implementing it himself.
