### ISSUE TITLE
Camera does not resize with orientation change ...

### ISSUE THREAD

**Issue by proxsys** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#48]
The fixed nature of the camera preview size results in having to stop/start the camera after the orientation change event fires.

Is there a way to make the camera occupy the entire screen and without having to recalculate width and height and stop/start the camera?

I don't know if this is a bug, a lack of feature or limitation.

Thanks!

**Comment by techieyann** [comment]
I just lock the orientation when the camera is open, track the down direction with the accelerometer, and rotate the output image as necessary.
