### ISSUE TITLE
how to fix previewwindow and buttons over each other?

### ISSUE THREAD

**Issue by parsarian** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#480]
I am using the following code to make a camera-based app. But the preview window is not fixed and easily bud dragging over the screen it replaces. Also fab buttons are in behind of preview window. How is possible to fix them over each other on the screen.

home.ts
```

 constructor(public navCtrl: NavController, private cameraPreview: CameraPreview) {
this.startCamera();
  }    
  startCamera() {
    const cameraPreviewOpts: CameraPreviewOptions = {
      x: 40,
      y: 40,
      width: window.screen.width-1,
      height: window.screen.height-1,
      camera: 'rear',
      tapPhoto: true,
      previewDrag: true,
      toBack: false,
      alpha: 1
    };

    this.cameraPreview.startCamera(cameraPreviewOpts).then(
      (res) => {
        console.log(res);
      },
      (err) => {
        console.log(err);
    });
  }

  showCamera(){
    this.cameraPreview.show();
  }

  stopCamera(){
    this.cameraPreview.stopCamera();
  }

  takePicture(){
    const pictureOpts: CameraPreviewPictureOptions = {
      width: 1280,
      height: 1280,
      quality: 85
    }

    this.cameraPreview.takePicture(pictureOpts).then(function(imgData){
      console.log('Picture taken');
      (<HTMLInputElement>document.getElementById('previewPicture')).src = 'data:image/jpeg;base64,' + imgData;
    }, (err) => {
      console.log(err);
    });
  }
}
```
home.html:

```
<ion-content padding>

<ion-fab right bottom>
  <button ion-fab color="primary" (click)="takePicture()">
    <ion-icon name="md-camera"></ion-icon>
  </button>
</ion-fab>
</ion-content>
```

**Comment by cmdickson** [comment]
> fab buttons are in behind of preview window

You need to set `toBack: true` to have the preview display "behind" the web view

**Comment by joseduin** [comment]
I have the same issue

**Comment by cheeroke** [comment]
...and for fix preview you need to set `previewDrag: true,` to `false`.

**Comment by yokeshvaradhan** [comment]
HI all i tried the same but i could not able to see the camera in my mobile
`constructor(public navCtrl: NavController,
              public cameraPreview: CameraPreview) { }
  click_cam(){
		// camera options (Size and location). In the following example, the preview uses the rear camera and display the preview in the back of the webview
		const cameraPreviewOpts: CameraPreviewOptions = {
		x: 0,
		y: 0,
		width: window.screen.width,
		height: window.screen.height,
		camera: 'rear',
		tapPhoto: true,
		previewDrag: false,
		toBack: true,
		alpha: 1
		};

		// start camera
		this.cameraPreview.startCamera(cameraPreviewOpts).then(
		(res) => {
			console.log("succcess ",res)
			this.cameraPreview.show().then(data =>{
				console.log(data);
			});
		},
		(err) => {
			console.log(err)
		});
		


	}

	

}
`
and in my html
`<ion-content padding style=" background-color: transparent " >
    <ion-fab right bottom>
        <button ion-fab color="primary" (click)="click_cam()">
          <ion-icon name="md-camera"></ion-icon>
        </button>
      </ion-fab>

</ion-content>`
in my console i get "camera started"  and  "ok"
but i could not able to see the camera view on to my html
