### ISSUE TITLE
storeToFile for iOS?

### ISSUE THREAD

**Issue by p3v9d5ui** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#481]
Hi,

I see that the storeToFile option has been added to save the image output to a file instead of returning a base64 data string, but unfortunately, this is only for Android.

Is support for iOS planned?

**Comment by westonganger** [comment]
Ideally we should have feature parity completely with both platforms. I would happily accept a PR for this.

**Comment by westonganger** [comment]
Fixed in #524
