### ISSUE TITLE
black preview using toBack: true on IOS(ionic)

### ISSUE THREAD

**Issue by AleCat83** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#483]
Hello,
first of all thanks for the plugin!

with the following code I m trying to use the camera Preview with some overlay controls. When the view start I can see my html (a fab button and the statusbar) but behind them, instead of the camera preview, I see a black screen.

`const cameraPreviewOpts: CameraPreviewOptions = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: cameraPreview.CAMERA_DIRECTION.BACK,
      tapPhoto: false,
      previewDrag: false,
      toBack: true,
      alpha: 1
    };`

`    this.platform.ready().then(() => {
     this.cameraPreview.startCamera(cameraPreviewOpts).then(
        (res) => {
        },
        (err) => {
        });
    });`

I also set the back ground to transparent with
`ion-app, ion-content {
    background-color: transparent !important;
  }`

thank

Ale

**Comment by AleCat83** [comment]
So I was able to solve it. The problem was in the css backgrounds. Previously I added the following **only** to the page specific css
`html, body, ion-app, ion-page, .nav-decor, ion-view, ion-content{
  background-color: transparent !important;
}`
You need to add at least
`ion-app, .nav-decor{
  background-color: transparent !important;//we need this for the camera preview plugin
}`
 **to the app.scss** otherwise the background colour will not be overridden by !important (probably due to other !important directives somewhere else).

Thanks

**Comment by kbala** [comment]
@AleCat83 It works, Thanks a lot!
