### ISSUE TITLE
Whats the best way to contribute to this plugin?

### ISSUE THREAD

**Issue by Bengejd** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#486]
I want to help contribute to this plugin, mainly in the video capture portion of things, but I am not sure the best way to go about this, without having to add/remove the plugin from my ionic application every time I make a change. What would you recommend @westonganger ?

**Comment by westonganger** [comment]
Can you not develop within your application folder in `plugins/cordova-plugin-camera-preview/`

**Comment by Bengejd** [comment]
I just wasn't sure what your process was. From what I've read, you have to add and remove the linked plugin everytime you make a change, so I wasn't sure if you had a better process, or not.
