### ISSUE TITLE
store To File limitation

### ISSUE THREAD

**Issue by Et3rnal** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#489]
I was happy to see storeToFile and decided to use it
However I faced the problem with the name, I tried to rename it but I was getting a file is not found as I was doing that inside takePicture()

So can takePicture call callback function instead of returning the data or the link? or how else I can rename the file?

Anyway, I add this line to CameraActivity.java:455 to solve my problem for now

```
String ts = tsLong.toString();
String path = getTempDirectoryPath() + "/capture"+ts+".jpg";
```
I don't really care what the name is, so this is just to make it uniqe and prevent the need to rename file manually just because we taking mutiple images

Hope this helps someone as I didn't find what I need in here.

Thanks for the great plugin.

**Comment by westonganger** [comment]
Fixed in #524
