### ISSUE TITLE
Camera freezes after phone sleeps and doesn't wake up ...

### ISSUE THREAD

**Issue by proxsys** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#49]
When the phone goes to sleep, by timeout or by pressing the power button, the camera freezes.

The only way out of this is to stop/start the camera.

This creates a user experience that is not seamless.

Is this a bug?

Thanks

**Comment by lukkysam** [comment]
I solved the problem, listening to the events "pause" and resume".

document.addEventListener("pause", function () {
    if (Camera.isActive) Camera.stop();
}, false);

document.addEventListener("resume", function (e) {
	if (Camera.isActive) Camera.start();
}, false);

, where var Camera = {
	start: function () {
		var tapEnabled = true;
		var dragEnabled = true;
		var toBack = true;
		return cordova.plugins.camerapreview.startCamera({
			x: 0,
			y: 0,
			width: window.innerWidth,
			height: window.innerHeight
		}, "back", tapEnabled, dragEnabled, toBack);
	}, ....

**Comment by julitroalves** [comment]
I have same issue! @lukkysam your solution doesn't work for me. :/

**Comment by THMah** [comment]
any update on this??

**Comment by westonganger** [comment]
Can anyone confirm if this is still ocuring with the master version of this plugin.

**Comment by pisti2** [comment]
I have almost the same problem.  When application goes into the background then goes back, it crashes.  There are 2 exceptions in the log
when it goes into the background: 

> com.cordovaplugincamerapreview.Preview.surfaceDestroyed(Preview.java:230)

and when it goes back and crashes:

> com.cordovaplugincamerapreview.Preview.surfaceCreated(Preview.java:219)

The error is: Camera is being used after Camera.release() was called

The app is running under Android 5.1.1

**Comment by THMah** [comment]
Tested with latest master branch.
This issue is fixed.
