### ISSUE TITLE
getHorizontalFOV not included

### ISSUE THREAD

**Issue by nahuelarjonadev** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#491]
I installed the plugin via:

`ionic cordova plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git
`
`npm install --save @ionic-native/camera-preview `

But when I try to call `this.cameraPreview.getHorizontalFOV(cb)` it's not defined. I inspected _@ionic-native/camera-preview/index.d.ts_ and effectively the method is not defined inside class declaration. What am I doing wrong? This is my first ionic cordova project so I might be missing something.

**Comment by jorgedangelo** [comment]
+

**Comment by Choppel** [comment]
The ionic version of this plugin is different from the native version. When using the ionic version you will have to read their documentation. I assume it doesn't state a getHorizontalFOV function which results in the error that you get.
