### ISSUE TITLE
Build failed for Android using PhoneGap Build

### ISSUE THREAD

**Issue by speralta117** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#493]
**Plugin version 0.10.0**

```
<engine name="android" spec="7.0.0" />
<engine name="ios" spec="4.5.5" />
```

I'm using Phonegap Build to compile my project and the iOS part runs without problems, however the android side returns this message:

![image](https://user-images.githubusercontent.com/33643170/46761424-083c4e80-cc9a-11e8-9557-280ed381e43c.png)

I read that this might be solved using an additional configuration in the gradle file of the android project
https://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3

But since I don't have access to those files through Phonegap Build; Is there any other configuration that I might be missing while including your plugin?

**Additional dependencies**
 ```
<plugin name="cordova-plugin-device" spec="1.1.6" />
    <plugin name="cordova-plugin-splashscreen" spec="4.0.3" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="3.0.0" />
    <plugin name="my-app-firebase-plugin" spec="3.0.3" />
    <plugin name="cordova-plugin-photo-viewer" spec="1.1.5" />
    <plugin name="cordova-plugin-media-capture" spec="3.0.2" />
```

Thanks

**Comment by NDMCreative** [comment]
Same here
