### ISSUE TITLE
GOOGLE_PLAY_SERVICES_VERSION

### ISSUE THREAD

**Issue by frankzhangxd** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#494]
I try to use this plugin with cordova-plugin-mauron85-background-geolocation, but they are not compatible. I notice the document says: "Always consult documentation of other plugins to figure out compatible versions" and need to specific the version in config.xml like this:

`
<plugin name="cordova-plugin-mauron85-background-geolocation">
<variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
<variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
<variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking enabled" />
<variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" />
</plugin>
`

Can you kindly indicate me what versions I should write down?

**Comment by m4tt72** [comment]
You have `GOOGLE_PLAY_SERVICES_VERSION = 11+`
and `ANDROID_SUPPORT_LIBRARY_VERSION = 23+`
upgrade `GOOGLE_PLAY_SERVICES_VERSION to 23+` and check for compatibility
Make the changes in `platforms/android/project.properties `

**Comment by frankzhangxd** [comment]
ANDROID_SUPPORT_LIBRARY_VERSION 23 is too old, it is possible to upgrade?

**Comment by m4tt72** [comment]
You can go with 28.0.0 but then you have to check compatible versions etc...
