### ISSUE TITLE
Enhancement: Faster Camera

### ISSUE THREAD

**Issue by lukkysam** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#51]
Hi, I really like this plugin. But there's on thing, that bothers me.

After taking a picture, the liveview disappears, until the setOnPictureTakenHandler fires. It would be nice, if the the liveview would be still available.

My suggestion to enhance functionality (if possible): `cordova.plugins.camerapreview.takePicture` method will return an object containing a identifier (e.g.  the timestamp), and the `setOnPictureTakenHandler` would contain the same identifier.

Like:

```
var photo = cordova.plugins.camerapreview.takePicture(obj);
//photo.timestamp == 123456789
setOnPictureTakenHandler(function(result,e){
//e.timestamp == 123456798
})
```

Maybe the same problem: If I'm taking photos too fast, some photos are lost between.

**Comment by erperejildo** [comment]
We're open for PRs. Feel free to make one if you think you can improve this repo please
