### ISSUE TITLE
cordova camera plugin issue with FILE_URI

### ISSUE THREAD

**Issue by anyangdp** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#511]
```uploadIdCardBack() { 
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI
    };
    this.camera.getPicture(options).then((imageData) => {
      this.idCardBack = imageData;
    }, (err) => {
      // Handle error
      alert('相机' + err);
    });
  }
<img id="idCardImg" [src]="idCardBack" alt=""/>
```
this imageData value like 
  file:///storage/emulated/0/Android/data/com.anyangdp.hellocordova/cache/1545208600890.jpg, 
but this image can not read image and show in the page.
"@ionic-native/camera": "^5.0.0-beta.22"

**Comment by jackbayliss** [comment]
@anyangdp  You are using https://github.com/apache/cordova-plugin-camera, not  cordova-plugin-camera-preview.   👍

**Comment by anyangdp** [comment]
thx, now i used DATA_URL, i  will try cordova-plugin-camera-preview.
