### ISSUE TITLE
How to disable screen lock or sleep mode

### ISSUE THREAD

**Issue by mesutgunay** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#512]
thank you for providing this plugin.  I want the screen sleep mode to be canceled when the camera is turned on or I want the screen lock to be canceled.

**Comment by jackbayliss** [comment]
I used Insomia @mesutgunay.
Check the usage docs:  [https://ionicframework.com/docs/native/insomnia/](url) 👍

**Comment by Hope555** [comment]
@jackbayliss 
Hi jackbayliss
Could you please explain how to stop the 'lag'?
Thanks.
