### ISSUE TITLE
Android - java.lang.NullPointerException - crashes whole webview

### ISSUE THREAD

**Issue by Dutch77** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#514]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class android.app.Fragment.getClass()' on a null object reference

Sorry can't provide whole stack, but on Android application sometimes crashes on CameraPreview.java:299, where fragmentTransaction variable is not set.

Since I have zero knowledge about Android, I fixed it with nasty workaround with cathing and silencing NullPointerException. To my suprise application works as nothing happend even when the error occurs.

`try {
    FragmentManager fragmentManager = cordova.getActivity().getFragmentManager();
    FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
    fragmentTransaction.add(containerView.getId(), fragment);
    fragmentTransaction.commit();
} catch(NullPointerException e) {
    Log.d(TAG, "fragmentTransaction was null");
}`

It would be great if someone provide real fix for this issue.

**Comment by nicowxdvd** [comment]
any idea, same problem!
