### ISSUE TITLE
image freeze effect when taking a picture

### ISSUE THREAD

**Issue by slmarcos** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#518]
when taking a picture the picture freezes quickly. I wonder if I can remove this freeze or increase in a way that shows the user that the photo was actually taken.

Tnks

**Comment by jackbayliss** [comment]
@slmarcos  Unfortunately there's no easy way, it comes down to the device you're using. 

I've had to make my own implementation to stop the 'lag'.  👍

**Comment by Hope555** [comment]
@jackbayliss 
Hi jackbayliss
Could you please explain how to stop the 'lag'?
Thanks.

**Comment by jackbayliss** [comment]
@Hope555  Unfortunately it depends on your camera implementation (so it comes down to the Android code).

I've managed to fix it myself by implementing a different 'camera view', but again it comes down to how it's programmed ultimately and the device being used. I do have a repo on my profile, but that isn't the one I'm currently using. However, it may be okay for taking singular photos without lag. 👍
