### ISSUE TITLE
Low quality images

### ISSUE THREAD

**Issue by blhack** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#53]
The images that this plugin captures seem to be _unbelievably_ low quality.  Taking a picture with the front facing camera using this plugin vs taking the picture with the same camera and the system provided photo application produces extremely different results.

Is there something I am missing, or an attribute I may be passing that could effect this?  Here is my code for actually snapping the photo:

cordova.plugins.camerapreview.takePicture({maxWidth:1600, maxHeight:1200});

(however changing the value here doesn't seem to have any effect on the resultant photo).
![camerapreview_24_07_2015_1348_47_original](https://cloud.githubusercontent.com/assets/673603/8884362/0ac96ac0-320b-11e5-9a8d-3cd816bbfb9d.jpg)
![img_20150724_134214](https://cloud.githubusercontent.com/assets/673603/8884381/28e81e0c-320b-11e5-89de-311ca23c1bba.jpg)

**Comment by marty-krishner** [comment]
+1

**Comment by fernandoTinelli** [comment]
some update about that issue? i'm facing the same problem.

**Comment by fernandoTinelli** [comment]
I figure how resolve the problem. It's related with the optimal size of the preview  in the method "getOptimalPreviewSize".
After the comment "Cannot find the one match the aspect ratio, ignore the requirement", and after the if statement put the code

optimalSize = sizes.get(0);
for(int i=0;i<sizes.size();i++)
{
     if(sizes.get(i).width > optimalSize.width)
           optimalSize = sizes.get(i);
}

if you want enable the focus, put the following code inside the if statement of the method "setCamera".

Camera.Parameters params = mCamera.getParameters();
params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
mCamera.setParameters(params);

Note: I made this modifications for android tablet. i hope this help somebody.

**Comment by Divya-A** [comment]
Any updates on this issue? I am facing the same problem.

**Comment by blhack** [comment]
fernandoTinelli is there an error in that code?  (It looks like you didn't finish declaring the for loop).

**Comment by fernandoTinelli** [comment]
blhack my bad, the for loop is:

 for(int i=0;i<sizes.size();i++)

**Comment by jiwufeiyang** [comment]
I am facing the same problem.After taking a picture is blurred, and finally images are not square (the resolution is not the same width and height)

**Comment by petervojtek** [comment]
The hotfix suggested by fernandoTinelli really works, thanks.

it only took me some time to realize that the proper file which has to be edited is this one:
my_ionic_project/platforms/android/src/com/mbppower/CameraActivity.java

and not this one:
my_ionic_project/plugins/com.mbppower.camerapreview/src/android/com/mbppower/CameraActivity.java

**Comment by mustaphaaassab** [comment]
Hi everybody, thank yu very much for this plugin, it works fine for, the code of quality of the image also works fine, but please i have a problem with the focus, which means when i put code of focus my app crashes if i launch my camera. there is any help please ?

**Comment by RichardBoyder** [comment]
Yes please , me to . I really want to use this plugin, but with no way of auto focus it is unfortunately no use to me. It is probably one of the best plugins out there but really need it to work.

**Comment by goariel10** [comment]
Hi. i'm facing the same problem on iOS, help :)

**Comment by iarry** [comment]
The auto focus solution @fernandoTinelli posted will crash the app if it's not a supported focus mode for the device. 

Here's the code I used to prevent this:
```java
List<String> mFocusModes = mCamera.getParameters().getSupportedFocusModes();

Camera.Parameters params = mCamera.getParameters();
if (mFocusModes.contains("continuous-picture")) {
    params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
} else if (mFocusModes.contains("continuous-video")){
    params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO);
} else if (mFocusModes.contains("auto")){
    params.setFocusMode(Camera.Parameters.FOCUS_MODE_AUTO);
}
mCamera.setParameters(params);
```

This was also in the `setCamera()` function in `CamersActivity.java`, within the `if(mCamera != null)` check.

Issues #72 #33 and #83 could also be fixed by this.

**Comment by blhack** [comment]
Thank you, iarry -- I was getting the crashing issue too.

**Comment by andrea-86** [comment]
@fernandoTinelli  my problem is quite similar, but not the same. 
I've just set autofocus for the camera(with fail but now is not my priority, replacing it with focusing always before take picture, for the moment).
My problem is that photo taked with camerapreview have a 1088x1920 resolution(wich is the max of Camera.sizes size) but photo taken with default application have a 1520x2048 resolution(for the actual settings).
I try to pass higher value of height and width to takephoto() function but this doesn't work.

Have you any idea how to solve this?

**Comment by dinhtuan1991vt** [comment]
It's still very blur with Android. Anyone can solve this?

**Comment by andrea-86** [comment]
@dinhtuan1991vt  i solved the blur problem calling a function that refocus automaticallly before take the photo.
Here's the function

```
public void refocusCamera(){

		Log.d(TAG, "################## refocus ######################");
		getActivity().runOnUiThread(new Runnable() {
			@Override
			public void run() {
				mCamera.cancelAutoFocus();
				mCamera.autoFocus(new Camera.AutoFocusCallback() {
					@Override
					public void onAutoFocus(boolean success, Camera camera) {
						if (success){
							takePicture(0,0);

						}

					}
				});
			}
		});
	}
```

Then have to add the function in execute method in camerapreview and in your js plugin for calling it

**Comment by erperejildo** [comment]
Are focus and optimal quality as well include in last commit?

**Comment by danmobilers** [comment]
Thanks, fernandoTinelli!

**Comment by FelschR** [comment]
Can you create a new release which includes these changes and make it available on npm?

**Comment by FelschR** [comment]
With the latest version on the master branch I still only get 1920x1080 images.
I call the takePicture method without parameters.
What am I missing?

**Comment by SnowBases** [comment]
in iOS, i'm facing the same problem, but I ended up by doing this:

![image](https://user-images.githubusercontent.com/31583701/70037565-b9feb300-15f1-11ea-8478-b97014a16dbf.png)

And after invoke takePicture(), the image quality is getting better.
