### ISSUE TITLE
takeSnapshot function does not exist

### ISSUE THREAD

**Issue by AleCat83** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#531]
Hello,
In my ionic 3 app I'm trying to use the takeSnapshot function in place of the takePicture but I'm getting an error (funcrtion does not exist).

In my package.json I have:

`    "@ionic-native/camera-preview": "^4.20.0"`

and

`    "cordova-plugin-camera-preview": "git+https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git",`

thanks.

**Comment by AleCat83** [comment]
The problem is that the ionicNative wrapper ("^4.20.0")  is still not updated to use this new function. I manually added the function to the ionicWrapper and now I'm able to use the function.

**Comment by wangzhengjiang** [comment]
Hi, 
Could you list the steps on how do you change the ionic wrapper? I face same problem now.

**Comment by AleCat83** [comment]
Hello,

Open the file node_modules/@ionic_native/camera_preview/index.d.ts and add

`takeSnapshot(options?: CameraPreviewPictureOptions): Promise<any>;`

inside the class CameraPreview alongside the other methods.

Open the file node_modules/@ionic_native/camera_preview/index.js and add 

`  CameraPreview.prototype.takeSnapshot = /**
   * Take the snapshot (base64)
   * @param {CameraPreviewPictureOptions} [options] size and quality of the picture to take
   * @return {Promise<any>}
   */
  function (options) {
    return;
  };`

inside the object CameraPreview alongside the others (for example after the equivalent for takePicture).

NOTE: this will not survive a plugin update / reinstall cause you are editing files inside node_modules which is not a good idea. Probably there is a better way to do this, for example overriding the files somewhere else (I don't know if it is possible and how) or creating a fork with the custom of the plugin and pointing the package.json to it.

My goal was to take a picture with the exact size of the screen, reflecting the preview, I ended up using the takePicture method and cropping the image to the screen aspect ratio cause takeSnapshot is missing photo features like flash.

Hope this helps.

**Comment by wangzhengjiang** [comment]
Thank for your instructions.

As you know the changes will overwrite by upgrading, I don't use ionic
wrapper for camera preview, I use plugin directly in my project.

**Comment by hrithiktyagi23** [comment]
these steps are not working for me the error says  Cannot read property 'then' of undefined
