### ISSUE TITLE
flash in takeSnapshot function

### ISSUE THREAD

**Issue by AleCat83** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#532]
In my Ionic 3 application I'm using **takeSnapshot** function to get a picture. I noticed that the flash is not used by this function even if it is active (contrarily to takePicture). Is there a way to enable it?

**Comment by westonganger** [comment]
No `takeSnapshot` takes a screenshot of sortsm not an actual photo. As such no special camera capabilities are available.

**Comment by AleCat83** [comment]
Thanks for the reply. Since I need to take a photo exactly the same as the preview (on my iPhone 7 for example, the photo is wider than the preview), what would be the best approach? 
I tried cropping the photo (using html canvas) after the shot, it seems to work but it is very slow.
