### ISSUE TITLE
undestanding the max zoom value

### ISSUE THREAD

**Issue by AleCat83** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#541]
Hello,

I'm adding a pinch to zoom feature to my Ionic application. It works on both ios/android but I have problems understanding the maxZoom value returned by getMaxZoom level: testing on iPhone 7  I get a maxZoom value of 181 while testing on an Asus Zen Phone the a value is 30. 
Now, if I want to set the zoom to 10x, should a simply call setZoom(10) on both devices or should I normalize the value with the maxZoom?
Thanks for the amazing work!

**Comment by FrancMunoz** [comment]
Hello!

I use to get `getMaxZoom` to get a reference then apply for normalized value using a rule of three... thus, If I want my app with 10 levels of zoom get `getMaxZoom` and divide by 10 and then multiply for current zoom level... in your case for iPhone 7 (18.1 x current zoom level) and Asus Zen (3 x current zoom level). 

Your code will use max zoom of device and will be able to manage all available devices.

Hope it helps!
