### ISSUE TITLE
Forces higher version of cordova (9.0.0) than specified in the project

### ISSUE THREAD

**Issue by estiaan** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#544]
**Issue**: Including this plugin may cause projects to use a different cordova version than specified. Specifically, the project will attempt to use 9.0.0 (and many packages aren't ready for 9 yet). Please see https://stackoverflow.com/questions/55304065/cordova-error-using-requirecordovamodule-to-load-non-cordova-module-q-is-no

**Steps to reproduce**: Install cordova cli 8.1.2., `ionic info` should have `cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)`.

Run `npm install` and `ionic info` should now have `cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)`

**Possible Fix**: Change package.json line 35 from
``` "cordova": "*" ```
to something safer like 
``` "cordova": ">= 8.0.0" ```

I'd be happy to make a pr but I need some guidance on the min cordova version that I should use.

**Comment by westonganger** [comment]
No thanks I like the flexibility. App developers should lock there own version of Cordova.

**Comment by estiaan** [comment]
Fair enough. Please consider changing it to "cordova": ">=0.0.0"` or similar - that's what other plugins do. This causes a pretty tedious debugging process, and locking your version of Cordova lib in package.json isn't really standard practice (if you use the CLI as intended it won't lock it.)

**Comment by westonganger** [comment]
I think it most definitely should be standard practice to lock your cordova version in package.json. 

I fail to see how `>=0.0.0` and `*` are any different? Can you elaborate?

**Comment by estiaan** [comment]
> I think it most definitely should be standard practice to lock your cordova version in package.json.

I think I now agree with you on this, but if you use ionic through the cli it isn't set for whatever reason so the majority of devs won't have it locked. 

> I fail to see how `>=0.0.0` and `*` are any different? Can you elaborate?

`>=0.0.0` will use whatever version is returned by `cordova -v`.  `*` will use the highest version it can find no matter what you started building with, so `cordova -v` and `ionic info`'s cordova might not match after `npm install` if you are working on multiple projects.

**Comment by westonganger** [comment]
Ok sounds good. Please submit a PR and I will merge it.

**Comment by estiaan** [comment]
It looks like the Cordova dependency has been removed in `0.11`, so no need.
