### ISSUE TITLE
getCameraCharacteristics missing

### ISSUE THREAD

**Issue by safead** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#546]
No Object C code for "getCameraCharacteristics" method in current release. As the result, cordova returned this error on method invocation "ERROR: Method 'getCameraCharacteristics:' not defined in Plugin 'CameraPreview'"

**Comment by westonganger** [comment]
Currently this feature is for Android only. A PR for iOS support would be happily accepted

I have now updated the readme to state this. Thanks for pointing this out.
