### ISSUE TITLE
camera becomes blurred due to camera movement

### ISSUE THREAD

**Issue by abbasse** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#548]
Hello, 
I use the camera preview plugin "0.11.0" and I configure my CameraPreview with this parameters : 

const cameraPreviewOpts: CameraPreviewOptions = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: 'rear',
      toBack: true,
      tapPhoto: false,
      tapToFocus: true or false (try both),
      previewDrag: true or false  (try both)
    };

Most of the times the preview is good but if I make multiple movements with my camera (Xiaomi pocophone f1), I'm getting a blurry preview image.  And if I take a picture at this time the image is also blurred. It seems that it is a problem of focus. 
However If I navigate away for the app and then I come back, the image is sharp again or if I swichCamera (rear -> front -> rear).

Thanks in advance.

**Comment by Choppel** [comment]
Use getSupportedFocusModes to see which focus modes your phone supports.
Use getFocusMode to get the current focus mode. Maybe it is set to fixed.
Use setFocusMode to set it to auto.
