### ISSUE TITLE
Cannot access clicked image on android

### ISSUE THREAD

**Issue by developeron29** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#55]
This is one great plugin. Thanks!

The image doesn't gets stored into the camera roll in android as it does in ios.
Cannot access the image from the returned url(result[0]) as well, on android.

Any help would be appreciated, Thanks!

**Comment by Tawsif** [comment]
same problem for me as well

**Comment by Danyzzz** [comment]
same problem for me...it is possible save image to the gallery?

**Comment by Djagu** [comment]
Same issue here ...

**Comment by westonganger** [comment]
takePicture now only returns base64. Please use master and use new instructions in readme.
