### ISSUE TITLE
CameraPreview.setZoom

### ISSUE THREAD

**Issue by AliMonam** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#558]
I could not get any feedback from CameraPreview.setZoom(2) on Android. It works perfectly on iOS. 
Is anyone else experiencing this issue?

**Comment by cassini-usman** [comment]
Yes. Having this same issue. setZoom() currently works fine with iOS but not on Android.

**Comment by Choppel** [comment]
What is the output of getMaxZoom? Also, try calling setZoom with the errorCallback and see what the error message says.
