### ISSUE TITLE
ionic 4 startCamera too slow

### ISSUE THREAD

**Issue by AmbroiseVuaridel** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#566]
startCamera takes 10s to complete on iphone 6s with ionic 4.
I use the plugin from git master repository
this code displays something between 9000ms and 11000ms :
  cameraOptions = {
    x: 0,
    y: 0,
    width: window.screen.width,
    height: window.screen.height,
    camera: this.cameraPreview.CAMERA_DIRECTION.BACK,
    toBack: true,
    tapPhoto: false,
    tapFocus: true,
    previewDrag: false,
    storeToFile: false,
    disableExifHeaderStripping: false
  };
  async ngOnInit() {
      console.time("1")
      await this.cameraPreview.startCamera(this.cameraOptions);
      console.timeEnd("1")
  }

**Comment by nvahalik** [comment]
Are you doing this in a debug build? Debug releases are way slower than release builds when I've tested this.

**Comment by AmbroiseVuaridel** [comment]
@nvahalik Thank you for your message.
i am building my app like this : 
ionic cordova build ios --prod --verbose -- --buildFlag="-UseModernBuildSystem=0"

**Comment by AmbroiseVuaridel** [comment]
actually it turns out that this huge lag is due somehow to the debbuger (independently of prod or dev build). While being connected to xcode for the log, the camera takes ages to load, whils unplugged, a couple of seconds...
