### ISSUE TITLE
Camera Is Open but Hiding Behind My UI  when toBack is True

### ISSUE THREAD

**Issue by siddmegadeth** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#567]
Camera Is Open but Hiding Behind My UI  when toBack is True

Platform  : Android
Framework : OnsenUI , AngularJS
is there any CSS3/CSS to control when toBack is enabled. 
Tried with your example wbut does not seem to work. 

Need this fix urgently.

Thanks

**Comment by jesobreira** [comment]
Have you tried setting your UI elements to background: transparent?
