### ISSUE TITLE
Blurry Image (back camera without flash)

### ISSUE THREAD

**Issue by tompap** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#577]
Hello,

I tried a lot of different settings but with my phone (OnePlus 6T), when taking a picture takePicture or takeSnapshot the image is blurry.

I can set the focus mode and see that it work => in the preview image, In the preview the image is perfect, it's just when taking a picture that the result is blurry.

NOTE : when the flash is ON, the image is correct !
NOTE: using the front camera is ON

I suspect it's because on a OnePlus 6T there are two camera at the back (and when taking picture the other camera is used instead of the one with the correct focus in the preview). 

How to solve this ?

**Comment by tompap** [comment]
Hello, why did you close my issue ? Did you solve it ?
This extension is wonderful better than default cordova-camera. I would like to remove cordova-camera on my current applications but the images with your plugin have an issue with focus or something that make the image blur. No issue when flash is activated but this is not a real solution.

If you try to take a picture of a book, you will see that the text on the book is not readable due to "blur" (like if focus was OK)

**Comment by westonganger** [comment]
Sorry I have to close non-actionable issues like this quite often if these cordova projects are to survive, the issues simply build up too fast and no one solves them. 

Honestly different devices produce different results. Please try testing with a couple other different devices and see if you are getting the same results. The other phones may work correctly. 

That being said your idea of 1 camera previewing and 1 camera taking photo is interesting. I encourage you to dig into the code and see if you can find the problem. The Android Java code is quite easy to understand.

**Comment by abhishek1234321** [comment]
The same issue happens on One plus 6 as well, Android 10

@tompap were you able to figure out a fix?

**Comment by matiasfic** [comment]
Having exact same problema on One Plus 6T Android 10
