### ISSUE TITLE
Stop Camera shows dark background color

### ISSUE THREAD

**Issue by abhibly** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#578]
Hello,

In my app, I have to capture picture using front camera. But after capturing the picture, a dark screen is displayed. I am attaching the screenshots:

When the app started, the page looked like this. The background was white:
![Screenshot_2019-11-18-14-01-09-729_io ionic starter](https://user-images.githubusercontent.com/15784815/69036617-4747e200-0a0c-11ea-8431-db9a19d0a358.png)

When i start camera, the camera is displayed
![Screenshot_2019-11-18-14-01-35-097_io ionic starter](https://user-images.githubusercontent.com/15784815/69036615-4747e200-0a0c-11ea-8ca2-bf531f63589a.png)

After capturing the camera, the background is dark
![Screenshot_2019-11-18-14-01-43-893_io ionic starter](https://user-images.githubusercontent.com/15784815/69036616-4747e200-0a0c-11ea-9517-3c36f8a60f57.png)

Below is the code I used to start and capture the picture:
```
  StartCamera() {
    const cameraPreviewOpts: CameraPreviewOptions = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: 'front',
      tapPhoto: true,
      previewDrag: true,
      toBack: true,
      alpha: 1
    };

    // start camera
    this.cameraPreview.startCamera(cameraPreviewOpts).then(
      (res) => {
        this.camerastarted = true;
      },
      (err) => {
        console.log(err);
      });
  }

  TakePicture() {
    const pictureOpts: CameraPreviewPictureOptions = {
      width: 1280,
      height: 1280,
      quality: 85
    };
    this.cameraPreview.takePicture(pictureOpts).then((imageData) => {
      this.StopCamera();
    }, (err) => {
      console.log(err);
    });
  }

  StopCamera() {
    this.cameraPreview.stopCamera().then(() => {
      this.camerastarted = false;
    });
  }
```

And my HTML code looks like:
```
<ion-app>
  <ion-button *ngIf="!camerastarted" (click)="StartCamera()">Start Camera</ion-button>
  <ion-button *ngIf="camerastarted" (click)="TakePicture()">Take Picture</ion-button>
</ion-app>
```
After capturing the picture, I want the background to be white. 
Can somebody please help me how to achieve this.

**Comment by thalerlinus** [comment]
+1 
Same Problem Try to use lastCam on ios.
Found No solution on android yet

**Comment by rushsteve1** [comment]
As a temporary workaround:
- create a CSS class containing `background-color: white !important`
- Remove the class from the body in the camera open callback like this `document.body.className = ''`
- Add the class to the body in the camera close callback like this `document.body.className = 'class'`

**Comment by Maqsyo** [comment]
I have the same issue.
I think it is cause of this setting here:

https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/blob/master/src/android/CameraPreview.java#L324
`view.setBackgroundColor(0x00000000);`

Is this necessary or could you reuse the default background-color of the main-window?
Maybe you could provide a config for us so we could set it to "white" or something else?

**Comment by westonganger** [comment]
@Maqsyo I would love a PR for changing the background color. Transparent is going to be unlikely I would think. Ideally the PR should include both Android and iOS.

**Comment by roccolocko** [comment]
Did anyone find a solution for this? I have the exact same issue in the current version.

**Comment by acyvas** [comment]
Just add transparent to --ion-background-color: in variables.scss
Works on Ionic 6 Capacitor 3
`.ios body {
     --ion-background-color: #000000 transparent;`

`.md body {
    --ion-background-color: #121212 transparent; `
