### ISSUE TITLE
Camera Preview have zoom compared with native camera

### ISSUE THREAD

**Issue by enoizz** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#580]
Hey, when I do StartCameraPreview I use the SetZoom(0) but the camera is still zoomed comparing with the native camera. 
Can anyone help me with this "zoom" when i do StartCameraPreview?

**Comment by KnufflPuffl** [comment]
I have the same issue, is there any fix to this?

**Comment by KnufflPuffl** [comment]
Hi again, I fixed the issue myself, so I wanted to let you know, it might help you. 

The problem for me was that I set the width and height dimensions to window.innerWidth and window.innerHeight, but I also had a header on top and an overlay on bottom - removing these heights from window.innerHeight did the trick for me.

**Comment by jalabenson** [comment]
> Hi again, I fixed the issue myself, so I wanted to let you know, it might help you.
> 
> The problem for me was that I set the width and height dimensions to window.innerWidth and window.innerHeight, but I also had a header on top and an overlay on bottom - removing these heights from window.innerHeight did the trick for me.

Can you please mention the code.
When I open the app, by default it is zooming.
Struggling on this.

**Comment by KnufflPuffl** [comment]
> > Hi again, I fixed the issue myself, so I wanted to let you know, it might help you.
> > The problem for me was that I set the width and height dimensions to window.innerWidth and window.innerHeight, but I also had a header on top and an overlay on bottom - removing these heights from window.innerHeight did the trick for me.
> 
> Can you please mention the code.
> When I open the app, by default it is zooming.
> Struggling on this.

Sure here is the code: 

	var w = window.innerWidth; 
	var h = window.innerHeight*0.80-60; 

	var options = {
	  x: 0,
	  y: 60,
	  width: w,
	  height: h,
	  camera: CameraPreview.CAMERA_DIRECTION.BACK,
	  toBack: true,
	  tapPhoto: true,
	  tapFocus: false,
	  previewDrag: false,
	  storeToFile: true,
	  disableExifHeaderStripping: false
	};
	

	
	CameraPreview.startCamera(options);
	
	
	CameraPreview.setZoom(zoom);


As you can see in my case the total height of the camera view was only 80% - 60px, due to my  header and footer on top/bottom.
