### ISSUE TITLE
storeToFile

### ISSUE THREAD

**Issue by elepetit** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#584]
The wrapper for ionic native forgot the storeToFile option in CameraOptions interface.

**Comment by RobinGiel** [comment]
do this : 

  startCamera() {
    const cameraPreviewOpts = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: "rear",
      toBack: true,
      alpha: 1,
      tapToFocus: true,
      storeToFile: true
    };
    this.cameraPreview.startCamera(cameraPreviewOpts).then(
      res => { .....

**Comment by RobinGiel** [comment]
I did this to use the option storeToFile

  startCamera() {
    const cameraPreviewOpts = {
      x: 0,
      y: 0,
      width: window.screen.width,
      height: window.screen.height,
      camera: "rear",
      toBack: true,
      alpha: 1,
      tapToFocus: true,
      storeToFile: true
    };
    this.cameraPreview.startCamera(cameraPreviewOpts).then( ....
