### ISSUE TITLE
AndroidManifest issue on building by Cordova

### ISSUE THREAD

**Issue by SimoneVB** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#585]
Hi,

I'm using Cordova CLI on Windows. Using your plugin v.0.11.1 and Android platform 8.1.0.
```
    <plugin name="cordova-plugin-camera-preview" source="npm" spec="~0.11.1">
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
    </plugin>
```

I have a recurring error in AndroidManifest that prevents me from compiling the App
"**Element uses-feature#android.hardware.camera.autofocus at AndroidManifest.xml:20:5-70 duplicated with element declared at AndroidManifest.xml:19:5-95**"

The problem is caused by the feature "android.hardware.camera.autofocus",
which is duplicated in the manifest:
```
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
```

How can I solve or work around the problem?

Ty in advance
Simone

**Comment by westonganger** [comment]
@SimoneVB I just checked the manifest and it is not duplicated. 

https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/blob/master/plugin.xml#L38
