### ISSUE TITLE
imageData / image file size is larger than native camera data

### ISSUE THREAD

**Issue by PabbleDabble** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#586]
Hello!  I first wanna say, I really like this plugin, you're doing a great job with it / the repo here.  Thanks so very much.  

My app uses the native camera as well as camera preview to utilize a "multi-cam" setting where the user can take multiple pictures and save them all at once.  However, the end result of pictures taken using the camera preview have much higher file size than ones with the native camera.  

v0.10.0 at the moment

In my CameraPreviewPictureOptions I've been playing with quality but keeping w/h set at width: 2448 / height: 3264 to match the images I'm getting from the native camera.
I've been varying quality at 50, 85, and 100 to compare the three images / data to the native images (Android testing for now, although will be testing this against iOS as it's used in this app as well, Windows we default the multi-cam to disabled).

Native: 200-250 kb
Q50: 300-500 kb
Q85: 800-1000 kb
Q100: 3000-4000 kb

I've been tracking this by the final saved images, as well as the length of the base64 string when takePicture(options) responds.  

All the images look fine for the most part, but we'd really like to be at the default quality, and have the file size closer to the native images (upload times, storage space).  

Is there anything you can think of that might help here?
Is this a known difference?
Would store to file help with this (I just haven't gotten around to testing this, I'm fine with the b64 data for our current workflow)?

I've really tried to do a lot of research / my own testing before posting this, so apologies if this is covered somewhere else / a known thing. 

Any help here would be great! Thanks so much

**Comment by PabbleDabble** [comment]
I'm investigating this more, and comparing the images.
The image taken with the native camera (200-250 kb size) appears to be pretty much the same quality as the camera-preview image taken with quality: 50.
I tested this by comparing pictures taken of the same object, and comparing parts of the image when zoomed in 200/300% and I'm not really able to discern any quality loss between the two.

I'm still hoping for someone smarter than me to chime in here, but I think my fix might be to simply assume quality: 50 is an acceptable file size / image end result quality.  

I will update / respond as I can.  Thanks

**Comment by westonganger** [comment]
Thanks for your investigation into this. Be sure you are testing with multiple different Android devices as well.

A PR will be appreciating if you are able to come up with an improvement to our default quality value after further testing with iOS.

**Comment by PabbleDabble** [comment]
We've decided to open the camera preview with the following
const width = 3264;
const height = 2448;
const quality = 50;

I don't think the default quality should be changed at this time.  

**Re: My original issue/query:** I think my understanding of the plugin was most likely incorrect.  Unless anyone else has other comments about the base64 data coming back from the plugin, relative to the native camera, I think I will close this in a couple days.  

Thanks so much.

**Comment by PabbleDabble** [comment]
Just for one final follow-up, I did see camera preview does have the method "getSupportedPictureSizes()" included, which works really nicely, so if anyone else is trying to get the supported resolutions, you can start the camera preview, then run that method, then get back an array of supported sizes, and is those values as inputs to "takePicture()"

Cheers!
