### ISSUE TITLE
Video recording error

### ISSUE THREAD

**Issue by bearbearLin** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#591]
when i run the  function of stopRecordVideo()，will throw an error，"Attempt to invoke virtual method 'void android.media.MediaRecorder.stop()' on a null object reference"

**Comment by vipulsharma144** [comment]
@bearbearLin see this https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/324#issuecomment-592563590

**Comment by westonganger** [comment]
Please use the updated startRecordVideo instructions, the arguments list was incorrect before.

Old Instructions: 
startRecordVideo(cb, [errorCallback])

New Instructions:
startRecordVideo(options, cb, [errorCallback])
