### ISSUE TITLE
 CameraPreview is not abstract and does not override abstract method

### ISSUE THREAD

**Issue by RobinGiel** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#594]
cordovaplugincamerapreview\CameraPreview.java:36: error: CameraPreview is not abstract and does not override abstract method onSwitchCameraError(String) in CameraPreviewListener
public class CameraPreview extends CordovaPlugin implements CameraActivity.CameraPreviewListener {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

_________________________________________________________

**Comment by westonganger** [comment]
This should now be fixed in e16896a

**Comment by RobinGiel** [comment]
Thanks all @westonganger :-) I'm able to build again. Cheers!
