### ISSUE TITLE
local variable height is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by fudr** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#596]
Hi, Im getting this when trying to build:

cordova-build error : C:\cordova\test\platforms\android\src\com\cordovaplugincamerapreview\CameraPreview.java:439: error: local variable height is accessed from within inner class; needs to be declared final
1>MSBUILD : cordova-build error :  fragment.startRecord(getFilePath(filename), camera, width, height, quality, withFlash);
1>MSBUILD : cordova-build error :  ^
1>MSBUILD : cordova-build error : C:\cordova\test\platforms\android\src\com\cordovaplugincamerapreview\CameraPreview.java:439: error: local variable quality is accessed from within inner class; needs to be declared final
1>MSBUILD : cordova-build error :  fragment.startRecord(getFilePath(filename), camera, width, height, quality, withFlash);

etc for each of the startRecord  parameters. Any thought?
thanks

**Comment by fudr** [comment]
Any thought, I still cant compile it.
thanks

**Comment by westonganger** [comment]
This is now fixed in master
