### ISSUE TITLE
can you put a layer of html on top of the camera?

### ISSUE THREAD

**Issue by sourcer18** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#602]
can you put a layer of html on top of the camera?. 
I want to add a transparent png on top so that I have a graph, is this possible?

**Comment by viewportdesign** [comment]
yes this is possible - simply using position:absolute; or position:fixed; with z-index should do the trick.

**Comment by sourcer18** [comment]
I have put it as you have commented and it does not work, is it possible that there is something that is not putting well?

![5b7b1576-6863-460e-8016-b11aa01ca2cb](https://user-images.githubusercontent.com/6040292/80248052-7c1d2c80-866f-11ea-99ae-a881d62e09a9.jpg)

the idea is to see it like this

![image](https://user-images.githubusercontent.com/6040292/80248177-b4246f80-866f-11ea-9cdb-3822fd5171e1.png)

**Comment by sourcer18** [comment]
in this tutorial, although it is old, it manages to put html on top of the camera. What do you do to get it? Use this great plugin

https://www.joshmorony.com/ionic-go-create-a-pokemon-go-style-interface-in-ionic-2/
