### ISSUE TITLE
App Crash/Restart web view due to OOM, when capturing multiple photos

### ISSUE THREAD

**Issue by ryaa** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#604]
The app crashes/restarts when taking multiple photos. This seems to be due to an out of memory (OOM) issue, where the OS tells the app to free memory and forces to reload/restart the app.

This is 100% reproducible on iPhone 6S Plus with 16 GB when taking 24-26 photos with the plugin returning base64 images and tapPhoto is set to false.

Steps to reproduce:
1) invoke **startCamera** method with both **storeToFile** and **tapPhoto** options set to false
2) start taking multiple photos by sequentially invoking **takePicture** with **quality** option set to 100 (max value)
Note:
- since **startCamera** **tapPhoto** options set to false, in my app I have "Add" button to trigger taking a photo. The user can tap this as many times as needed and tap "Done" when finished. This enables the user taking multiple photos.
- since **startCamera** **storeToFile** option  is set to false and **takePicture** **quality** option set to 100 (max value) the latter method will return very large base64 string (can be as large as 10-12 MB)

After the user takes 24-26 photos the app (web view) is restarted (this number might be different based on the **takePicture** **quality** option value, camera characteristics and the smartphone memory size)

When checking the logs when connected to XCode the below or similar messages can be seen:
```
Received memory pressure event 1 vm pressure 0
Received memory pressure event 1 vm pressure 0
Received memory pressure event 4 vm pressure 1
Received memory pressure event 4 vm pressure 1
```

The problem seems to be due to the memory leak. **takePicture** method adds cordova callbacks  to the global scope and those are never cleaned up, until the web view is restarted to free the memory. This seems to be because **takePicture** method returns plugin result with keepCallback set to true (both for iOS and Android platforms) and each subsequent **takePicture** method invocation adds another callback reference to window.cordova and when this method returns a very large string this causes the problem with the memory not being released - see memory snapshot below

<img width="1431" alt="Screenshot 2020-04-22 at 15 37 52" src="https://user-images.githubusercontent.com/3608222/80562817-89307780-89f1-11ea-930e-239fde3a3f51.png">

My assumption is that the initial intention for **takePicture** was that it is invoked only once and when the user taps (**startCamera** **tapPhoto** option set to true) the appropriate callback is invoked multiple times and is cleaned up when the user is finished. However, if **takePicture** is invoked multiple times with **startCamera** **tapPhoto** option set to false, this leads to a memory leak, which, for very large strings returned, causes the app (web view) to restart due to the memory consumption.

Probably, the cordova callback should not be kept if **startCamera** **tapPhoto** option set to false, since this implies that **takePicture** will be invoked once or multiple times for each photo to be taken.

**Comment by westonganger** [comment]
Great investigation. Thank you for your work on this via PR #605. I will keep this open until you confirm the issue is resolved.

**Comment by ryaa** [comment]
> Great investigation. Thank you for your work on this via PR #605. I will keep this open until you confirm the issue is resolved.

I tested this change on my side and with it i can take 50 photos sequentially without crash/app restart. I did not try more then 50 (taking too much time) but without this change the app always restart after 24-26 photos taken on my iPhone 6S Plus so I see the improvement.

**Comment by genocide453** [comment]
> > Great investigation. Thank you for your work on this via PR [#605](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/605). I will keep this open until you confirm the issue is resolved.
> 
> I tested this change on my side and with it i can take 50 photos sequentially without crash/app restart. I did not try more then 50 (taking too much time) but without this change the app always restart after 24-26 photos taken on my iPhone 6S Plus so I see the improvement.





https://madam48.github.io/3SXPsTiIUP8n1EqOnwDRmMpTBRTKBTULDC_U6j-0ohHOivmmQdfJKzDBuFQ/
