### ISSUE TITLE
Android- Back Camera Direction- Problem with preview rotation

### ISSUE THREAD

**Issue by psivori** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#608]
I got this logs running the plugin on Android 9 in many devices:

D/Preview: screen is rotated 90deg from natural
D/Preview: back camera is oriented -90deg from natural
D/Preview: need to rotate preview 0deg

The device is rotated 90 degrees, so the result should be displayOrientation = 1, not 0. I think there is something wrong with this code on Preview class:

if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
displayOrientation = (info.orientation + degrees) % 360;
displayOrientation = (360 - displayOrientation) % 360; 
} else {
**displayOrientation = (info.orientation - degrees + 360) % 360;**
}

**Comment by westonganger** [comment]
Please create a PR if you still believe the code to be incorrect.
