### ISSUE TITLE
Android v4.1.1 cordova.plugins.camerapreview undefined

### ISSUE THREAD

**Issue by rphansen91** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#61]
After trying to implement the Camera Preview I ran into issues initializing the camera. Followed the documentation but could not figure out why the cordova.plugins.camerapreview was not firing anything and after deviceready executing

```
alert(cordova.plugins.camerapreview)
```

Returns undefined in the alert box

I then tried to build the app [Cordova Camera Preview App](https://github.com/mbppower/CordovaCameraPreviewApp) and everything worked as expected after building onto my HTC running Android v5.0.5

After going through the CordovaCameraPreviewApp cordova folder structure everything was set up the same except for the following file

CordovaCameraPreviewApp

```
./platforms/android/cordova/version
var VERSION = "3.6.4";
```

MyApp

```
./platforms/android/cordova/version
var VERSION = "4.1.1";
```

Any suggestions on solving this issue I also tried to remove all plugins and reinstalling but to no avail

**Comment by foysalit** [comment]
seeing the same issue. ```cordova.plugins``` doesn't seem to contain the ```camerpreview``` object.

**Comment by Sentence** [comment]
+1

**Comment by tonymckendry** [comment]
Bump, I'm having the same issue (using Meteor, which uses Cordova for Android 4.1.1)

**Comment by westonganger** [comment]
Fixed in master. Follow the new instructions in the readme
