### ISSUE TITLE
z-index of dialog above preview

### ISSUE THREAD

**Issue by kapchew** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#610]
Hi,

Is there a way to make some HTLM element to appear on top of camera preview? I am using toBack: false, and when my app needs to show an error, I need the error message to appear on top of the camera preview.

Thanks.

**Comment by westonganger** [comment]
Your going to have to play around with your CSS to achieve this. Sometimes it can be tricky.

**Comment by niravparsana94** [comment]
@kapchew,
I need similar thing. I need to draw canvas element above camera view. I tried with z-index but it is not working.
Did you found any solution?
