### ISSUE TITLE
Redirect camera preview output to specify canvas

### ISSUE THREAD

**Issue by kapchew** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#612]
Hi,

Is there a way to redirect camera preview output to a user specified canvas instead of using the default preview panel? e.g.

CameraPreview.startCamera(canvas, onSuccess, onFailed)

This will give much more flexibility to developers and also avoid the problem of z-index of the camera preview panel either behind html or above all html element.

**Comment by westonganger** [comment]
No sorry. Likely you will need to use a different plugin for that functionality.
