### ISSUE TITLE
startRecordVideo / stopRecordVideo not found

### ISSUE THREAD

**Issue by loucif01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#613]
Hi guys,
do functions startRecordVideo and stopRecordVideo really work ?! beacuse i install the plugin cordova-plugin-camera-preview but i didn't find these methods included,pleas any help!

![startRecordVideoNotFound](https://user-images.githubusercontent.com/32873487/82732848-d1e50300-9d07-11ea-9432-5c0f36c6305f.png)

**Comment by piyushysoft** [comment]
Hi @loucif01 
I also work with same plugin. In this plugin document has functions startRecordVideo and stopRecordVideo. Really when install plugin i din't find methods included on this plugin. 
its better to use other plugin as per requirement.

**Comment by vipulsharma144** [comment]
hi @loucif01 
it should work, may I know how you are using the plugin?

**Comment by piyushysoft** [comment]
hi @vipulsharma144  please first add plugin in your code and please check startRecordVideo methods is display in it or not?

**Comment by vipulsharma144** [comment]
@piyushysoft the "displaying" of the function in editor suggestions is editor dependent. For that one needs to know how the project is configured just because it is not popping up in the editor's suggestions does not mean it doesn't exist.

**Comment by piyushysoft** [comment]
hi @vipulsharma144  I check with my code but i type manually then also getting me error for  startRecordVideo function.

**Comment by piyushysoft** [comment]
@vipulsharma144 
![camera](https://user-images.githubusercontent.com/54830712/82831852-2a1e2f80-9ed7-11ea-9bae-7bdf95196dee.png)

Please review attach file..

**Comment by piyushysoft** [comment]
@vipulsharma144  please review attach screen shot.
![camera](https://user-images.githubusercontent.com/54830712/82831929-60f44580-9ed7-11ea-9dd2-76b1133359d2.png)

**Comment by vipulsharma144** [comment]
@piyushysoft are you developing this in Ionic? can you provide your package.json?

**Comment by piyushysoft** [comment]
@vipulsharma144  yes I developing using ionic . I shared my package.json  in attach file. Please review and get back to me.
[package.zip](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/files/4678332/package.zip)

**Comment by vipulsharma144** [comment]
That is the reason i asked you the details. As the @ionic-native/camera-preview package is not yet updated you are not able to see the suggestions in your editor . This is not the fault of the plugin.

**Comment by loucif01** [comment]
@vipulsharma144  so the fault is in @ionic-native/camera-preview ?how can i fix this? do you have any other options,i really need this function!

**Comment by piyushysoft** [comment]
> That is the reason i asked you the details. As the @ionic-native/camera-preview package is not yet updated and thus you are not able to see the suggestions in your editor . This is not the fault of the plugin.

@vipulsharma144 please suggest way then resolve it..

**Comment by vipulsharma144** [comment]
@loucif01  it's not a fault , the package is not yet updated. I am not completely sure regarding fix , but can you try editing 2 files
1) node_modules/@ionc-native/camera-preview/index.js add 
```

CameraPreview.prototype.startRecordVideo = function(options) {
    return cordova(
      this,
      "startRecordVideo",
      { successIndex: 1, errorIndex: 2 },
      arguments
    );
  };
  CameraPreview.prototype.stopRecordVideo = function() {
    return cordova(
      this,
      "stopRecordVideo",
      { successIndex: 1, errorIndex: 2 },
      arguments
    );
  };

```


and 
2)  node_modules/@ionc-native/camera-preview/index.d.ts add 

```
startRecordVideo(options?: any): Promise<any>;
stopRecordVideo(): Promise<any>;
```
NOTE: If this works this is just a **hack** and will be replaced on update.

**Comment by loucif01** [comment]
@vipulsharma144 
thank you mister hacker! :) yes it worked, we just also need to add what you wrote to the two files of the directory  : node_modules/@ionc-native/camera-preview/ngx

**Comment by vipulsharma144** [comment]
@westonganger  can you close this?

**Comment by westonganger** [comment]
Sure @vipulsharma144 thanks for your resolution of this issue.

**Comment by piyushysoft** [comment]
@vipulsharma144  thanks for help. startRecordVideo(options?: any): Promise<any>;
stopRecordVideo(): Promise<any>; can't me return any thing after process..
