### ISSUE TITLE
How to display full viewport, instead of the zoomed in feel of the preview window

### ISSUE THREAD

**Issue by joshuaohana** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#62]
The preview shows a zoomed and cropped viewport of the camera. When you capture a picture you have access to both the full image and the one shown in the preview.

I want to be able to display the full image as the preview (as opposed to the zoomed/cropped view).

How can I do this?

**Comment by marty-krishner** [comment]
+1

**Comment by thomascrown** [comment]
+1

**Comment by Tawsif** [comment]
+1

**Comment by RichardBoyder** [comment]
Hi guys, How do we fix this?

**Comment by Tawsif** [comment]
Any update on this ??

**Comment by Tawsif** [comment]
@joshuaohana got any solution to fix this ??

**Comment by andrea-86** [comment]
+1, it will be very nice!

**Comment by joshuaohana** [comment]
@Tawsif @andrea-86 @RichardBoyder  hah okay so apparently I didn't fix it, but came up with a janky hack...

Added the below (note my comment) to CameraActivity.onLayout(). Just hard-coded previewWidth and height. That's the size of the box I'm throwing the preview on and apparently it must've worked well enough because I haven't touched it since. To be honest, this was a while ago and I barely remember it...

            // this kinda works maybe 85% good
            //
            previewWidth = 200;
            previewHeight = 175;

**Comment by julitroalves** [comment]
I have noted that it occurs when the orientation device is set to landscape but the device is on portrait orientation so when camera preview loads it have dimensions of landscape orientation but in portrait format.

To test this issue hold the device, from begin of opening of app to full content loaded on view, in a given orientation and see if preview is zoomed in this case all occurs successfully.

**Comment by weiz18** [comment]
hellom we re still facing the same issue.is there any way to fix it ?
cheers
