### ISSUE TITLE
Docs and current Release are not up to date

### ISSUE THREAD

**Issue by wsdt** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#620]

**Comment by westonganger** [comment]
I cannot do anything about this if you do not provide any exact details.

**Comment by wsdt** [comment]
E.g. you are using a static reference everywhere in your docs: 
`CameraPreview.startCamera(options);`

But the current release needs an injected instance. Moreover, dependency injection e.g. in Angular is not as easy as it should be, as no module or similar is implemented.

**Comment by westonganger** [comment]
Hmm, well this is the normal way of doing things in javascript. We shouldn't have to care about which specific dependency injection format you are using as this library is not specific to Angular or any framework at all.

**Comment by westonganger** [comment]
Is there anything other documentation issues you had or is that it?
