### ISSUE TITLE
ERROR: Method 'startRecordVideo:' not defined in Plugin 'CameraPreview'

### ISSUE THREAD

**Issue by ddtch** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#622]
Hello folks, I run the camera preview plugin and it works, it shows me picture everything is good, but when I'm trying to start recording I see an error in logs

`ERROR: Method 'startRecordVideo:' not defined in Plugin 'CameraPreview' 2020-07-09 00:16:34.540668+0400 My App [27671:4583490] FAILED pluginJSON = ["CameraPreview1342876959","CameraPreview","startRecordVideo",["front",375,667,85,false]]`

What can be the problems? Any Ideas?

**Comment by AAnish11** [comment]
Hello @ddtch 
I am getting the same error when i am trying to record the video without passing the all `opts` . Below is my code which is running well.
```
const opt = {
        cameraDirection: this.cameraPreview.CAMERA_DIRECTION.BACK,
        width: window.screen.width / 2,
        height: window.screen.height / 2,
        quality: 60,
        withFlash: this.flashMode !== 'off',
      };
      this.cameraPreview.startRecordVideo(opt)
        .then((file) => {
          console.log('startRecordVideo', file);
        }, (err) => {
          console.log('startRecordVideo', err);
        });
```

**Comment by westonganger** [comment]
This method was added in v0.12.0. Please ensure you have upgraded.
