### ISSUE TITLE
coefficient param is never used, but some lines above it's called with 1f and 1.5f

### ISSUE THREAD

**Issue by agonzalez8** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#624]
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/blob/39cafcd775a1fe940b2247dd8f5a46ce79937b84/src/android/CameraActivity.java#L833

**Comment by westonganger** [comment]
@agonzalez8 Wild appreciate it if you made a PR

**Comment by westonganger** [comment]
This is now fixed in master @ a5caba1
