### ISSUE TITLE
blurry preview image under certain circumstances

### ISSUE THREAD

**Issue by matt2323** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#64]
Hello, 
I'm getting a blurry preview image with a nexus 5 running the newest version of android. It only occurs with the initial call to startCamera and only when the default camera is set to back. 
If set to front, there is no problem. Also if you navigate away for the app, then come back, the image is sharp again. 

I noticed this same behavior with the demo app when I set the default camera to back. 

Thanks, 
Matt

**Comment by tumenor** [comment]
Same problem, only that mine occours with front camera aswell.

**Comment by ptrpt** [comment]
Same problem here... When I open the app, no matter which default camera I set, I get the blurry live-view. But when I switch the camera (using the switchCamera() method) it turns sharp and clear...

**Comment by ptrpt** [comment]
Apparently, this is the same issue: #53 

And on the issue above there is also a solution!

**Comment by westonganger** [comment]
Fixed in master.
