### ISSUE TITLE
ToBack does not work.

### ISSUE THREAD

**Issue by jonatarussi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#643]
Even setting the ToBack to `true`, the camera overlays the HTML. `body` is with `background: transparent`.

Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    android: 9.0.0`

`cordova-plugin-camera-preview: 0.12.1
`

**Comment by nitriixxx** [comment]
Hey @jonatarussi ,

I got the same issue, I made a pull request about it => https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/644

**Comment by westonganger** [comment]
@jonatarussi can you check out #644 and see if it solves your issues?

**Comment by westonganger** [comment]
This is now fixed in master.

**Comment by westonganger** [comment]
v0.12.2 is now released which contains the fix from #644
