### ISSUE TITLE
Picture is out of focus

### ISSUE THREAD

**Issue by sortiz4** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#645]
I've run into an issue on the Galaxy S21 Ultra where the picture is out of focus while the preview is in focus. The preview has no problem autofocusing on the subject but the focal plane changes when the picture is taken. This seems to be the only device where this is happening. I suspect this might be a Samsung issue though... in fact it seems like an OTA update from Samsung in March is when the issue started.

Here are the options I have used with `CameraPreview.startCamera`. 

```javascript
const options = {
  x: 0,
  y: 0,
  camera: CameraPreview.CAMERA_DIRECTION.BACK,
  width: this.getPreviewWidth(),
  height: this.getPreviewHeight(),
  toBack: true,
};
```

Here are the options I have used with `CameraPreview.takePicture` and `CameraPreview.takeSnapshot`. 

```javascript
const options = {
  width: this.getPictureWidth(),
  height: this.getPictureHeight(),
  quality: 65,
};
```

**Comment by matiasfic** [comment]
The same happen on OnePlus 6T
