### ISSUE TITLE
[Request] Save Location

### ISSUE THREAD

**Issue by gabereiser** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#65]
Requesting that the save location be changed from the Assets Library for iOS to the Documents Folder.  This prevents images taken with the app from being accessed from the photo library.  I can rewrite the image save/load methods but would like to see it as official.

**Comment by zwlcoding** [comment]
@gabereiser 

Hi,Friend.
Could you please provide your code. I have the same needs. But I will not native code

**Comment by andrea-86** [comment]
There's a way to have back  the path of captured image instead of the base64 data?

**Comment by westonganger** [comment]
Please see master readme for latest instructions.
