### ISSUE TITLE
Too zoomed in vs. native camera

### ISSUE THREAD

**Issue by thomascrown** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#66]
Only tested this on Android, but the view is too zoomed in. Is there any way to zoom it out?

**Comment by stephan-nordnes-eriksen** [comment]
I have seen this too. The pictures which is taken appears to be correct, but on some devices the preview video is zoomed in. Have not been able to figure out why this is happening or how to fix it. (I am not the maintainer)

**Comment by baslentfert** [comment]
yes i discovered the issue as well, maybe i have a fix for this.

**Comment by Djagu** [comment]
@baslentfert Can you share your fix please ?

**Comment by stephan-nordnes-eriksen** [comment]
I have fixed this issue on my branch, but I have also changed a lot of the behavior so the libraries are no longer compatible.

**Comment by baslentfert** [comment]
i updated my branch, with my latest developments. but i only needed to take a picture in hi res and display it.
maybe it is a start for somebody else.

**Comment by rafaelbuiu** [comment]
Is there any solution for this issue out there?
I cannot find a solution for it anywhere.
@baslentfert How "taking the picture in hi-res" fix the issue if it is the native camera preview that is zoomed in?
Thank you for you help.

**Comment by erperejildo** [comment]
Please, try new version.
