### ISSUE TITLE
is platform browser supported ?

### ISSUE THREAD

**Issue by acevedodamian** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#673]
Hi i would like to ask if platform browser is supported , im not seeing it in plugin.xml ( but im seeing a folder www )

thanks a lot !

**Comment by andreszs** [comment]
There is no browser platform for this plugin.

The **www** folder always contains the [Plugin Class Mapping](https://cordova.apache.org/docs/en/2.5.0/guide/plugin-development/android/#plugin-class-mapping) file, required for JS to native interaction.
