### ISSUE TITLE
error building with xcode 13.4.1

### ISSUE THREAD

**Issue by theanonymoustrader** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#677]
Hello!

I'm trying to run a simple app with xcode 13.4.1, but I've got an error on the file CameraPreview.m.
The error is on the line 66 , "assignment to readonly property", as you can see in the screenshot.

How I can solve it?
<img width="1016" alt="Schermata 2022-07-20 alle 15 08 25" src="https://user-images.githubusercontent.com/106443394/179989926-94484075-0df6-488c-a15b-81811df92824.png">

**Comment by hvaughan3** [comment]
I had the same problem. Looks like it may be due to latest toBack changes but not sure what the fix is. I ended up installing the latest version in NPM instead of pinning to master branch.

`cordova plugin add cordova-plugin-camera-preview@0.12.3`

**Comment by westonganger** [comment]
@thrnjica seems like your PR #676 caused this, can you comment here. What xcode/ios versions did you test with?

**Comment by westonganger** [comment]
I have now rolled back the recent ios toBack changes as per https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/676#issuecomment-1221153232

**Comment by westonganger** [comment]
@Saqib92 the iOS toBack feature was not removed and it already existed before, just the latest commit that changed the code was rolled back.

**Comment by Saqib92** [comment]
> @Saqib92 the iOS toBack feature was not removed and it already existed before, just the latest commit that changed the code was rolled back.

still toBack is not working on iOS.
