### ISSUE TITLE
migrate camera preview plugin from plugin.cordova.io to npm

### ISSUE THREAD

**Issue by mastroganjalf** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#68]
when I try to compile the app tells me that the library plugin.cordova.io is deprecated, and reading this article https://cordova.apache.org/news/2015/09/08/CPR-readonly.html say you should bring plug up npm

**Comment by westonganger** [comment]
This plugin is now on npm. Check the Readme for any changes to setup.
