### ISSUE TITLE
Getting the result image data of take picture  

### ISSUE THREAD

**Issue by mustaphaaassab** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#73]
Hello,
Thank you for the plugin it works for me, but the problem with me is that i can not store or get the image (result of the capture). i work in android. 
please can you help me

**Comment by irwynks** [comment]
Hello!

I'm running into the same issue. setOnPictureTakenHandler doesn't seem to be registering/ isn't firing (I'm not very good with java..)

Amazing work btw!

**Comment by mbppower** [comment]
Hi guys, check your permissions in the AndroidManifest.
Please refer to the demo app: https://github.com/mbppower/CordovaCameraPreviewApp/blob/master/platforms/android/AndroidManifest.xml

Cheers

**Comment by irwynks** [comment]
Hi Marcel,
Thanks for getting back. Not sure what it was but just tried to reboot and it works fine now.

**Comment by mustaphaaassab** [comment]
Thanks guys it work fine
