### ISSUE TITLE
Feature request - Display camera live preview in a html element.

### ISSUE THREAD

**Issue by Richard-Walker** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#74]
Hi,

Would it be possible to embed the preview stream in a DOM element such as `<canvas>` or `<video>`.

KR,

Richard

**Comment by mbppower** [comment]
Hi Richard, that is not supported right know. I believe that the rendering performance would me very slow.

**Comment by irwynks** [comment]
Hi guys. I've forked the project and have been mucking around with the CameraActivity.java file. I managed to prematurely send the Bitmap btyestream back through setOnPictureTakenHandler as a base64 string upon each picture being taken (instead of creating a file and saving it). You can then render to a canvas element/image. I stuck it on an interval so that the is updated every x milliseconds. It runs really smooth! Though my device is heating up quite a bit...
(Once again, I don't know much java)

**Comment by Richard-Walker** [comment]
Hi,

Good to read you guys. Nice to see that this project is active :)

Let me explain what I am trying to achieve...

My goal is to make a web app I wrote using [trackingjs](http://trackingjs.com) work on mobile, more specifically on iOS which does not support `getUserMedia`.

The app tracks objects from the camera stream.

The **trackingjs** library works by specifying a `<video>` element to track in the tracker constructor.

If it is not possible to embed the camera preview in such an element, maybe a more suitable way is to call the tracking method on each frame individually.

Indeed, the library has a method `track(pixels, width, height)`.
The parameter `pixels`, which contains the image data, expects an `Uint8ClampedArray` ([see mdn doc](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray)).

Would it be possible to expose the frames in such format?
(I don't know objective C)

@irwynks : in Android, I've read that WebRTC is now supported, so it should be possible to do it in a pure web app (without cordova). You can check [my app](http://richard-walker.github.io/pr-headstill/) to see if it works ;)

**Comment by irwynks** [comment]
Richard,

Thanks for that! Sounds perfect for what I'm trying to get done (which is decoding QR codes in the background upon said code being presented in front of camera without a preview window). Trackingjs also looks epic.

As for going from Bitmap bytestream to RGBA, I would have no clue at this point. This is my first time working with image manipulation. <a href='http://answers.unity3d.com/questions/511676/converting-a-byte-array-to-a-color-array.html'>This</a> could be worth a read for you however (If you havent come across it already). Hope it helps!

**Comment by bassemBMI** [comment]
Hi Richard,
Have you found a solution for this issue ? I'm facing the same situation and I tried different camera plugins but no one work as I want.
Thx.

**Comment by RichardBoyder** [comment]
Hi there . I've been waiting for some reply but no luck, I really want it to work .

I'll keep a eye out and if you do the same I'm sure we can find the answer.

The Cordova camera is really a tricky one... Change one thing and something else breaks .

**Comment by dirtybluejeans** [comment]
This plugin captures frames and dumps them onto a GL context. Looking at the code (which I must admin I don't understand much of, I'm not a native ios guy), I can see that the image data is being captured in a structure which is most likely the same as the ImageData structure that a Canvas 2d context requires for it's putImageData call. Maybe if there could be a JS callback with a pointer to such data, which if it returns false then the plugin doesn't need to render the data (the callback will be responsible for rendering it). Sounds doable - but like I said, beyond my capabilities. I understand @mbppower 's concerns around performance, but at least iOS devices are certainly fast enough to render the data - look at the amazing 3D visualizations that you can do in google cardboard, three.js etc.. 

I can help test if someone can help build!

Thanks

**Comment by mluis** [comment]
@irwynks did you managed to put the base64 string back on the html canvas?
