### ISSUE TITLE
Not able to find this Plugin on Phonegap

### ISSUE THREAD

**Issue by Ankit-Prajapati** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#76]
Hello,

I am not able to find this Plugin on Phonegap Plugins List. (https://build.phonegap.com/plugins).
Nor I am able to find this Plugin here: http://cordova.apache.org/plugins/
Has this Plugin been removed or depreciated?

This Plugin accomplishes a great functionality in my App.

And now when I am trying to build the Template, this Plugin is giving me Error.
Hence I am not able to add a new Plugin, because to add a new Plugin I need to remove this Camera Plugin first, which will in turn disables my functionality achieved by this Camera Plugin.

Can you please help me out to find the proper Solution/Work Around?

**Comment by westonganger** [comment]
I have added this plugin to npm. Please re-read the Readme and try with the new instructions
