### ISSUE TITLE
ionic white background-color view

### ISSUE THREAD

**Issue by web75018** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#77]
Hi guys
i'm still having a white background-color when i put "toBack = true;".
i added "<body ng-app="starter" style="background-color: transparent;">".

any solution?
Thanks

**Comment by iarry** [comment]
One of your `ion-` directives isn't transparent. Inspect them in your browser and check. For me it was my `ion-pane`.

**Comment by web75018** [comment]
thanks a lof fo reply.
i did the same too, on each ion-*. but still having this same error.
i checked the CameraPreview.m, and it's same ok too.
                        self.webView.opaque = NO;
                        self.webView.backgroundColor = [UIColor clearColor];

did i missed some thing?

**Comment by iarry** [comment]
The fix I mentioned worked for me on Android, I hadn't checked iOS but I'm seeing the same issue as you now that I've tested on iOS. 

I've tried setting all `subviews` in the `webView` to be transparent, as well as any `.platform-ios` classes to a transparent background and still no luck. I've posted this on the Ionic forums [here](https://forum.ionicframework.com/t/transparent-webview-in-ios/41118).

**Comment by iarry** [comment]
I've found a fix. The calls to `self.webView.opaque = NO;
self.webView.backgroundColor = [UIColor clearColor];` need to happen within the `webViewDidFinishLoad` of the `MainViewController`. It's how the Google Maps plugin works. [Here's](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/685) the issue tracker you may want to bookmark as well.

I forked this plugin [here](https://github.com/iarry/CordovaCameraPreview) with the fix so feel free to use it, I'll make a pull request after I solve another issue I've been having in Android. The current fix should really be put in a separate Util's file but for now this solution should work fine.

**Comment by wasabeto** [comment]
I need to compile my APP in PhoneGap but does not recognize the upgrade you did to him . any ideas.. ?

**Comment by PinoDominique** [comment]
I don't know if you have fixed your issue but here what I've done to fix it. You will have to edit the ionic main css file (www/lib/ionic/css/ionic.css). There, you go to the ".view" section and set the background-color value to transparent.

**Comment by KamranakwardaK** [comment]
Just add 
glClearColor(0, 0, 0, 0);
in CameraRendarControl.m

**Comment by westonganger** [comment]
iOS is fixed. Please use master and follow the instruction in the readme.

**Comment by darkthsideous** [comment]
@KamranAliKhan01 help
