### ISSUE TITLE
Barcode scan

### ISSUE THREAD

**Issue by PSEAlex** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#80]
It is possible to integrate a barcode scanner with this plugin?

**Comment by 526avijitgupta** [comment]
+1

**Comment by Giriton** [comment]
+1

**Comment by maxharland** [comment]
+1

**Comment by westonganger** [comment]
Closing as this is outside of the scope of this project however I would love to have another plugin integrate with this one to provide that functionality.
