### ISSUE TITLE
iOS picture appears 90 degree anticlockwise

### ISSUE THREAD

**Issue by MrBramard** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#81]
Hi,

I'm working on a Android/iOS app and I want to display a picture taken with this plugin.
The plugin works fine on Android but when I take a picture with the iOS version, the picture taken appears on the side, 90 degree anticlockwise. 
The camera preview before the picture is taken is in the right orientation.
The picture taken is also saved on the iOS Photos app and is not on the side.

The first picture is a screenshot of the app and the second is the image saved on iOS Photos.

Sorry for my English, I hope my problem is understandable and that someone can help me with it.

![img_0072](https://cloud.githubusercontent.com/assets/1318811/12695994/484148b2-c75e-11e5-9514-2692f9245f5c.jpg)
![img_0071](https://cloud.githubusercontent.com/assets/1318811/12695996/4ac4486e-c75e-11e5-9b70-5d5e0700946d.jpg)

**Comment by andrea-86** [comment]
Same problem....
Did you find any solution?

**Comment by KamranakwardaK** [comment]
It doesn't show any preview on my project

**Comment by KamranakwardaK** [comment]
@MrBramard How did you get picture output, I'm not getting any img with the URL
