### ISSUE TITLE
Import Intel XDK problem

### ISSUE THREAD

**Issue by adanreyes18** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#84]
_Hi I have had problems importing the plugin Intel XDK , tells me that there is no branch of this project , please help, this is my message of Intel XDK:

> "Command failed: C:\Users\Adán\AppData\Local\Intel\XDK\bin\git\bin\git.exe --exec-path=C:\Users\Adán\AppData\Local\Intel\XDK\bin\git\libexec\git-core -c init.templatedir=C:\Users\Adán\AppData\Local\Intel\XDK\bin\git\share\git-core\templates clone https://github.com/mbppower/CordovaCameraPreview.git C:\Users\ADN~1\AppData\Local\Temp\git\1454603968808 --single-branch --depth=1 --branch Camera Cloning into 'C:\Users\ADN~1\AppData\Local\Temp\git\1454603968808'... warning: Could not find remote branch Camera to clone. fatal: Remote branch Camera not found in upstream origin Unexpected end of command stream"

**Comment by diegolamonica** [comment]
Hi @adanreyes18, I've imported it using this value into _Repo URL_ field `https://github.com/mbppower/CordovaCameraPreview` and the value `skanygin` into the _GIT Ref_ field.

![cordovacamerapreview](https://cloud.githubusercontent.com/assets/409514/14395777/fb2aa47c-fdd3-11e5-8a36-6492ee6e50bb.png)
