### ISSUE TITLE
Not getting anything from the file path returned on Android.

### ISSUE THREAD

**Issue by troyberg** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#86]
The result I get from the PictureTakenHandler, when on Android, looks like `/data/data/com.myAppName/files/camerapreview_09_02_2016_1152_04_preview.jpg`

From what I understand, that looks correct. However, when I try to simply use that path as the src attribute in an <img> tag, I just get a broken image like maybe there is no file there.

Any idea why this may be happening?
Does that path look correct?
Might it be failing to actually store the picture there?

**Comment by highercomve** [comment]
Use adb shell and search in that path. For me the file is there, but i don't know how to read it and create a File object using the that file.

**Comment by Djagu** [comment]
I have the same issue, have you found any solutions ?

**Comment by highercomve** [comment]
In my case i have the files in the `/data` folder and the webview can't access that folder, therefore using the [cordova file plugin](https://github.com/apache/cordova-plugin-file) i use this function (the $q is a angular function to return a promise, you can use whatever fit you)

```
 function readAsDataURL(path, file) {
     var q = $q.defer();

     if ((/^\//.test(file))) {
         q.reject('file-name cannot start with \/');
     }

     try {
         $window.resolveLocalFileSystemURL(path, function(fileSystem) {
             fileSystem.getFile(file, {
                 create: false
             }, function(fileEntry) {
                 fileEntry.file(function(fileData) {
                     var reader = new FileReader();
                     reader.onloadend = function(evt) {
                         if (evt.target.result !== undefined || evt.target.result !== null) {
                             q.resolve(evt.target.result);
                         } else if (evt.target.error !== undefined || evt.target.error !== null) {
                             q.reject(evt.target.error);
                         } else {
                             q.reject({
                                 code: null,
                                 message: 'READER_ONLOADEND_ERR'
                             });
                         }
                     };
                     reader.readAsDataURL(fileData);
                 });
             }, function(error) {
                 q.reject(error);
             });
         }, function(err) {
             q.reject(err);
         });
     } catch (e) {
         q.reject(e);
     }

     return q.promise;
 }
```

and then after take the picture (this function is the callback of takepic function on camerapreview)

```
function extractBase64FromNativeUrl(fileurl) {
    var filename = fileurl.split('/').pop()
    readAsDataURL(cordova.file.dataDirectory, filename)
        .then(result => {
            // result is the base 64 of the image
        })
        .catch(error => {
            console.log(error)
        })
}
```

I hope that can help you

**Comment by troyberg** [comment]
@Djagu Yes I have. Sorry. I should have posted back much sooner, but I had forgotten I posted here. I still haven't been able get a path that I could use directly in an <img>'s src attribute, but my ultimate goal was to get the file's base64 for database storage data which works as a src attribute as well, so hopefully this helps you too.

`				resolveLocalFileSystemURL('file:///'+result[1], function(fileEntry) {
				    fileEntry.file(function(file) {
				        var reader = new FileReader();
				        reader.onload = function(event) {
				            base64 = event.target.result; //Here is your base64 string
				        };
				        reader.readAsDataURL(file);
				    });
				});`

After digging around a few different places, this is what my code looks like. Maybe you will understand what is going on here more than I do in order to better use it to fit your purposes. Unfortunately, I still don't have a very firm grasp on handling files with JavaScript, but this got me the base64 data that I needed. 

**Important Note: You need to append "file:///" to the beginning of your result in order for resolveLocalFileSystemURL() to work.

I hope that this helps.

**Comment by Djagu** [comment]
@highercomve, @troyberg Thanks to both of you, works perfectly !

**Comment by erperejildo** [comment]
I was struggling with this. Thanks for 'file:///'+result[1]

**Comment by dnmd** [comment]
@Djagu / @erperejildo appending 'file:///' makes me think it fixes it for Android, did you by any chance also tested it on iOS? Just because the file system structure is a [little different](https://github.com/apache/cordova-plugin-file#file-system-layouts)

**Comment by eeerrrttty** [comment]
could not resolve here.

**Comment by eeerrrttty** [comment]
what is the result[1] ??
