### ISSUE TITLE
it seems dont support android 6.0

### ISSUE THREAD

**Issue by billyct** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#89]
when i use it the app will flash back.

**Comment by techieyann** [comment]
Android 6.0 requires [explicit permission requests](https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#android-permissions).


I'm sure I'll run into more issues in the future, but this is how I got the plugin working for me:

In **CameraPreview.java**:
- add to the imports:
```javascript
import android.Manifest;
import android.content.pm.PackageManager;
import java.util.Arrays;
```
- inside the CameraPreview class, add to the private vars:
```javascript
private final String [] permissions = {
  Manifest.permission.CAMERA,
  Manifest.permission.READ_EXTERNAL_STORAGE,
  Manifest.permission.WRITE_EXTERNAL_STORAGE
};
private final int permissionsReqId = 0;
private CallbackContext execCallback;
private JSONArray execArgs;`
```
- in the execute function, replace the `else if (startCameraAction.equals(action))` with:
```javascript
else if (startCameraAction.equals(action)) {
  if (cordova.hasPermission(permissions[0])) {
    return startCamera(args, callbackContext);
  }
  else {
    execCallback = callbackContext;
    execArgs = args;
    cordova.requestPermissions(this, permissionsReqId, permissions);
  }
}
```
- and finally add this function:
```javascript
@Override
public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws JSONException {
  for(int r:grantResults)
  {
    if(r == PackageManager.PERMISSION_DENIED)
    {
      execCallback.sendPluginResult(new PluginResult(PluginResult.Status.ILLEGAL_ACCESS_EXCEPTION));
      return;
    }
  }
  if (requestCode == permissionsReqId) {
    startCamera(execArgs, execCallback);
  }
}
```

**Comment by chen1203** [comment]
thanks @techieyann ! it works for me!

**Comment by zyf0330** [comment]
@westonganger Hope you to add code to request runtime permission of Camera and WRITE_EXTERNAL_STORAGE.

**Comment by dnmd** [comment]
Although the solution from @techieyann works, I used the excellent  [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin). All I needed to do is call the "requestCameraAuthorization", the user is prompted and all works like a charm :)

````javascript
cordova.plugins.diagnostic.requestCameraAuthorization(function(status){
    console.log("Authorization request for camera use was " + (status == cordova.plugins.diagnostic.permissionStatus.GRANTED ? "granted" : "denied"));
}, function(error){
    console.error(error);
});
````

**Comment by westonganger** [comment]
Please use master, all permission issues have been fixed.
