### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by ivanboring** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#90]
First off, this is a great plugin.

My problem is that I've got everything working except for the setOnPictureTakenHandler. I'm running on iOS.

I do get a result back that is a file with the assets-library:// protocol, but when I try to use it, it won't work. I used XMLHttpRequest to see if I can reach the file, but it get's file not found.

When I go into the photos app, I can see the photo, so it has been saved. I can't just reach it. Any thoughts? I'm guessing this issue is not necessary connected to this plugin

**Comment by dagda01** [comment]
I have the same issue, have you find any solution?

**Comment by ivanboring** [comment]
Not a real solution, but it seems that the Cordova iPhone library 3.5 has access to the files. So it works if you revert your "cordova platform ios" to an earlier version.

**Comment by westonganger** [comment]
File saving is no longer supported by this plugin. It now returns base64 data and you the developer must choose what to do with that data. Closing.
