### ISSUE TITLE
base64 issue

### ISSUE THREAD

**Issue by dagda01** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#91]
Hello, 

I can't transfer the picture. Here the code I use. It's maybe the "type" of path who don't correct but I don't know how to change it. Thanks. 

document.addEventListener('deviceready', function () {
        cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result){

```
      document.getElementById('originalPicture').src = result[0]; // picture is OK 
      console.log(result[0]); // assets-library://asset/asset.JPG?id=B9BE3C30-A45A-40C2-B565-0117069FE620&ext=JPG

       var options = {
          fileKey: "img",
          fileName: file.name,
          chunkedMode: false,
          mimeType: "image/jpeg"
      };


       $cordovaFileTransfer.upload("http://myAbsoluteUrlToUploadPicture.php", result[0], options)
          .then(function(result) {
            console.log("SUCCESS: " + JSON.stringify(result.response));
          }, function(err) {
            console.log("ERROR: " + JSON.stringify(err));
          }, function (progress) {
            // constant progress updates
          });

      }, false);


    });
```

**Comment by andrea-86** [comment]
Some mistakes in this post.
First of all, the title is Base64 but it not seem to be the problem. (unless your real question is How to have back a base64 image form camerapreview)

In addition, the variable file.name what contains? whe can't see it in the code you have posted.

At all, the first thing i'll try to do is to replace the initial part of the path in result[0] (assets-library://) to obtain a clean URL of the file, and then pass it to the Filetransfer:

```
var cleanPath= result[0].replace("assets-library://","");
 $cordovaFileTransfer.upload("http://myAbsoluteUrlToUploadPicture.php", cleanPath, options)...
```

**Comment by dagda01** [comment]
Thanks for your reply. 

The title of my post isn't correct, apologize about that. I can't change it after create it. 

I try to replace "assets-library://" to "" but now, I have an error code 1.

`FileTransferError {
    code = 1;
    source = "asset/asset.JPG?id=059ACE51-606F-41C3-A6A8-E56AF80402DD&ext=JPG";
    target = "http://atmosphere.io/_dev/snappi/test.php";
}
`

About var options parameters, I forgot to change name during my last try. I change it to

`var options = {
              fileKey: "img",
              fileName: 'test.jpg',
              chunkedMode: false,
              mimeType: "image/jpeg"
          };`


So my complete code is now:

`$ionicPlatform.ready(function() {

    if ($window.cordova &&
              $window.cordova.plugins &&
              $window.cordova.plugins.camerapreview) {

      document.addEventListener('deviceready', function () {
        $window.cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result){

          document.getElementById('originalPicture').src = result[0]; // picture is OK 
          
          var trustHosts = true;
          var options = {
              fileKey: "img",
              fileName: 'test.jpg',
              chunkedMode: false,
              mimeType: "image/jpeg"
          };

          var cleanPath= result[0].replace("assets-library://","");
          console.log(cleanPath);
          $cordovaFileTransfer.upload("http://atmosphere.io/_dev/snappi/test.php", cleanPath, options, trustHosts);
            
        })
      })



      $timeout(function () {
        
         cordova.plugins.camerapreview.startCamera(rect, "back", tapEnabled, dragEnabled, toBack);
         cordova.plugins.camerapreview.show();
         $state.go($state.current, {}, {reload: true});  

      }, 0);

    }
  });
`

Any other idea? 

Thanks a lot

**Comment by westonganger** [comment]
Base64 output is now the default and only return type for taking a picture with this plugin. Please use master and follow the readme as things have changed.
