### ISSUE TITLE
Photo Resolution

### ISSUE THREAD

**Issue by andrea-86** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#94]
Is there a way to decide the photo resolution?

My problem is that photo taked with camerapreview have a 1088x1920 resolution(wich is the max of Camera.sizes size) but photo taken with default camera application have a 1520x2048 resolution(for the actual settings).
I try to pass higher value of height and width to takephoto() function but this doesn't work.

any idea?

**Comment by andrea-86** [comment]
Solution for IOs

Set the sessionPreset in SessionManager.m file

In `- (void) setupSession:(NSString *)defaultCamera`

add following instruction (i added at line 77 of code, but i think you can write where you want)

```
if ([self.session canSetSessionPreset:AVCaptureSessionPresetPhoto]) {
            [self.session setSessionPreset:AVCaptureSessionPresetPhoto];
        }
```
further reference at [IOs Developer Library](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureSession_Class/index.html#//apple_ref/doc/constant_group/Video_Input_Presets)

I'm testing with iPhone 4s with iOS 7.1.2 and the result, after this, is a photo with a 1936x2592px, instead of 720x1280px.

**Comment by erperejildo** [comment]
You can specify the resolution here:
`CameraPreview.takePicture({maxWidth:640, maxHeight:640});`
Do you mean this?

**Comment by westonganger** [comment]
This is fixed in master. Please ensure you are using the latest master and follow the instructions in the readme.
