### ISSUE TITLE
how to use this plugin functions in angularjs controller

### ISSUE THREAD

**Issue by shashankp250** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#96]
I am using ionic to build app, but not able to inject this plugin into angularjs controller. Can you please expose this functions as factory so that someone can directly use this functions in angularjs controller.

For example: All ngcordova plugin has been exposed as angularjs factory.

**Comment by westonganger** [comment]
That is kind of outside the scope of this project. It just adds it to the window. To use it use `CameraPreview` object anywhere in your code.

**Comment by ptrpt** [comment]
I can help you with that ;) I found myself with the ssame problem. The solution is to use this plugin from within a AngularJS controller is to  ensure that Angular only starts after the Cordova app is up and running. 
Here goes a tutorial:

1. Replace the ng-app element with an id of your choice (I chose id="app");
2. On the function deviceReady of cordova app add the following code;
` var domElement = document.getElementById("app");
        angular.bootstrap(domElement, ["cameraApp"]);`
3. Now your Angular app can invoke cordova plugins!

From there you can use the CameraPreview as you wish.

Cheers!

**Comment by westonganger** [comment]
This plugin isn't an angular plugin but it instead attaches itself to the window object. You don't have to inject it into your app. You do need to ensure `deviceready` event has fired so inside your controller/run/config would look like this.

```javascript
document.addeventlistener("deviceready", function(){
  // your code or functions that use any cordova plugins
 cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack)
}, false);
```
