### ISSUE TITLE
Photo Resolution - Android

### ISSUE THREAD

**Issue by pablobianchi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#98]
Hi, thanks for this great plugin !

I want to know if there is a way to use the best camera resolution ?, for example, if I take a photo with the tablet ( using the Android Camera APP ) it saves a picture of 1920 x 1080, but when I use these plugin I can not get a good resolution.

Thanks !

**Comment by shirk3y** [comment]
+1 same issue

**Comment by shirk3y** [comment]
I think this is because photos are taken from preview frames...

**Comment by julitroalves** [comment]
+1 same issue

**Comment by erperejildo** [comment]
Today I had the same problem and I fixed it with @fernandoTinelli solution here:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/53

**Comment by westonganger** [comment]
This is fixed in master.
