### ISSUE TITLE
Is it possible to use this plugin with ionic?

### ISSUE THREAD

**Issue by AlexShmykov** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#99]
Hi guys,
is it possible to use this Plugin with ionic?
I'm not able to inject this into the controller.

**Comment by westonganger** [comment]
Do not inject it,  just use it and it will work. The object is attached to the global namespace.

**Comment by AlexShmykov** [comment]
thx for the fast reply.
could you give me an example, please?
I can't get it to run.

**Comment by westonganger** [comment]
```javascript
$ionicPlatform.ready(function(){
  if(window.cordova){
    $scope.startCamera = function(){
      cordova.plugins.camerapreview.startCamera({x: 0, y: 0, width: screen.width, height: screen.height}, "front", false, false, false);
    };
  }
});
```

**Comment by AlexShmykov** [comment]
I've tried it the way you told me, I guess.
But it still doesn't work.
Maybe you see the mistake?

my app.js file:
`
var app = angular.module('starter', ['ionic', 'ngCordova'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
  
    if(window.cordova && window.cordova.plugins.Keyboard) {
      // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
      // for form inputs)
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      // Don't remove this line unless you know what you are doing. It stops the viewport
      // from snapping when text inputs are focused. Ionic handles this internally for
      // a much nicer keyboard experience.
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
})

.controller('CamCtrl', function ($scope, $ionicPlatform) {
   $ionicPlatform.ready(function(){
   if(window.cordova){
    $scope.startCam = function(){
      var tapEnabled = true; //enable tap take picture
      var dragEnabled = true; //enable preview box drag across the screen
      var toBack = false; //send preview box to the back of the webview
      var rect = {x: 100, y: 100, width: 200, height:200};
      cordova.plugins.camerapreview.startCamera(rect, "front", tapEnabled, dragEnabled, toBack);
    };
   }
 });
})
`

my template.html file: 

`   <ion-content  style="background-color:transparent" class="has-subheader">  
<button class="button" ng-click="startCam()">Start Camera at back</button>
</ion-content>
`

**Comment by westonganger** [comment]
`background-color: transparent` needs to be on the `ion-view` element. Also this is not required if you have set toBack to false because it should be in the front of the webview. 

Do you have the plugin correctly installed, what errors are you getting? Does `cordova.plugins.camerapreview` exist and is not undefined?

**Comment by AlexShmykov** [comment]
I followed the readme file of the plugin.
I installed it like: `cordova plugin add https://github.com/mbppower/CordovaCameraPreview.git`
And i don't get any errors from the console.
What do you mean by: 

> Does cordova.plugins.camerapreview exist and is not undefined?

**Comment by tordnilsen** [comment]
Hi, did you find a solution?

**Comment by Shmkvlx** [comment]
Hi,
Yes, i had to test on a real device!
Its Not possible to Test it in a Browser or in the ionic view App.


Von meinem iPhone gesendet

**Comment by tordnilsen** [comment]
I've tried on a real device. But have no luck. Do you have a complete project to share?

**Comment by flogr** [comment]
Hi @Shmkvlx ,
i'd be interested to in example files. How did you get in running on your device? I'm struggling with testing CameraPreview & Ionic, too. Doesn't work in browser or ionic view app on a real device...

**Comment by flogr** [comment]
I got it working now, too, but only on a real device without ionic view, also no "ngCordova" is needed, as this is initiated globally by ionic.

var app = angular.module('starter', ['ionic'])

        .run(function ($ionicPlatform) {
            $ionicPlatform.ready(function () {
                if (window.cordova && window.cordova.plugins.Keyboard) {
                    cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
                    cordova.plugins.Keyboard.disableScroll(true);
                }
                if (window.StatusBar) {
                    StatusBar.styleDefault();
                }
            });
        })

        .controller('CamCtrl', function ($scope, $ionicPlatform) {
            $ionicPlatform.ready(function () {
                if (window.cordova) {
                    
                    var startCam = function () {
                        var tapEnabled = true; //enable tap take picture
                        var dragEnabled = false; //enable preview box drag across the screen
                        var toBack = true; //send preview box to the back of the webview
                        var rect = {x: 0, y: 0, width: screen.width, height: screen.height};
                        var cameraType = "front" //camera "back" or "front"
                        cordova.plugins.camerapreview.startCamera(rect, cameraType, tapEnabled, dragEnabled, toBack);
                    };
                    
                    //get permission for camera
                    cordova.plugins.diagnostic.requestCameraAuthorization(function(status){
                        startCam();
                    }, function(error){
                        alert("Without the proper permission we can't take picutres, fucker!")
                    });

                    $scope.takePicture = function () {
                        alert("picture taken");
                    }
                    
                }
            });
        })

<body ng-app="starter" ng-controller="CamCtrl">

        <ion-pane class="transparent">
            
            <button class="button" ng-click="takePicture()">Take Picture</button>
            
        </ion-pane>

    </body>

Dont forget to make everything transparent if using toBack = true.

**Comment by Tauqeer1** [comment]
I am getting error while testing on android device , Cannot read property 'startCamera' of undefined , 
cordova.plugins.camerapreview.startCamera({x: 0, y: 0, width: screen.width, height: screen.height}, "front", false, false, false);

**Comment by amit0001** [comment]
Hi. I am able to get the camera started but when trying to take a picture nothing happens. This is my code for that:



` cordova.plugins.camerapreview.takePicture(function(imgData){
         alert('Snap2');
});`

**Comment by amit0001** [comment]
BTW the solution that worked for me is @westonganger 's : 

`$ionicPlatform.ready(function(){
  if(window.cordova){
    $scope.startCamera = function(){
      cordova.plugins.camerapreview.startCamera({x: 0, y: 0, width: screen.width, height: screen.height}, "front", false, false, false);
    };
  }
});`
